
#+TITLE: The Location of Emacs-Lisp Tests

* Introduction

In this document, we describe the relationship between Emacs-Lisp files and
their associated automated test files.


* In Emacs

The Emacs repository contains a very large number of Emacs-Lisp files, many of
which pre-date both formal package support for Emacs and automated unit
testing. The test layout is, therefore, somewhat different than for ELPA
packages.

All paths are relative to the Emacs root directory.

** Source

Lisp files are stored in the ~lisp~ directory or its sub-directories.
Sub-directories are in many cases themed after packages (~gnus~, ~org~,
~calc~), related functionality (~net~, ~emacs-lisp~, ~progmodes~) or status
(~obsolete~).

C source is stored in the ~src~ directory, which is flat.


** Test Files

Automated tests should be stored in the ~test/automated/lisp~ directory. Tests
should reflect the directory structure of the source tree; so tests for files
in the ~emacs-lisp~ source directory should reside in the
~test/automated/lisp/emacs-lisp~ directory.

Tests should normally reside in a file with ~-tests~ added to the name of
the tested source file; hence ~ert.el~ is tested in ~ert-tests.el~, or
~pcase.el~ is tested in ~pcase-tests.el~. Exceptionally, tests for a
single feature may be placed into multiple files of any name which are
themselves placed in a directory named after the feature with ~-tests~
appended, suchj as ~/test/automated/lisp/emacs-lisp/eieio-tests~

Where features of the C source are tested using Emacs-Lisp test files, these
should reside in ~/test/automated/src~ and be named after the C file.

A few test suites which predate this scheme and do not fit cleanly
into it are placed in ~/test/automated/lisp/legacy~.

** Resource Files

Resource files for tests (containing test data) should reside in a directory
named after the feature with a ~-resources~ suffix, and located in the same
directory as the feature. Hence, the lisp file ~flymake.el~ should have test
files in ~/test/automated/lisp/progmodes/flymake-tests.el~ should reside in a
directory called ~/test/automated/lisp/progmodes/flymake-resources~.

No guidance is given for the organisation of resource files inside the
~-resource~ directory; files can be organised at the author's discretion.


* In ELPA

All paths are given relative to the package root.

** Source Files

ELPA lisp files should be stored at top-level within the package.

** Test Files

Test files should normally reside in the ~test~ directory, and be named after
the file being tested, with a ~tests~ suffix added.

** Resources Files

Resource files for tests should reside in the ~dev-resources~ directory. No
guidance is given for the organisation of resource files inside the
~dev-resource~ directory; files can be organised at the author's discretion.




* The Move

** Makefile

Is single directory and doesn't work. Don't know how to do a recursive
make, but actually, the directory structure isn't too deep, so perhaps
we don't care; we can use wildcards with a few slashes in.

./emulation
./erc
./cedet
./cedet/semantic
./cedet/semantic/bovine
./cedet/semantic/decorate
./cedet/semantic/analyze
./cedet/semantic/symref
./cedet/semantic/wisent
./cedet/srecode
./cedet/ede
./vc
./eshell
./term
./play
./nxml
./gnus
./url
./mail
./mh-e
./obsolete
./textmodes
./language
./net
./international
./leim
./leim/ja-dic
./leim/quail
./org
./calc
./emacs-lisp
./calendar
./progmodes


** Helpers

#+begin_src emacs-lisp
  (require 'dash)
  (defun copy-location ()
    (interactive)
    (kill-new
     (format "mv %s %s"
             (file-name-nondirectory
              (buffer-file-name))
             (s-join
              "/"
              (-butlast
               (--drop-while
                (not (string= "lisp" it))
                (split-string
                 (locate-library
                  (symbol-name
                   (symbol-at-point)))
                 "/")))))))
#+end_src

** Move Script


#+begin_src bash
mkdir lisp
mkdir lisp/c
mv Makefile.in lisp

mv add-log-tests.el lisp/vc
mv advice-tests.el lisp/emacs-lisp/nadvice-tests.el
mv auth-source-tests.el lisp/gnus
mv auto-revert-tests.el lisp/autorevert-tests.el
mv bytecomp-tests.el lisp/emacs-lisp
mv calc-tests.el lisp/calc
mv cl-generic-tests.el lisp/emacs-lisp
mv cl-lib-tests.el lisp/emacs-lisp
mv cmds-tests.el src
mv comint-testsuite.el lisp/comint-tests.el
mv compile-tests.el lisp/progmodes
mv completion-tests.el lisp/minibuffer-tests.el
mv core-elisp-tests.el lisp/legacy-tests
mv data-tests.el src
mv dbus-tests.el lisp/net
mv decoder-tests.el lisp/legacy
mv descr-text-test.el lisp/descr-text-tests.el
mv eieio-test-methodinvoke.el lisp/emacs-lisp/eieio-tests
mv eieio-test-persist.el lisp/emacs-lisp/eieio-tests
mv eieio-test.el lisp/emacs-lisp/eieio-tests
mv electric-tests.el lisp
mv emacs-lisp-tests.el lisp/progmodes
mv epg-tests.el lisp
mv ert-tests.el lisp/emacs-lisp
mv ert-x-tests.el lisp/emacs-lisp
mv eshell.el lisp/eshell
mv f90.el lisp/progmodes
mv file-notify-tests.el lisp/filenotify-tests.el
mv files.el lisp/legacy/files-tests.el
mv finalizer-tests.el src
mv flymake-tests.el lisp/progmodes
mv fns-tests.el src
mv font-parse-tests.el lisp/legacy
mv generator-tests.el lisp/emacs-lisp
mv gnus-tests.el lisp/gnus
mv help-fns.el lisp/help-fns-tests.el
mv icalendar-tests.el lisp/calendar
mv imenu-test.el lisp/imenu-tests.el
mv info-xref.el lisp/info-xref-tests.el
mv inotify-test.el src/inotify-tests.el
mv json-tests.el lisp
mv let-alist.el lisp/emacs-lisp/let-alist-tests.el
mv lexbind-tests.el lisp/legacy
mv libxml-tests.el src/xml-tests.el
mv man-tests.el lisp
mv map-tests.el lisp/emacs-lisp
mv message-mode-tests.el lisp/gnus/message-tests.el
mv mule-util.el lisp/international/mule-util-tests.el
mv newsticker-tests.el lisp/net
mv occur-tests.el lisp/legacy
mv package-test.el lisp/emacs-lisp/package-tests.el
mv pcase-tests.el lisp/emacs-lisp
mv print-tests.el src
mv process-tests.el lisp/legacy
mv python-tests.el lisp/progmodes
mv reftex-tests.el lisp/textmodes
mv regexp-tests.el lisp/emacs-lisp/regexp-opt-tests.el
mv replace-tests.el lisp/
mv ruby-mode-tests.el lisp/progmodes
mv sasl-scram-rfc-tests.el lisp/net
mv seq-tests.el lisp/emacs-lisp
mv sgml-mode-tests.el lisp/textmodes
mv simple-test.el lisp/simple-tests.el
mv subr-tests.el lisp/subr-tests.el
mv subr-x-tests.el lisp/emacs-lisp
mv subword-tests.el lisp/progmodes
mv syntax-tests.el lisp/legacy
mv tabulated-list-test.el lisp/emacs-lisp
mv textprop-tests.el lisp/legacy
mv thingatpt.el lisp/thingatpt-tests.el
mv thunk-tests.el lisp/emacs-lisp
mv tildify-tests.el lisp/textmodes
mv timer-tests.el lisp/emacs-lisp
mv tramp-tests.el lisp/net
mv undo-tests.el lisp/legacy
mv url-future-tests.el lisp/url
mv url-util-tests.el lisp/url
mv vc-bzr.el lisp/vc/vc-bzr-tests.el
mv vc-tests.el lisp/vc
mv xml-parse-tests.el lisp/xml-tests.el
mv zlib-tests.el src
#+end_src

** After Script

top level Makefile will need altering
