# .github/workflows/fixme-check.yml -- check for FIXME task labels
#
# This is a GitHub CI workflow
# <https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration>
# to check for FIXME and similar task labels left unresolved in the
# MPS source tree.

name: FIXME check

on:
  # Run as part of CI checks on branch push and on merged pull request.
  - push
  - pull_request
  - workflow_dispatch # allow manual triggering

jobs:
  check-fixme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # see <https://github.com/actions/checkout/blob/main/README.md#usage>
      - run: tool/check-fixme
