;; The contents of this file are loaded into `package-autosuggest-database'
;; and were automatically generate by scraping ELPA for auto-loaded
;; code using the `scrape-elpa' command.  Please avoid updating this
;; file manually!

(
(ada-mode auto-mode-alist "\\.ad[abs]\\'") ;from ~/Source/elpa/packages/ada-mode/ada-mode-autoloads.el
(arbitools auto-mode-alist "\\.trf?\\'" arbitools-mode) ;from ~/Source/elpa/packages/arbitools/arbitools-autoloads.el
(auctex auto-mode-alist "\\.hva\\'" LaTeX-mode) ;from ~/Source/elpa/packages/auctex/auctex-autoloads.el
(bnf-mode auto-mode-alist "\\.bnf\\'") ;from ~/Source/elpa/packages/bnf-mode/bnf-mode-autoloads.el
(chess auto-mode-alist "\\.pgn\\'" chess-pgn-mode) ;from ~/Source/elpa/packages/chess/chess-autoloads.el
(cobol-mode auto-mode-alist "\\.c\\(ob\\|bl\\|py\\)\\'") ;from ~/Source/elpa/packages/cobol-mode/cobol-mode-autoloads.el
(code-cells auto-mode-alist "\\.ipynb\\'" code-cells-convert-ipynb) ;from ~/Source/elpa/packages/code-cells/code-cells-autoloads.el
(csharp-mode auto-mode-alist "\\.cs\\'") ;from ~/Source/elpa/packages/csharp-mode/csharp-mode-autoloads.el
(csv-mode auto-mode-alist "\\.[Cc][Ss][Vv]\\'") ;from ~/Source/elpa/packages/csv-mode/csv-mode-autoloads.el
(csv-mode auto-mode-alist "\\.tsv\\'" tsv-mode) ;from ~/Source/elpa/packages/csv-mode/csv-mode-autoloads.el
(dismal auto-mode-alist "\\.dis\\'" dismal-mode) ;from ~/Source/elpa/packages/dismal/dismal-autoloads.el
(djvu auto-mode-alist "\\.djvu\\'" djvu-init-mode) ;from ~/Source/elpa/packages/djvu/djvu-autoloads.el
(dts-mode auto-mode-alist "\\.dtsi?\\'") ;from ~/Source/elpa/packages/dts-mode/dts-mode-autoloads.el
(ess auto-mode-alist "\\.[Bb][Uu][Gg]\\'" ess-bugs-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.[Bb][Oo][Gg]\\'" ess-bugs-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.[Bb][Mm][Dd]\\'" ess-bugs-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.[Jj][Aa][Gg]\\'" ess-jags-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "/R/.*\\.q\\'" ess-r-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.[rR]\\'" ess-r-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.[rR]profile\\'" ess-r-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "NAMESPACE\\'" ess-r-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "CITATION\\'" ess-r-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.[Rr]out\\'" ess-r-transcript-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess interpreter-mode-alist "Rscript" ess-r-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess interpreter-mode-alist "r" ess-r-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "/Makevars\\(\\.win\\)?\\'" makefile-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "DESCRIPTION\\'" conf-colon-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.Rd\\'" Rd-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.[Ss]t\\'" S-transcript-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.Sout\\'" S-transcript-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(ess auto-mode-alist "\\.[Ss][Aa][Ss]\\'" SAS-mode) ;from ~/Source/elpa/packages/ess/lisp/ess-autoloads.el
(gle-mode auto-mode-alist "\\.gle\\'") ;from ~/Source/elpa/packages/gle-mode/gle-mode-autoloads.el
(gpr-mode auto-mode-alist "\\.gpr\\'") ;from ~/Source/elpa/packages/gpr-mode/gpr-mode-autoloads.el
(html5-schema auto-mode-alist "\\.html?\\'" nxml-mode) ;from ~/Source/elpa/packages/html5-schema/html5-schema-autoloads.el
(jgraph-mode auto-mode-alist "\\.jgr\\'") ;from ~/Source/elpa/packages/jgraph-mode/jgraph-mode-autoloads.el
(json-mode auto-mode-alist "\\.json\\'") ;from ~/Source/elpa/packages/json-mode/json-mode-autoloads.el
(lmc auto-mode-alist "\\.elmc\\'" lmc-asm-mode) ;from ~/Source/elpa/packages/lmc/lmc-autoloads.el
(matlab-mode auto-mode-alist "\\.tlc\\'" tlc-mode) ;from ~/Source/elpa/packages/matlab-mode/matlab-mode-autoloads.el
(matlab auto-mode-alist "\\.tlc\\'" tlc-mode) ;from ~/Source/elpa/packages/matlab/matlab-autoloads.el
(muse auto-mode-alist "\\.muse\\'" muse-mode-choose-mode) ;from ~/Source/elpa/packages/muse/lisp/muse-autoloads.el
(auctex auto-mode-alist "\\.drv\\'" latex-mode) ;from ~/Source/elpa/packages/names/tests/auctex-11.87.7/auctex-autoloads.el
(auctex auto-mode-alist "\\.dtx\\'" doctex-mode) ;from ~/Source/elpa/packages/names/tests/auctex-11.87.7/auctex-autoloads.el
(nftables-mode auto-mode-alist "\\.nft\\(?:ables\\)?\\'") ;from ~/Source/elpa/packages/nftables-mode/nftables-mode-autoloads.el
(nftables-mode auto-mode-alist "/etc/nftables.conf") ;from ~/Source/elpa/packages/nftables-mode/nftables-mode-autoloads.el
(nftables-mode interpreter-mode-alist "nft\\(?:ables\\)?") ;from ~/Source/elpa/packages/nftables-mode/nftables-mode-autoloads.el
(omn-mode auto-mode-alist "\\.pomn\\'") ;from ~/Source/elpa/packages/omn-mode/omn-mode-autoloads.el
(omn-mode auto-mode-alist "\\.omn\\'") ;from ~/Source/elpa/packages/omn-mode/omn-mode-autoloads.el
(poke-mode auto-mode-alist "\\.pk\\'") ;from ~/Source/elpa/packages/poke-mode/poke-mode-autoloads.el
(pspp-mode auto-mode-alist "\\.sps\\'") ;from ~/Source/elpa/packages/pspp-mode/pspp-mode-autoloads.el
(python auto-mode-alist "/\\(?:Pipfile\\|\\.?flake8\\)\\'" conf-mode) ;from ~/Source/elpa/packages/python/python-autoloads.el
(rec-mode auto-mode-alist "\\.rec\\'") ;from ~/Source/elpa/packages/rec-mode/rec-mode-autoloads.el
(rnc-mode auto-mode-alist "\\.rnc\\'") ;from ~/Source/elpa/packages/rnc-mode/rnc-mode-autoloads.el
(sed-mode auto-mode-alist "\\.sed\\'") ;from ~/Source/elpa/packages/sed-mode/sed-mode-autoloads.el
(sed-mode interpreter-mode-alist "sed") ;from ~/Source/elpa/packages/sed-mode/sed-mode-autoloads.el
(shen-mode auto-mode-alist "\\.shen\\'") ;from ~/Source/elpa/packages/shen-mode/shen-mode-autoloads.el
(sisu-mode auto-mode-alist "\\.ss[imt]\\'") ;from ~/Source/elpa/packages/sisu-mode/sisu-mode-autoloads.el
(smalltalk-mode auto-mode-alist "\\.st\\'") ;from ~/Source/elpa/packages/smalltalk-mode/smalltalk-mode-autoloads.el
(sml-mode auto-mode-alist "\\.s\\(ml\\|ig\\)\\'") ;from ~/Source/elpa/packages/sml-mode/sml-mode-autoloads.el
(sml-mode auto-mode-alist "\\.cm\\'" sml-cm-mode) ;from ~/Source/elpa/packages/sml-mode/sml-mode-autoloads.el
(sml-mode auto-mode-alist "\\.grm\\'" sml-yacc-mode) ;from ~/Source/elpa/packages/sml-mode/sml-mode-autoloads.el
(sql-cassandra auto-mode-alist "\\.cql\\'" sql-mode) ;from ~/Source/elpa/packages/sql-cassandra/sql-cassandra-autoloads.el
(sxhkdrc-mode auto-mode-alist "sxhkdrc\\'") ;from ~/Source/elpa/packages/sxhkdrc-mode/sxhkdrc-mode-autoloads.el
(systemd auto-mode-alist "\\.automount\\'" systemd-automount-mode) ;from ~/Source/elpa/packages/systemd/systemd-autoloads.el
(systemd auto-mode-alist "\\.mount\\'" systemd-mount-mode) ;from ~/Source/elpa/packages/systemd/systemd-autoloads.el
(systemd auto-mode-alist "\\.path\\'" systemd-path-mode) ;from ~/Source/elpa/packages/systemd/systemd-autoloads.el
(systemd auto-mode-alist "\\.service\\'" systemd-service-mode) ;from ~/Source/elpa/packages/systemd/systemd-autoloads.el
(systemd auto-mode-alist "\\.socket\\'" systemd-socket-mode) ;from ~/Source/elpa/packages/systemd/systemd-autoloads.el
(systemd auto-mode-alist "\\.swap\\'" systemd-swap-mode) ;from ~/Source/elpa/packages/systemd/systemd-autoloads.el
(systemd auto-mode-alist "\\.timer\\'" systemd-timer-mode) ;from ~/Source/elpa/packages/systemd/systemd-autoloads.el
(vcard auto-mode-alist "\\.[Vv][Cc][Ff]\\'" vcard-mode) ;from ~/Source/elpa/packages/vcard/vcard-autoloads.el
(wisi auto-mode-alist "\\.parse_table.*\\'" wisitoken-parse_table-mode) ;from ~/Source/elpa/packages/wisi/wisi-autoloads.el
(wisitoken-grammar-mode auto-mode-alist "\\.wy\\'" simple-indent-mode) ;from ~/Source/elpa/packages/wisitoken-grammar-mode/wisitoken-grammar-mode-autoloads.el
(wisitoken-grammar-mode auto-mode-alist "\\.wy\\'") ;from ~/Source/elpa/packages/wisitoken-grammar-mode/wisitoken-grammar-mode-autoloads.el
(adoc-mode auto-mode-alist "\\.a\\(?:scii\\)?doc\\'") ;from ~/Source/nongnu/packages/adoc-mode/adoc-mode-autoloads.el
(apache-mode auto-mode-alist "/\\.htaccess\\'") ;from ~/Source/nongnu/packages/apache-mode/apache-mode-autoloads.el
(apache-mode auto-mode-alist "/\\(?:access\\|httpd\\|srm\\)\\.conf\\'") ;from ~/Source/nongnu/packages/apache-mode/apache-mode-autoloads.el
(apache-mode auto-mode-alist "/apache2/.+\\.conf\\'") ;from ~/Source/nongnu/packages/apache-mode/apache-mode-autoloads.el
(apache-mode auto-mode-alist "/httpd/conf/.+\\.conf\\'") ;from ~/Source/nongnu/packages/apache-mode/apache-mode-autoloads.el
(apache-mode auto-mode-alist "/apache2/sites-\\(?:available\\|enabled\\)/") ;from ~/Source/nongnu/packages/apache-mode/apache-mode-autoloads.el
(arduino-mode auto-mode-alist "\\.pde\\'") ;from ~/Source/nongnu/packages/arduino-mode/arduino-mode-autoloads.el
(arduino-mode auto-mode-alist "\\.ino\\'") ;from ~/Source/nongnu/packages/arduino-mode/arduino-mode-autoloads.el
(beancount auto-mode-alist "\\.beancount\\'" beancount-mode) ;from ~/Source/nongnu/packages/beancount/beancount-autoloads.el
(bison-mode auto-mode-alist "\\.y\\'") ;from ~/Source/nongnu/packages/bison-mode/bison-mode-autoloads.el
(bison-mode auto-mode-alist "\\.l\\'" flex-mode) ;from ~/Source/nongnu/packages/bison-mode/bison-mode-autoloads.el
(bison-mode auto-mode-alist "\\.jison\\'" jison-mode) ;from ~/Source/nongnu/packages/bison-mode/bison-mode-autoloads.el
(bqn-mode auto-mode-alist "\\.bqn\\'") ;from ~/Source/nongnu/packages/bqn-mode/bqn-mode-autoloads.el
(bqn-mode interpreter-mode-alist "bqn") ;from ~/Source/nongnu/packages/bqn-mode/bqn-mode-autoloads.el
(clojure-mode auto-mode-alist "\\.\\(clj\\|cljd\\|dtm\\|edn\\|lpy\\)\\'") ;from ~/Source/nongnu/packages/clojure-mode/clojure-mode-autoloads.el
(clojure-mode auto-mode-alist "\\.cljc\\'" clojurec-mode) ;from ~/Source/nongnu/packages/clojure-mode/clojure-mode-autoloads.el
(clojure-mode auto-mode-alist "\\.cljs\\'" clojurescript-mode) ;from ~/Source/nongnu/packages/clojure-mode/clojure-mode-autoloads.el
(clojure-mode auto-mode-alist "\\(?:build\\|profile\\)\\.boot\\'") ;from ~/Source/nongnu/packages/clojure-mode/clojure-mode-autoloads.el
(clojure-mode interpreter-mode-alist "bb") ;from ~/Source/nongnu/packages/clojure-mode/clojure-mode-autoloads.el
(clojure-mode interpreter-mode-alist "nbb" clojurescript-mode) ;from ~/Source/nongnu/packages/clojure-mode/clojure-mode-autoloads.el
(coffee-mode auto-mode-alist "\\.coffee\\'") ;from ~/Source/nongnu/packages/coffee-mode/coffee-mode-autoloads.el
(coffee-mode auto-mode-alist "\\.iced\\'") ;from ~/Source/nongnu/packages/coffee-mode/coffee-mode-autoloads.el
(coffee-mode auto-mode-alist "Cakefile\\'") ;from ~/Source/nongnu/packages/coffee-mode/coffee-mode-autoloads.el
(coffee-mode auto-mode-alist "\\.cson\\'") ;from ~/Source/nongnu/packages/coffee-mode/coffee-mode-autoloads.el
(coffee-mode interpreter-mode-alist "coffee") ;from ~/Source/nongnu/packages/coffee-mode/coffee-mode-autoloads.el
(d-mode auto-mode-alist "\\.d[i]?\\'") ;from ~/Source/nongnu/packages/d-mode/d-mode-autoloads.el
(dart-mode auto-mode-alist "\\.dart\\'") ;from ~/Source/nongnu/packages/dart-mode/dart-mode-autoloads.el
(dockerfile-mode auto-mode-alist "\\.dockerfile\\'") ;from ~/Source/nongnu/packages/dockerfile-mode/dockerfile-mode-autoloads.el
(drupal-mode auto-mode-alist "[^/]\\.\\(module\\|test\\|install\\|profile\\|tpl\\.php\\|theme\\|inc\\)\\'" php-mode) ;from ~/Source/nongnu/packages/drupal-mode/drupal-mode-autoloads.el
(drupal-mode auto-mode-alist "[^/]\\.info\\'" conf-windows-mode) ;from ~/Source/nongnu/packages/drupal-mode/drupal-mode-autoloads.el
(drupal-mode auto-mode-alist "[^/]\\.make\\'" drush-make-mode) ;from ~/Source/nongnu/packages/drupal-mode/drupal-mode-autoloads.el
(editorconfig auto-mode-alist "\\.editorconfig\\'" editorconfig-conf-mode) ;from ~/Source/nongnu/packages/editorconfig/editorconfig-autoloads.el
(elixir-mode auto-mode-alist "\\.elixir\\'") ;from ~/Source/nongnu/packages/elixir-mode/elixir-mode-autoloads.el
(elixir-mode auto-mode-alist "\\.ex\\'") ;from ~/Source/nongnu/packages/elixir-mode/elixir-mode-autoloads.el
(elixir-mode auto-mode-alist "\\.exs\\'") ;from ~/Source/nongnu/packages/elixir-mode/elixir-mode-autoloads.el
(elixir-mode auto-mode-alist "mix\\.lock") ;from ~/Source/nongnu/packages/elixir-mode/elixir-mode-autoloads.el
(ett auto-mode-alist "\\.ett\\'" ett-mode) ;from ~/Source/nongnu/packages/ett/ett-autoloads.el
(forth-mode auto-mode-alist "\\.\\(f\\|fs\\|fth\\|4th\\)\\'") ;from ~/Source/nongnu/packages/forth-mode/forth-mode-autoloads.el
(geiser-racket auto-mode-alist "\\.rkt\\'" scheme-mode) ;from ~/Source/nongnu/packages/geiser-racket/geiser-racket-autoloads.el
(gnu-apl-mode auto-mode-alist "\\.apl\\'") ;from ~/Source/nongnu/packages/gnu-apl-mode/gnu-apl-mode-autoloads.el
(gnu-apl-mode interpreter-mode-alist "apl") ;from ~/Source/nongnu/packages/gnu-apl-mode/gnu-apl-mode-autoloads.el
(go-mode auto-mode-alist "go\\.mod\\'" go-dot-mod-mode) ;from ~/Source/nongnu/packages/go-mode/go-mode-autoloads.el
(go-mode auto-mode-alist "go\\.work\\'" go-dot-work-mode) ;from ~/Source/nongnu/packages/go-mode/go-mode-autoloads.el
(graphql-mode auto-mode-alist "\\.graphql\\'") ;from ~/Source/nongnu/packages/graphql-mode/graphql-mode-autoloads.el
(graphql-mode auto-mode-alist "\\.gql\\'") ;from ~/Source/nongnu/packages/graphql-mode/graphql-mode-autoloads.el
(haml-mode auto-mode-alist "\\.haml\\'") ;from ~/Source/nongnu/packages/haml-mode/haml-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.hcr\\'" ghc-core-mode) ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.dump-simpl\\'" ghc-core-mode) ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.ghci\\'" ghci-script-mode) ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.chs\\'" haskell-c2hs-mode) ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.cabal\\'\\|/cabal\\.project\\|/\\.cabal/config\\'" haskell-cabal-mode) ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.[gh]s\\'") ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.hsig\\'") ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.l[gh]s\\'" haskell-literate-mode) ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode auto-mode-alist "\\.hsc\\'") ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode interpreter-mode-alist "runghc") ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(haskell-mode interpreter-mode-alist "runhaskell") ;from ~/Source/nongnu/packages/haskell-mode/haskell-mode-autoloads.el
(j-mode auto-mode-alist "\\.ij[rsp]$") ;from ~/Source/nongnu/packages/j-mode/j-mode-autoloads.el
(j-mode auto-mode-alist "\\.ijt$" j-lab-mode) ;from ~/Source/nongnu/packages/j-mode/j-mode-autoloads.el
(jade-mode auto-mode-alist "\\.jade\\'") ;from ~/Source/nongnu/packages/jade-mode/jade-mode-autoloads.el
(jade-mode auto-mode-alist "\\.pug\\'") ;from ~/Source/nongnu/packages/jade-mode/jade-mode-autoloads.el
(jade-mode auto-mode-alist "\\.styl\\'" stylus-mode) ;from ~/Source/nongnu/packages/jade-mode/jade-mode-autoloads.el
(jinja2-mode auto-mode-alist "\\.jinja2\\'") ;from ~/Source/nongnu/packages/jinja2-mode/jinja2-mode-autoloads.el
(jinja2-mode auto-mode-alist "\\.j2\\'") ;from ~/Source/nongnu/packages/jinja2-mode/jinja2-mode-autoloads.el
(julia-mode auto-mode-alist "\\.jl\\'") ;from ~/Source/nongnu/packages/julia-mode/julia-mode-autoloads.el
(lua-mode auto-mode-alist "\\.lua\\'") ;from ~/Source/nongnu/packages/lua-mode/lua-mode-autoloads.el
(lua-mode interpreter-mode-alist "lua") ;from ~/Source/nongnu/packages/lua-mode/lua-mode-autoloads.el
(markdown-mode auto-mode-alist "\\.\\(?:md\\|markdown\\|mkd\\|mdown\\|mkdn\\|mdwn\\)\\'") ;from ~/Source/nongnu/packages/markdown-mode/markdown-mode-autoloads.el
(nginx-mode auto-mode-alist "nginx\\.conf\\'") ;from ~/Source/nongnu/packages/nginx-mode/nginx-mode-autoloads.el
(nginx-mode auto-mode-alist "/nginx/.+\\.conf\\'") ;from ~/Source/nongnu/packages/nginx-mode/nginx-mode-autoloads.el
(nix-mode auto-mode-alist "^/nix/store/.+\\.drv\\'" nix-drv-mode) ;from ~/Source/nongnu/packages/nix-mode/nix-mode-autoloads.el
(nix-mode auto-mode-alist "\\flake.lock\\'" js-mode) ;from ~/Source/nongnu/packages/nix-mode/nix-mode-autoloads.el
(nix-mode auto-mode-alist "\\.nix\\'") ;from ~/Source/nongnu/packages/nix-mode/nix-mode-autoloads.el
(php-mode auto-mode-alist "/\\.php_cs\\(?:\\.dist\\)?\\'") ;from ~/Source/nongnu/packages/php-mode/lisp/php-mode-autoloads.el
(php-mode auto-mode-alist "\\.\\(?:php\\.inc\\|stub\\)\\'") ;from ~/Source/nongnu/packages/php-mode/lisp/php-mode-autoloads.el
(php-mode auto-mode-alist "\\.\\(?:php[s345]?\\|phtml\\)\\'" php-mode-maybe) ;from ~/Source/nongnu/packages/php-mode/lisp/php-mode-autoloads.el
(proof auto-mode-alist "\\.v\\'" coq-mode) ;from ~/Source/nongnu/packages/proof-general/generic/proof-autoloads.el
(racket-mode auto-mode-alist "\\.rkt\\'") ;from ~/Source/nongnu/packages/racket-mode/racket-mode-autoloads.el
(racket-mode auto-mode-alist "\\.rktd\\'") ;from ~/Source/nongnu/packages/racket-mode/racket-mode-autoloads.el
(racket-mode auto-mode-alist "\\.rktl\\'") ;from ~/Source/nongnu/packages/racket-mode/racket-mode-autoloads.el
(racket-mode interpreter-mode-alist "racket") ;from ~/Source/nongnu/packages/racket-mode/racket-mode-autoloads.el
(raku-mode interpreter-mode-alist "perl6\\|raku") ;from ~/Source/nongnu/packages/raku-mode/raku-mode-autoloads.el
(raku-mode auto-mode-alist "\\.p[lm]?6\\'") ;from ~/Source/nongnu/packages/raku-mode/raku-mode-autoloads.el
(raku-mode auto-mode-alist "\\.nqp\\'") ;from ~/Source/nongnu/packages/raku-mode/raku-mode-autoloads.el
(raku-mode auto-mode-alist "\\.raku\\(?:mod\\|test\\)?\\'") ;from ~/Source/nongnu/packages/raku-mode/raku-mode-autoloads.el
(rfc-mode auto-mode-alist "/rfc[0-9]+\\.txt\\'") ;from ~/Source/nongnu/packages/rfc-mode/rfc-mode-autoloads.el
(rust-mode auto-mode-alist "\\.rs\\'") ;from ~/Source/nongnu/packages/rust-mode/rust-mode-autoloads.el
(sass-mode auto-mode-alist "\\.sass\\'") ;from ~/Source/nongnu/packages/sass-mode/sass-mode-autoloads.el
(scad-mode auto-mode-alist "\\.scad\\'") ;from ~/Source/nongnu/packages/scad-mode/scad-mode-autoloads.el
(scala-mode auto-mode-alist "\\.\\(scala\\|sbt\\|worksheet\\.sc\\)\\'") ;from ~/Source/nongnu/packages/scala-mode/scala-mode-autoloads.el
(stylus-mode auto-mode-alist "\\.jade\\'" jade-mode) ;from ~/Source/nongnu/packages/stylus-mode/stylus-mode-autoloads.el
(stylus-mode auto-mode-alist "\\.pug\\'" jade-mode) ;from ~/Source/nongnu/packages/stylus-mode/stylus-mode-autoloads.el
(stylus-mode auto-mode-alist "\\.styl\\'") ;from ~/Source/nongnu/packages/stylus-mode/stylus-mode-autoloads.el
(subed auto-mode-alist "\\.ass\\'" subed-ass-mode) ;from ~/Source/nongnu/packages/subed/subed/subed-autoloads.el
(subed auto-mode-alist "\\.srt\\'" subed-srt-mode) ;from ~/Source/nongnu/packages/subed/subed/subed-autoloads.el
(subed auto-mode-alist "\\.vtt\\'" subed-vtt-mode) ;from ~/Source/nongnu/packages/subed/subed/subed-autoloads.el
(swift-mode auto-mode-alist "\\.swift\\(interface\\)?\\'") ;from ~/Source/nongnu/packages/swift-mode/swift-mode-autoloads.el
(systemd auto-mode-alist "\\.nspawn\\'" systemd-mode) ;from ~/Source/nongnu/packages/systemd/systemd-autoloads.el
(tuareg auto-mode-alist "\\.ml[ip]?\\'" tuareg-mode) ;from ~/Source/nongnu/packages/tuareg/tuareg-autoloads.el
(tuareg auto-mode-alist "\\.eliomi?\\'" tuareg-mode) ;from ~/Source/nongnu/packages/tuareg/tuareg-autoloads.el
(tuareg interpreter-mode-alist "ocamlrun" tuareg-mode) ;from ~/Source/nongnu/packages/tuareg/tuareg-autoloads.el
(tuareg interpreter-mode-alist "ocaml" tuareg-mode) ;from ~/Source/nongnu/packages/tuareg/tuareg-autoloads.el
(tuareg auto-mode-alist "\\.mly\\'" tuareg-menhir-mode) ;from ~/Source/nongnu/packages/tuareg/tuareg-autoloads.el
(tuareg auto-mode-alist "[./]opam_?\\'" tuareg-opam-mode) ;from ~/Source/nongnu/packages/tuareg/tuareg-autoloads.el
(typescript-mode auto-mode-alist "\\.ts\\'") ;from ~/Source/nongnu/packages/typescript-mode/typescript-mode-autoloads.el
(yaml-mode auto-mode-alist "\\.\\(e?ya?\\|ra\\)ml\\'") ;from ~/Source/nongnu/packages/yaml-mode/yaml-mode-autoloads.el
(yaml-mode magic-mode-alist "^%YAML\\s-+[0-9]+\\.[0-9]+\\(\\s-+#\\|\\s-*$\\)") ;from ~/Source/nongnu/packages/yaml-mode/yaml-mode-autoloads.el
(zig-mode auto-mode-alist "\\.\\(zig\\|zon\\)\\'") ;from ~/Source/nongnu/packages/zig-mode/zig-mode-autoloads.el
)
