(setq purify-flag nil)

(load "emacs-lisp/byte-run")
(load "emacs-lisp/backquote")
(load "subr")

(load "emacs-lisp/macroexp")
(load "emacs-lisp/pcase")
(load "emacs-lisp/gv")

(load "emacs-lisp/nadvice")
(load "emacs-lisp/inline")
(load "emacs-lisp/cl-lib")
(load "emacs-lisp/cl-seq")
(load "emacs-lisp/cl-macs")
(load "emacs-lisp/cl-preloaded")

(load "custom")
(load "cus-face")
(load "emacs-lisp/timer")
(load "faces")
(load "emacs-lisp/easy-mmode")
(load "subr")
(load "bindings")
(load "emacs-lisp/derived")
(load "abbrev")
(load "minibuffer")
(load "window")
(load "simple")

(load "emacs-lisp/subr-x")
(load "progmodes/prog-mode")
(load "emacs-lisp/regexp-opt")
(load "emacs-lisp/lisp-mode")
(load "emacs-lisp/lisp-mnt")
(load "emacs-lisp/radix-tree")
(load "emacs-lisp/autoload")

(load "files")
(load "help")
(load "emacs-lisp/cconv")
(load "isearch")
(load "emacs-lisp/easymenu")
(load "emacs-lisp/cl-extra")
(load "emacs-lisp/warnings")
(load "emacs-lisp/bytecomp")
(load "emacs-lisp/byte-opt")
(load "emacs-lisp/cl-generic")
(load "progmodes/elisp-mode")

(defvar command-line-args-left (cdr command-line-args))
(setq generated-autoload-file "ldefs-boot.el")

(load "emacs-lisp/debug")
(setq debug-on-error t)

(batch-update-autoloads)
