#!/bin/sh
# impl.sh.hqbuild
#
# $HopeName: MMsrc!tools:swbuild(trunk.1) $
# Copyright (C) 1996 Harlequin Group, all rights reserved
#
# Build script for SWIG autobuild system.
# The SWIG autobuild system expects to execute this file passing it
# an argument.
#
# We specify that the argument will be the platform code to make life
# easy for us

case $# in
 1) ;;
 *) echo 1>&2 'Wrong number of arguments to hqbuild.
Exactly one argument expected'; exit 1;;
esac

gnumake -r -f "$1.gmk"
