#!/bin/sh
# tool/check-shell-scripts -- check shell scripts in the MPS
#
# Copyright (c) 2023 Ravenbrook Limited. See end of file for license.
#
# This script finds shell scripts in the MPS tree and runs shellcheck
# on them to check for issues.
#
# It can be invoked from the command line of from Continuous
# Integration scripts.
#
# The script excludes .git because it contains default Git Hooks
# installed by git that trigger shellcheck.
#
# The script ignores tool/autoconf because those scripts are part of
# GNU autoconf and not under our control.

find . -path './.git' -prune -o \
     -path './tool/autoconf' -prune -o \
     -type f ! -name '*~' -print |
{
    code=0
    while read -r f; do
	if head -1 -- "$f" | grep -E -q -e '^#!/bin/(ba)?sh'; then
	    # --format=gcc allows use of this script with Emacs M-x compile
	    if ! shellcheck --format=gcc "$f"; then
		code=1
	    fi
	fi
    done
    exit "$code"
}

# A. REFERENCES
#
# [None]
#
#
# B. DOCUMENT HISTORY
#
# 2023-01-14 RB Created.
#
#
# C. COPYRIGHT AND LICENSE
#
# Copyright (C) 2023 Ravenbrook Limited <https://www.ravenbrook.com/>.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the
#    distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# $Id$
