#! /bin/sh
# Merge gnulib sources into Emacs sources.
# Typical usage:
#
#	admin/merge-gnulib

# Copyright 2012-2026 Free Software Foundation, Inc.

# This file is part of GNU Emacs.

# GNU Emacs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# GNU Emacs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.

# written by Paul Eggert

# It is unclear whether module list sorting depends on locale; play it safe.
export LC_ALL=C

GNULIB_URL=https://git.savannah.gnu.org/git/gnulib.git

GNULIB_MODULES='
  alignasof alloca-opt binary-io bool boot-time builtin-expect byteswap
  c-ctype c-strcase canonicalize-lgpl
  careadlinkat close-stream copy-file-range
  crypto/md5 crypto/md5-buffer
  crypto/sha1-buffer crypto/sha256-buffer crypto/sha512-buffer
  d-type diffseq double-slash-root dtoastr dtotimespec dup2
  environ execinfo faccessat
  fchmodat fcntl fcntl-h fdopendir file-has-acl
  filemode filename filevercmp flexmember fpieee
  free-posix fstatat fsusage fsync futimens
  getline getloadavg getopt-gnu getrandom gettime gettimeofday gitlog-to-changelog
  ieee754-h ignore-value intprops largefile libgmp lstat
  malloc-gnu manywarnings memmem-simple mempcpy memrchr memset_explicit
  minmax mkostemp mktime
  nanosleep nproc nstrftime-limited
  pathmax pipe2 pselect pthread_sigmask
  qcopy-acl readlink readlinkat realloc-posix regex
  sig2str sigdescr_np socklen stat-time std-gnu23
  stdc_bit_width stdc_count_ones stdc_trailing_zeros
  stdckdint-h stddef-h stdio-h stdio-windows
  stpcpy stringeq strnlen strtoimax symlink sys_stat-h sys_time-h
  tempname time-h time_r time_rz timegm timer-time timespec-add timespec-sub
  unlocked-io update-copyright utimensat
  vla warnings year2038
'

AVOIDED_MODULES='
  access btowc chmod close crypto/af_alg dup fchdir fstat gnulib-i18n
  iswblank iswctype iswdigit iswxdigit langinfo-h libgmp-mpq
  localcharset locale-h localename-unsafe-limited lock
  mbrtowc mbsinit memchr mkdir msvc-inval msvc-nothrow nl_langinfo
  openat-die opendir pthread-h raise
  save-cwd select setenv sigprocmask stat std-gnu11 stdarg-h strncpy
  threadlib tzset unsetenv utime utime-h
  wchar-h wcrtomb wctype wctype-h
'

GNULIB_TOOL_FLAGS='
  --conditional-dependencies --import --no-changelog --no-vc-files
  --gnu-make
  --makefile-name=gnulib.mk.in
'

# The source directory, with a trailing '/'.
# If empty, the source directory is the working directory.
src=$2
case $src in
  */ | '') ;;
  *) src=$src/ ;;
esac

# Gnulib's source directory.
gnulib_srcdir=${1-$src../gnulib}

case $gnulib_srcdir in
  -*) src=- ;;
esac
case $src in
  -*)
    printf '%s\n' >&2 "$0: usage: $0 [GNULIB_SRCDIR [SRCDIR]]

    SRCDIR is the Emacs source directory (default: working directory).
    GNULIB_SRCDIR is the Gnulib source directory (default: SRCDIR/../gnulib)."
    exit 1 ;;
esac

[ -x "$src"autogen.sh ] || {
  printf '%s\n' >&2 "$0: '${src:-.}' is not an Emacs source directory."
  exit 1
}

[ -d "$gnulib_srcdir" ] ||
git clone -- "$GNULIB_URL" "$gnulib_srcdir" ||
exit

[ -x "$gnulib_srcdir"/gnulib-tool ] || {
  printf '%s\n' >&2 "$0: '$gnulib_srcdir' is not a Gnulib source directory."
  exit 1
}

autogen() {
  if [ "$src" ]; then
    printf "$0: entering $src ..." &&
    (cd "$src" && ./autogen.sh) &&
    printf "$0: leaving $src ..."
  else
    ./autogen.sh
  fi
}

# gnulib-tool has problems with a bare checkout (Bug#32452#65).
# Also, we need gnulib.mk.in to get the old module list.
[ -e "$src"lib/gnulib.mk.in ] || autogen || exit

get_module_list() {
  sed -n 's/## begin gnulib module //p' "$src"lib/gnulib.mk.in
}
old_modules=$(get_module_list) || exit

avoided_flags=
for module in $AVOIDED_MODULES; do
  avoided_flags="$avoided_flags --avoid=$module"
done

# Clean the lib directory as well.
if [ -e "$src"lib/Makefile ]; then
   make -C "$src"lib maintainer-clean || exit
fi

"$gnulib_srcdir"/gnulib-tool --dir="$src" $GNULIB_TOOL_FLAGS \
	$avoided_flags $GNULIB_MODULES &&
rm -- "$src"lib/calendar-ethiopian.h \
      "$src"lib/calendar-persian.h \
      "$src"lib/calendar-thai.h \
      "$src"lib/calendars.h \
      "$src"lib/gl_openssl.h \
      "$src"lib/stdio-read.c "$src"lib/stdio-write.c \
      "$src"m4/fcntl-o.m4 \
      "$src"m4/gl-openssl.m4 \
      "$src"m4/gnulib-cache.m4 "$src"m4/gnulib-tool.m4 \
      "$src"m4/manywarnings-c++.m4 \
      "$src"m4/off64_t.m4 \
      "$src"m4/warn-on-use.m4 "$src"m4/wint_t.m4 &&
cp -- "$gnulib_srcdir"/build-aux/texinfo.tex "$src"doc/misc &&
cp -- "$gnulib_srcdir"/build-aux/config.guess \
      "$gnulib_srcdir"/build-aux/config.sub \
      "$gnulib_srcdir"/build-aux/install-sh \
      "$gnulib_srcdir"/build-aux/move-if-change \
   "$src"build-aux &&
cp -- "$gnulib_srcdir"/lib/af_alg.h \
      "$gnulib_srcdir"/lib/save-cwd.h \
   "$src"lib &&
cp -- "$gnulib_srcdir"/m4/codeset.m4 \
   "$src"m4 &&
autogen &&
new_modules=$(get_module_list) || exit

test "$old_modules" = "$new_modules" ||
  printf >&2 '%s\n' \
    "$0: warning: module list changed; fix ../nt/gnulib-cfg.mk ..." \
    "$0: warning: ... or notify emacs-devel for w32 adaption." \
    "$0: warning: For more, run 'git diff ${src}lib/gnulib.mk.in'."
