#!/usr/local/bin/perl -w
#
# Compile all the .c files in $testlib_dir,
# putting the resulting .o files in $obj_dir.
#

&options(
 "MPS_INCLUDE_DIR",
 "INTERFACE_VERSION",
 "PLATFORM"
);

require "require";

&clib;

