#!/usr/local/bin/perl -w
#
# Compile all the .c files in $testlib_dir,
# putting the resulting .o files in $obj_dir.
#

&options(
 "MPS_INCLUDE_DIR",
 "INTERFACE_VERSION",
 "PLATFORM"
);

require "dirs";

print "Compiling test libraries from $testlib_dir.\n";

require "compile";

open(MANIFEST, "$testlib_dir/manifest");

while ($tlfile = <MANIFEST>) {
 chop($tlfile);
 $tlfile = $testlib_dir."/".$tlfile;
 $tlobj = $tlfile;
 $tlobj =~ s/\.c/\.o/;
 $tlobj =~ s/$testlib_dir/$obj_dir/;
 print"$tlfile -> $tlobj";

 if (&compile($tlfile, $tlobj)) {
  print " ok\n";
 } else {
  print " failed\n";
 }
}

close(MANIFEST);

