#!/usr/local/bin/perl
#
# make an index of all the tests (all .c files) in the
# current directory, and write it on stdout.
#

&options();

print $platform_phylum."\n";

require "headread";

open(IF, ">tmp_index");

while ($testfile = <*.c>) {
 &readheader($testfile, 0);
 $testnum=$testfile;
 $testnum=~s/\.c//;
 $testname = $test_header{"summary"};
 unless ($testname) {
  print "unknown test: ".$testnum."\n";
 } else {
  print IF $testnum.": ".$testname."\n";
 }
}

close(IF);
if ($platform_phylum eq "unix") {
 $sort_options = "-n";
} elsif ($platform_phylum eq "pc") {
 $sort_options = "<"; # there's no numeric sort option, unfortunately
}

system("sort $sort_options tmp_index");
system("rm tmp_index");
 
