#!/usr/local/bin/perl
# $HopeName: MMQA_harness!script:commands:run(trunk.2) $
#
# run tests interactively (allows for user input, immediate results,
# &c, and give results in standard format, and mailing results)

&options(
 "MPS_INCLUDE_DIR",
 "MPS_LINK_OBJ",
 "INTERFACE_VERSION",
 "PLATFORM",
 "LOG_DIR"
);

require "require";

foreach $testfile (@qa_args) {
 &run_test($testfile, "yes", "results", "$LOG_DIR/last.log");
 &mailfile("$LOG_DIR/last.log", "MMQA-log: result of test $testfile");
}

