#!/usr/local/bin/perl -w
# $HopeName: MMQA_harness!script:commands:runset(trunk.3) $
#
# run a set of tests specified in a test-set file
#

&requiredoptions(
 "MPS_INCLUDE_DIR",
 "MPS_LINK_OBJ",
# "MPS_INTERFACE_VERSION",
 "MPS_PRODUCT",
 "PLATFORM",
 "LOG_DIR"
);

$testset = $ARGV[0];

&run_testset($testset, "$LOG_DIR/summ.log", "$LOG_DIR/res.log", "$LOG_DIR/full.log");

