#!/usr/local/bin/perl
#
# run tests interactively (allows for user input, immediate results,
# &c, but doesn't give results in standard format)

&options(
 "MPS_INCLUDE_DIR",
 "MPS_LINK_OBJ",
 "INTERFACE_VERSION",
 "PLATFORM"
);

require "require";

foreach $testfile (@qa_args) {
 &try_test($testfile);
}

