#!/usr/local/bin/perl
# $HopeName: MMQA_harness!script:commands:try(trunk.8) $
#
# run tests interactively (allows for user input, immediate results,
# &c, but doesn't give results in standard format)

&options();

require "require";

print "The try command has been removed. Please use the run command instead.\n";


