#!/usr/local/perl
# $HopeName: MMQA_harness!script:logging(trunk.4) $
#
# provide a subroutine to pretty-print tests to a
# output stream
#

1;

sub display_test_source {
 local ($file, $stream, $width) = @_;

 unless (open(IN, $file)) {
  die "File ".$infile." unexpectedly not found.\n";
 }

 $l = "";

 while (<IN>) {
  print $stream $_;
 }

 close(IN);
}

