#!/usr/local/perl
# $HopeName: MMQA_harness!script:options(trunk.14) $
#

# global options for qa commands
#
# this file also has the job of detecting what platform
# we're on
#

# first to see where we are:

if (($ENV{"OS"} || "") eq "Windows_NT") {
 # it's NT, so find out what the processor is
 #  from a system variable
 $platform_class = "nt_".$ENV{"PROCESSOR_ARCHITECTURE"};
 if ($platform_class eq "nt_") {
  $platform_class = "nt_dunno";
 }
 $platform_phylum = "pc";
} elsif (($ENV{"OSTYPE"} || "") eq "Linux") {
# it's Linux. We'll assume they're all the same!
 $platform_class = "linux";
 $platform_phylum = "unix";
} else {
 # it's unix by default
 $platform_class = `class`;
 chop($platform_class);
 $platform_phylum = "unix";
}

%qa_options = (
 "v", "INTERFACE_VERSION",
 "i", "MPS_INCLUDE_DIR",
 "l", "MPS_LINK_OBJ",
 "p", "PLATFORM",
 "data", "DATA_DIR",
 "g", "LOG_DIR"
);

%qa_flags = (
 "debug", "DEBUG_INFO"
);

%qa_defaults = (
 "PLATFORM", $platform_class."__".$platform_phylum,
 "DEBUG_INFO", "off",
 "DATA_DIR", "$test_dir/../data",
 "LOG_DIR", "$test_dir/log",
 "INTERFACE_VERSION", "BQ"
);

%qa_unlogged_opts = (DATA_DIR, 1, LOG_DIR, 1);

