#!/usr/local/perl
#

# global options for qa commands
#
# this file also has the job of detecting what platform
# we're on
#

# first to see where we are:

if ($ENV{"OS"} eq "Windows_NT") {
 # it's NT, so find out what the processor is
 #  from a system variable
 $platform_class = "nt_".$ENV{"PROCESSOR_ARCHITECTURE"};
 if ($platform_class eq "nt_") {
  $platform_class = "nt_dunno";
 }
 $platform_phylum = "pc";
} else {
 # it's unix by default
 $platform_class = `class`;
 chop($platform_class);
 $platform_phylum = "unix";
}

%qa_options = (
 "v", "INTERFACE_VERSION",
 "i", "MPS_INCLUDE_DIR",
 "l", "MPS_LINK_OBJ",
 "p", "PLATFORM"
);

%qa_flags = (
);

%qa_defaults = (
 "INTERFACE_VERSION", "MO",
 "PLATFORM", $platform_class
);

