;;; latin1-disp.el --- display tables for other ISO 8859 on Latin-1 terminals -*- coding: emacs-mule -*-

;; Copyright (C) 2000, 2001 Free Software Foundation, Inc.

;; Author: Dave Love <fx@gnu.org>
;; Keywords: i18n

;; This file is part of GNU Emacs.

;; GNU Emacs is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to the
;; Free Software Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.

;;; Commentary:

;; This package sets up display of ISO 8859-n for n>1 by substituting
;; Latin-1 characters and sequences of them for characters which can't
;; be displayed, either because we're on a tty or because we don't
;; have the relevant window system fonts available.  For instance,
;; Latin-9 is very similar to Latin-1, so we can display most Latin-9
;; characters using the Latin-1 characters at the same code point and
;; fall back on more-or-less mnemonic ASCII sequences for the rest.

;; For the Latin charsets the ASCII sequences are mostly consistent
;; with the Quail prefix input sequences.  Latin-4 uses the Quail
;; postfix sequences since a prefix method isn't defined for Latin-4.

;; [A different approach is taken in the DOS display tables in
;; term/internal.el, and the relevant ASCII sequences from there are
;; available as an alternative; see `latin1-display-mnemonic'.  Only
;; these sequences are used for Arabic, Cyrillic, Greek and Hebrew.]

;; If you don't even have Latin-1, see iso-ascii.el and use the
;; complete tables from internal.el.  The ASCII sequences used here
;; are mostly in the same style as iso-ascii.

;;; Code:

;; Ensure `standard-display-table' is set up:
(require 'disp-table)
(require 'ucs-tables)

(defconst latin1-display-sets '(latin-2 latin-3 latin-4 latin-5 latin-8
		                latin-9 arabic cyrillic greek hebrew)
  "The ISO8859 character sets with defined Latin-1 display sequences.
These are the nicknames for the sets and correspond to Emacs language
environments.")

(defgroup latin1-display ()
  "Set up display tables for ISO8859 characters using Latin-1."
  :version "21.1"
  :link '(emacs-commentary-link "latin1-disp")
  :group 'i18n)

(defcustom latin1-display-format "{%s}"
  "A format string used to display the ASCII sequences.
The default encloses the sequence in braces, but you could just use
\"%s\" to avoid the braces."
  :group 'latin1-display
  :type 'string)

;;;###autoload
(defcustom latin1-display nil
  "Set up Latin-1/ASCII display for ISO8859 character sets.
This is done for each character set in the list `latin1-display-sets',
if no font is available to display it.  Characters are displayed using
the corresponding Latin-1 characters where they match.  Otherwise
ASCII sequences are used, mostly following the Latin prefix input
methods.  Some different ASCII sequences are used if
`latin1-display-mnemonic' is non-nil.

This option also treats some characters in the `mule-unicode-...'
charsets if you don't have a Unicode font with which to display them.

Setting this variable directly does not take effect;
use either M-x customize of the function `latin1-display'."
  :group 'latin1-display
  :type 'boolean
  :require 'latin1-disp
  :initialize 'custom-initialize-default
  :set (lambda (symbol value)
	 (if value
	     (apply #'latin1-display latin1-display-sets)
	   (latin1-display))))

;;;###autoload
(defun latin1-display (&rest sets)
  "Set up Latin-1/ASCII display for the arguments character SETS.
See option `latin1-display' for the method.  The members of the list
must be in `latin1-display-sets'.  With no arguments, reset the
display for all of `latin1-display-sets'. See also
`latin1-display-setup'.  As well as iso-8859 characters, this treats
some characters in the `mule-unicode-...' charsets if you don't have
a Unicode font with which to display them."
  (if sets
      (progn
	(mapc #'latin1-display-setup sets)
	(unless (latin1-char-displayable-p
		 (make-char 'mule-unicode-0100-24ff 32 33))
	  ;; It doesn't look as though we have a Unicode font.
	  (map-char-table
	   (lambda (c uc)
	     (when (and (char-valid-p c)
			(char-valid-p uc)
			(not (aref standard-display-table uc)))
	       (aset standard-display-table uc
		     (or (aref standard-display-table c)
			 (vector c)))))
	   ucs-mule-8859-to-mule-unicode)
	  ;; Extra stuff for windows-1252, in particular.
	  (mapc
	   (lambda (l)
	     (apply 'latin1-display-char l))
	   '((?\œôòú ",") ;; SINGLE LOW-9 QUOTATION MARK
	     (?\œôòş ",,")	;; DOUBLE LOW-9 QUOTATION MARK
	     (?\œôó¦ "...") ;; HORIZONTAL ELLIPSIS
	     (?\œôó° "o/oo") ;; PER MILLE SIGN
	     (?\œôó¹ "<") ;; SINGLE LEFT-POINTING ANGLE QUOTATION MARK
	     (?\œôòü "``")	;; LEFT DOUBLE QUOTATION MARK
	     (?\œôòı "''")	;; RIGHT DOUBLE QUOTATION MARK
	     (?\œôòó "-") ;; EN DASH
	     (?\œôòô "--")	;; EM DASH
	     (?\œôõâ "TM")	;; TRADE MARK SIGN
	     (?\œôóº ">") ;; SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
	     )))
	  (setq latin1-display t))
    (mapc #'latin1-display-reset latin1-display-sets)
    (aset standard-display-table
	  (make-char 'mule-unicode-0100-24ff) nil)
    (aset standard-display-table
	  (make-char 'mule-unicode-2500-33ff) nil)
    (aset standard-display-table
	  (make-char 'mule-unicode-e000-ffff) nil)
    (setq latin1-display nil)
    (redraw-display)))

(defcustom latin1-display-mnemonic nil
  "Non-nil means to display potentially more mnemonic sequences.
These are taken from the tables in `internal.el' rather than the Quail
input sequences."
  :type 'boolean
  :group 'latin1-display)

(defun latin1-display-char (char display &optional alt-display)
  "Make an entry in `standard-display-table' for CHAR using string DISPLAY.
If ALT-DISPLAY is provided, use that instead if
`latin1-display-mnemonic' is non-nil.  The actual string displayed is
formatted using `latin1-display-format'.

DISPLAY and ALT-DISPLAY are either strings or vectors.  String values
are formatted using `latin1-display-format' and passed to
`standard-display-ascii'; vectors are put into `standard-display-table'
asis."
  (if (and (stringp alt-display)
	   latin1-display-mnemonic)
      (setq display alt-display))
  (if (stringp display)
      (standard-display-ascii char (format latin1-display-format display))
    (aset standard-display-table char display)))

(defun latin1-display-identities (charset)
  "Display each character in CHARSET as the corresponding Latin-1 character.
CHARSET is a symbol which is the nickname of a language environment
using an ISO8859 character set."
  (if (eq charset 'cyrillic)
      (setq charset 'cyrillic-iso))
  (let ((i 32)
	(set (car (remq 'ascii (get-language-info charset 'charset)))))
    (while (<= i 127)
      (aset standard-display-table
	    (make-char set i)
	    (vector (make-char 'latin-iso8859-1 i)))
      (setq i (1+ i)))))

(defun latin1-display-reset (language)
  "Set up the default display for each character of LANGUAGE's charset.
LANGUAGE is a symbol naming a language environment using an ISO8859
character set."
  (if (eq language 'cyrillic)
      (setq language 'cyrillic-iso))
  (let ((charset (if (eq language 'arabic)
		     'arabic-iso8859-6
		   (car (remq 'ascii (get-language-info language
							'charset))))))
    (standard-display-default (make-char charset 32)
			      (make-char charset 127)))
  (sit-for 0))

(defun latin1-display-check-font (language)
  "Return non-nil if we have a font with an encoding for LANGUAGE.
LANGUAGE is a symbol naming a language environment using an ISO8859
character set: `latin-2', `hebrew' etc."
  (if (eq language 'cyrillic)
      (setq language 'cyrillic-iso))
  (let* ((info (get-language-info language 'charset))
	 (char (and info (make-char (car (remq 'ascii info)) ?\ ))))
    (and char (latin1-char-displayable-p char))))

;; This should be moved into mule-utils or somewhere after 21.1.
(defun latin1-char-displayable-p (char)
  "Return non-nil if we should be able to display CHAR.
On a multi-font display, the test is only whether there is an
appropriate font from the selected frame's fontset to display CHAR's
charset in general.  Since fonts may be specified on a per-character
basis, this may not be accurate."
  (cond ((< char 256)
	 ;; Single byte characters are always displayable.
	 t)
	((display-multi-font-p)
	 ;; On a window system, a character is displayable if we have
	 ;; a font for that character in the default face of the
	 ;; currently selected frame.
	 (let ((fontset (frame-parameter (selected-frame) 'font))
	       font-pattern)
	   (if (query-fontset fontset)
	       (setq font-pattern (fontset-font fontset char)))
	   (or font-pattern
	       (setq font-pattern (fontset-font "fontset-default" char)))
	   (if font-pattern
	       (progn
		 ;; Now FONT-PATTERN is a string or a cons of family
		 ;; field pattern and registry field pattern.
		 (or (stringp font-pattern)
		     (setq font-pattern (concat "-"
						(or (car font-pattern) "*")
						"-*-"
						(cdr font-pattern))))
		 (x-list-fonts font-pattern 'default (selected-frame) 1)))))
	(t
	 (let ((coding (terminal-coding-system)))
	   (if coding
	       (let ((safe-chars (coding-system-get coding 'safe-chars))
		     (safe-charsets (coding-system-get coding 'safe-charsets)))
		 (or (and safe-chars
			  (aref safe-chars char))
		     (and safe-charsets
			  (memq (char-charset char) safe-charsets)))))))))

(defun latin1-display-setup (set &optional force)
  "Set up Latin-1 display for characters in the given SET.
SET must be a member of `latin1-display-sets'.  Normally, check
whether a font for SET is available and don't set the display if it
is.  If FORCE is non-nil, set up the display regardless."
  (cond
   ((eq set 'latin-2)
    (when (or force
	      (not (latin1-display-check-font set)))
      (latin1-display-identities set)
      (mapc
       (lambda (l)
	 (apply 'latin1-display-char l))
       '((?‚Æ "'C" "C'")
	 (?‚Ğ "'D" "/D")
	 (?‚¦ "'S" "S'")
	 (?‚æ "'c" "c'")
	 (?‚ğ "'d" "/d")
	 (?‚Å "'L" "L'")
	 (?‚ñ "'n" "n'")
	 (?‚Ñ "'N" "N'")
	 (?‚à "'r" "r'")
	 (?‚À "'R" "R'")
	 (?‚¶ "'s" "s'")
	 (?‚¼ "'z" "z'")
	 (?‚¬ "'Z" "Z'")
	 (?‚¡ "`A" "A;")
	 (?‚Ê "`E" "E;")
	 (?‚£ "`L" "/L")
	 (?‚ª "`S" ",S")
	 (?‚Ş "`T" ",T")
	 (?‚¯ "`Z" "Z^.")
	 (?‚± "`a" "a;")
	 (?‚³ "`l" "/l")
	 (?‚ê "`e" "e;")
	 (?‚º "`s" ",s")
	 (?‚ş "`t" ",t")
	 (?‚¿ "`z" "z^.")
	 (?‚ÿ "`." "'.")
	 (?‚Ã "~A" "A(")
	 (?‚È "~C" "C<")
	 (?‚Ï "~D" "D<")
	 (?‚Ì "~E" "E<")
	 (?‚ì "~e" "e<")
	 (?‚¥ "~L" "L<")
	 (?‚Ò "~N" "N<")
	 (?‚Õ "~O" "O''")
	 (?‚Ø "~R" "R<")
	 (?‚© "~S" "S<")
	 (?‚« "~T" "T<")
	 (?‚Û "~U" "U''")
	 (?‚® "~Z" "Z<")
	 (?‚ã "~a" "a(}")
	 (?‚è "~c" "c<")
	 (?‚ï "~d" "d<")
	 (?‚µ "~l" "l<")
	 (?‚ò "~n" "n<")
	 (?‚õ "~o" "o''")
	 (?‚ø "~r" "r<")
	 (?‚¹ "~s" "s<")
	 (?‚» "~t" "t<")
	 (?‚û "~u" "u''")
	 (?‚¾ "~z" "z<")
	 (?‚· "~v" "'<")			; ?‚¢ in latin-pre
	 (?‚¢ "~~" "'(")
	 (?‚ù "uu" "u^0")
	 (?‚Ù "UU" "U^0")
	 (?‚Ä "\"A")
	 (?‚ä "\"a")
	 (?‚Ë "\"E" "E:")
	 (?‚ë "\"e")
	 (?‚½ "''" "'")
	 (?‚· "'<")			; Lynx's rendering of caron
	 ))))

   ((eq set 'latin-3)
    (when (or force
	      (not (latin1-display-check-font set)))
      (latin1-display-identities set)
      (mapc
       (lambda (l)
	 (apply 'latin1-display-char l))
       '((?ƒ¡ "/H")
	 (?ƒ¢ "~`" "'(")
	 (?ƒ¦ "^H" "H^")
	 (?ƒ¶ "^h" "h^")
	 (?ƒ© ".I" "I^.")
	 (?ƒª ",S")
	 (?ƒ« "~G" "G(")
	 (?ƒ¬ "^J" "J^")
	 (?ƒ¯ ".Z" "Z^.")
	 (?ƒ± "/h")
	 (?ƒ¹ ".i" "i^.")
	 (?ƒº ",s")
	 (?ƒ» "~g" "g(")
	 (?ƒ¼ "^j" "j^")
	 (?ƒ¿ ".Z" "z^.")
	 (?ƒÅ ".c" "C^.")
	 (?ƒÆ "^C" "C^")
	 (?ƒÕ ".G" "G^.")
	 (?ƒØ "^G" "G^")
	 (?ƒİ "~U" "U(")
	 (?ƒŞ "^S" "S^")
	 (?ƒå ".C" "c^.")
	 (?ƒæ "^c" "c^")
	 (?ƒõ ".g" "g^.")
	 (?ƒø "^g" "g^")
	 (?ƒı "~u" "u(")
	 (?ƒş "^s" "s^")
	 (?ƒÿ "/." "^.")))))

   ((eq set 'latin-4)
    (when (or force
	      (not (latin1-display-check-font set)))
      (latin1-display-identities set)
      (mapc
       (lambda (l)
	 (apply 'latin1-display-char l))
       '((?„¡ "A," "A;")
	 (?„¢ "k/" "kk")
	 (?„£ "R," ",R")
	 (?„¥ "I~" "?I")
	 (?„¦ "L," ",L")
	 (?„© "S~" "S<")
	 (?„ª "E-")
	 (?„« "G," ",G")
	 (?„¬ "T/" "/T")
	 (?„® "Z~" "Z<")
	 (?„± "a," "a;")
	 (?„² "';")
	 (?„³ "r," ",r")
	 (?„µ "i~" "~i")
	 (?„¶ "l," ",l")
	 (?„· "'<")
	 (?„¹ "s~" "s<")
	 (?„º "e-")
	 (?„» "g," ",g")
	 (?„¼ "t/" "/t")
	 (?„½ "N/" "NG")
	 (?„¾ "z~" "z<")
	 (?„¿ "n/" "ng")
	 (?„À "A-")
	 (?„Ç "I," "I;")
	 (?„È "C~" "C<")
	 (?„Ê "E," "E;")
	 (?„Ì "E." "E^.")
	 (?„Ï "I-")
	 (?„Ñ "N," ",N")
	 (?„Ò "O-")
	 (?„Ó "K," ",K")
	 (?„Ù "U," "U;")
	 (?„İ "U~" "~U")
	 (?„Ş "U-")
	 (?„à "a-")
	 (?„ç "i," "i;")
	 (?„è "c~" "c<")
	 (?„ê "e," "e;")
	 (?„ì "e." "e^.")
	 (?„ï "i-")
	 (?„ğ "d/" "/d")
	 (?„ñ "n," ",n")
	 (?„ò "o-")
	 (?„ó "k," ",k")
	 (?„ù "u," "u;")
	 (?„ı "u~" "~u")
	 (?„ş "u-")
	 (?„ÿ "^.")))))

   ((eq set 'latin-5)
    (when (or force
	      (not (latin1-display-check-font set)))
      (latin1-display-identities set)
      (mapc
       (lambda (l)
	 (apply 'latin1-display-char l))
       '((?ğ "~g" "g(")
	 (?Ğ "~G" "G(")
	 (?İ ".I" "I^.")
	 (?ş ",s")
	 (?Ş ",S")
	 (?ê "^e" "e<")			; from latin-post
	 (?ì ".e" "e^.")
	 (?ï "\"i" "i-")		; from latin-post
	 (?ı ".i" "i.")))))

   ((eq set 'latin-8)
    (when (or force
	      (not (latin1-display-check-font set)))
      (latin1-display-identities set)
      (mapc
       (lambda (l)
	 (apply 'latin1-display-char l))
       '((?¡ ".B" "B`")
	 (?¢ ".b" "b`")
	 (?¥ ".c" "c`")
	 (?¤ ".C" "C`")
	 (?¦ ".D" "D`")
	 (?« ".d" "d`")
	 (?¸ "`w")
	 (?¨ "`W")
	 (?º "'w" "w'")
	 (?ª "'W" "W'")
	 (?¼ "`y")
	 (?¬ "`Y")
	 (?± ".f" "f`")
	 (?° ".F" "F`")
	 (?³ ".g" "g`")
	 (?² ".G" "G`")
	 (?µ ".m" "m`")
	 (?´ ".M" "M`")
	 (?¹ ".p" "p`")
	 (?· ".P" "P`")
	 (?¿ ".s" "s`")
	 (?» ".S" "S`")
	 (?¾ "\"w")
	 (?½ "\"W")
	 (?ğ "^w" "w^")
	 (?Ğ "^W" "W^")
	 (?÷ ".t" "t`")
	 (?× ".T" "T`")
	 (?ş "^y" "y^")
	 (?Ş "^Y" "Y^")
	 (?¯ "\"Y")))))

   ((eq set 'latin-9)
    (when (or force
	      (not (latin1-display-check-font set)))
      (latin1-display-identities set)
      (mapc
       (lambda (l)
	 (apply 'latin1-display-char l))
       '((?¨ "~s" "s<")
	 (?¦ "~S" "S<")
	 (?¤ "Euro" "E=")
	 (?¸ "~z" "z<")
	 (?´ "~Z" "Z<")
	 (?¾ "\"Y")
	 (?½ "oe")
	 (?¼ "OE")))))

   ((eq set 'greek)
    (when (or force
	      (not (latin1-display-check-font set)))
      (mapc
       (lambda (l)
	 (apply 'latin1-display-char l))
       '((?†¡ "9'")
	 (?†¢ "'9")
	 (?†¯ "-M")
	 (?†µ "'%")
	 (?†¶ "'A")
	 (?†¸ "'E")
	 (?†¹ "'H")
	 (?†º "'I")
	 (?†¼ "'O")
	 (?†¾ "'Y")
	 (?†¿ "W%")
	 (?†À "i3")
	 (?†Ã "G*")
	 (?†Ä "D*")
	 (?†È "TH")
	 (?†Ë "L*")
	 (?†Î "C*")
	 (?†Ğ "P*")
	 (?†Ó "S*")
	 (?†Ö "F*")
	 (?†Ø "Q*")
	 (?†Ù "W*")
	 (?†Ú "\"I")
	 (?†Û "\"Y")
	 (?†Ü "a%")
	 (?†İ "e%")
	 (?†Ş "y%")
	 (?†ß "i%")
	 (?†à "u3")
	 (?†á "a*")
	 (?†â "b*")
	 (?†ã "g*")
	 (?†ä "d*")
	 (?†å "e*")
	 (?†æ "z*")
	 (?†ç "y*")
	 (?†è "h*")
	 (?†é "i*")
	 (?†ê "k")
	 (?†ë "l*")
	 (?†ì "m*")
	 (?†í "n*")
	 (?†î "c*")
	 (?†ğ "p*")
	 (?†ñ "r*")
	 (?†ò "*s")
	 (?†ó "s*")
	 (?†ô "t*")
	 (?†õ "u")
	 (?†ö "f*")
	 (?†÷ "x*")
	 (?†ø "q*")
	 (?†ù "w*")
	 (?†ú "\"i")
	 (?†û "\"u")
	 (?†ü "'o")
	 (?†ı "'u")
	 (?†ş "'w")))
      (mapc
       (lambda (l)
	 (aset standard-display-table (car l) (string-to-vector (cadr l))))
       '((?†Á "A")
	 (?†Â "B")
	 (?†Å "E")
	 (?†Æ "Z")
	 (?†Ç "H")
	 (?†É "I")
	 (?†Ê "J")
	 (?†Ì "M")
	 (?†Í "N")
	 (?†Ï "O")
	 (?†Ñ "P")
	 (?†Ô "T")
	 (?†Õ "Y")
	 (?†× "X")
	 (?†ï "o")))))

   ((eq set 'hebrew)
    (when (or force
	      (not (latin1-display-check-font set)))
      ;; Don't start with identities, since we don't have definitions
      ;; for a lot of Hebrew in internal.el.  (Intlfonts is also
      ;; missing some glyphs.)
      (let ((i 34))
	(while (<= i 62)
	  (aset standard-display-table
		(make-char 'hebrew-iso8859-8 i)
		(vector (make-char 'latin-iso8859-1 i)))
	  (setq i (1+ i))))
      (mapc
       (lambda (l)
	 (aset standard-display-table (car l) (string-to-vector (cadr l))))
       '((?ˆß "=2")
	 (?ˆà "A+")
	 (?ˆá "B+")
	 (?ˆâ "G+")
	 (?ˆã "D+")
	 (?ˆä "H+")
	 (?ˆå "W+")
	 (?ˆæ "Z+")
	 (?ˆç "X+")
	 (?ˆè "Tj")
	 (?ˆé "J+")
	 (?ˆê "K%")
	 (?ˆë "K+")
	 (?ˆì "L+")
	 (?ˆí "M%")
	 (?ˆî "M+")
	 (?ˆï "N%")
	 (?ˆğ "N+")
	 (?ˆñ "S+")
	 (?ˆò "E+")
	 (?ˆó "P%")
	 (?ˆô "P+")
	 (?ˆõ "Zj")
	 (?ˆö "ZJ")
	 (?ˆ÷ "Q+")
	 (?ˆø "R+")
	 (?ˆù "Sh")
	 (?ˆú "T+")))))

   ;; Arabic probably isn't so useful in the absence of Arabic
   ;; language support...
   ((eq set 'arabic)
    (setq set 'arabic)
    (when (or force
	      (not (latin1-display-check-font set)))
      (aset standard-display-table ?‡  " ")
      (aset standard-display-table ?‡¤ "¤")
      (aset standard-display-table ?‡­ "­")
      (mapc (lambda (l)
	      (apply  'latin1-display-char l))
	    '((?‡¬ ",+")
	      (?‡» ";+")
	      (?‡¿ "?+")
	      (?‡Á "H'")
	      (?‡Â "aM")
	      (?‡Ã "aH")
	      (?‡Ä "wH")
	      (?‡Å "ah")
	      (?‡Æ "yH")
	      (?‡Ç "a+")
	      (?‡È "b+")
	      (?‡É "tm")
	      (?‡Ê "t+")
	      (?‡Ë "tk")
	      (?‡Ì "g+")
	      (?‡Í "hk")
	      (?‡Î "x+")
	      (?‡Ï "d+")
	      (?‡Ğ "dk")
	      (?‡Ñ "r+")
	      (?‡Ò "z+")
	      (?‡Ó "s+")
	      (?‡Ô "sn")
	      (?‡Õ "c+")
	      (?‡Ö "dd")
	      (?‡× "tj")
	      (?‡Ø "zH")
	      (?‡Ù "e+")
	      (?‡Ú "i+")
	      (?‡à "++")
	      (?‡á "f+")
	      (?‡â "q+")
	      (?‡ã "k+")
	      (?‡ä "l+")
	      (?‡å "m+")
	      (?‡æ "n+")
	      (?‡ç "h+")
	      (?‡è "w+")
	      (?‡é "j+")
	      (?‡ê "y+")
	      (?‡ë ":+")
	      (?‡ì "\"+")
	      (?‡í "=+")
	      (?‡î "/+")
	      (?‡ï "'+")
	      (?‡ğ "1+")
	      (?‡ñ "3+")
	      (?‡ò "0+")))))

   ((eq set 'cyrillic)
    (setq set 'cyrillic-iso)
    (when (or force
	      (not (latin1-display-check-font set)))
      (mapc
       (lambda (l)
	 (apply 'latin1-display-char l))
       '((?Œ¢ "Dj")
	 (?Œ£ "Gj")
	 (?Œ¤ "IE")
	 (?Œ© "Lj")
	 (?Œª "Nj")
	 (?Œ« "Ts")
	 (?Œ¬ "Kj")
	 (?Œ® "V%")
	 (?Œ¯ "Dzh")
	 (?Œ± "B=")
	 (?Œ³ "â")
	 (?Œ´ "D")
	 (?Œ¶ "Z%")
	 (?Œ· "3")
	 (?Œ¸ "U")
	 (?Œ¹ "J=")
	 (?Œ» "L=")
	 (?Œ¿ "P=")
	 (?ŒÃ "Y")
	 (?ŒÄ "è")
	 (?ŒÆ "C=")
	 (?ŒÇ "C%")
	 (?ŒÈ "S%")
	 (?ŒÉ "Sc")
	 (?ŒÊ "=\"")
	 (?ŒË "Y=")
	 (?ŒÌ "%\"")
	 (?ŒÍ "Ee")
	 (?ŒÎ "Yu")
	 (?ŒÏ "Ya")
	 (?ŒÑ "b")
	 (?ŒÒ "v=")
	 (?ŒÓ "g=")
	 (?ŒÔ "g")
	 (?ŒÖ "z%")
	 (?Œ× "z=")
	 (?ŒØ "u")
	 (?ŒÙ "j=")
	 (?ŒÚ "k")
	 (?ŒÛ "l=")
	 (?ŒÜ "m=")
	 (?Œİ "n=")
	 (?Œß "n")
	 (?Œà "p")
	 (?Œâ "t=")
	 (?Œä "f=")
	 (?Œæ "c=")
	 (?Œç "c%")
	 (?Œè "s%")
	 (?Œé "sc")
	 (?Œê "='")
	 (?Œë "y=")
	 (?Œì "%'")
	 (?Œí "ee")
	 (?Œî "yu")
	 (?Œï "ya")
	 (?Œğ "N0")
	 (?Œò "dj")
	 (?Œó "gj")
	 (?Œô "ie")
	 (?Œù "lj")
	 (?Œú "nj")
	 (?Œû "ts")
	 (?Œü "kj")
	 (?Œş "v%")
	 (?Œÿ "dzh")))
      (mapc
       (lambda (l)
	 (aset standard-display-table (car l) (string-to-vector (cadr l))))
       '((?Œ¡ "Ë")
	 (?Œ¥ "S")
	 (?Œ¦ "I")
	 (?Œ§ "Ï")
	 (?Œ¨ "J")
	 (?Œñ "ë")
	 (?Œı "§")
	 (?Œ­ "-")
	 (?Œ° "A")
	 (?Œ² "B")
	 (?Œµ "E")
	 (?Œº "K")
	 (?Œ¼ "M")
	 (?Œ½ "H")
	 (?Œ¾ "O")
	 (?ŒÀ "P")
	 (?ŒÁ "C")
	 (?ŒÂ "T")
	 (?ŒÅ "X")
	 (?ŒĞ "a")
	 (?ŒÕ "e")
	 (?ŒŞ "o")
	 (?Œá "c")
	 (?Œã "y")
	 (?Œå "x")
	 (?Œõ "s")
	 (?Œö "i")
	 (?Œ÷ "ï")
	 (?Œø "j")))))

   (t (error "Unsupported character set: %S" set)))
   
  (sit-for 0))

;;;###autoload
(defcustom latin1-display-ucs-per-lynx nil
  "Set up Latin-1/ASCII display for Unicode characters.
This uses the transliterations of the Lynx browser.  The display is't
changed if the display can render Unicode characters.

Setting this variable directly does not take effect;
use either M-x customize of the function `latin1-display'."
  :group 'latin1-display
  :type 'boolean
  :require 'latin1-disp
  :initialize 'custom-initialize-default
  :set (lambda (symbol value)
	 (if value
	     (latin1-display-ucs-per-lynx 1)
	   (latin1-display-ucs-per-lynx -1))))

(defun latin1-display-ucs-per-lynx (arg)
  "Set up Latin-1/ASCII display for Unicode characters.
This uses the transliterations of the Lynx browser.

With argument ARG, turn such display on iff ARG is positive, otherwise
turn it off and display Unicode characters literally.  The display
is't changed if the display can render Unicode characters."
  (interactive "p")
  (if (> arg 0)
      (unless nil;; (latin1-char-displayable-p
;; 	       (make-char 'mule-unicode-0100-24ff 32 33))
	;; It doesn't look as though we have a Unicode font.
	(let ((latin1-display-format "%s"))
	  (mapc
	   (lambda (l)
	     (apply 'latin1-display-char l))
	   ;; Table derived by running Lynx on a suitable list of
	   ;; characters in a utf-8 file.
	   '((?\œô   "A")
	     (?\œô ¡ "a")
	     (?\œô ¢ "A")
	     (?\œô £ "a")
	     (?\œô ¤ "A")
	     (?\œô ¥ "a")
	     (?\œô ¦ "C")
	     (?\œô § "c")
	     (?\œô ¨ "C")
	     (?\œô © "c")
	     (?\œô ª "C")
	     (?\œô « "c")
	     (?\œô ¬ "C")
	     (?\œô ­ "c")
	     (?\œô ® "D")
	     (?\œô ¯ "d")
	     (?\œô ° "Ğ")
	     (?\œô ± "d/")
	     (?\œô ² "E")
	     (?\œô ³ "e")
	     (?\œô ´ "E")
	     (?\œô µ "e")
	     (?\œô ¶ "E")
	     (?\œô · "e")
	     (?\œô ¸ "E")
	     (?\œô ¹ "e")
	     (?\œô º "E")
	     (?\œô » "e")
	     (?\œô ¼ "G")
	     (?\œô ½ "g")
	     (?\œô ¾ "G")
	     (?\œô ¿ "g")
	     (?\œô À "G")
	     (?\œô Á "g")
	     (?\œô Â "G")
	     (?\œô Ã "g")
	     (?\œô Ä "H")
	     (?\œô Å "h")
	     (?\œô Æ "H/")
	     (?\œô Ç "H")
	     (?\œô È "I")
	     (?\œô É "i")
	     (?\œô Ê "I")
	     (?\œô Ë "i")
	     (?\œô Ì "I")
	     (?\œô Í "i")
	     (?\œô Î "I")
	     (?\œô Ï "i")
	     (?\œô Ğ "I")
	     (?\œô Ñ "i")
	     (?\œô Ò "IJ")
	     (?\œô Ó "ij")
	     (?\œô Ô "J")
	     (?\œô Õ "j")
	     (?\œô Ö "K")
	     (?\œô × "k")
	     (?\œô Ø "kk")
	     (?\œô Ù "L")
	     (?\œô Ú "l")
	     (?\œô Û "L")
	     (?\œô Ü "l")
	     (?\œô İ "L")
	     (?\œô Ş "l")
	     (?\œô ß "L.")
	     (?\œô à "l.")
	     (?\œô á "L/")
	     (?\œô â "l/")
	     (?\œô ã "N")
	     (?\œô ä "n")
	     (?\œô å "N")
	     (?\œô æ "n")
	     (?\œô ç "N")
	     (?\œô è "n")
	     (?\œô é "'n")
	     (?\œô ê "NG")
	     (?\œô ë "N")
	     (?\œô ì "O")
	     (?\œô í "o")
	     (?\œô î "O")
	     (?\œô ï "o")
	     (?\œô ğ "O\"")
	     (?\œô ñ "o\"")
	     (?\œô ò "OE")
	     (?\œô ó "oe")
	     (?\œô ô "R")
	     (?\œô õ "r")
	     (?\œô ö "R")
	     (?\œô ÷ "r")
	     (?\œô ø "R")
	     (?\œô ù "r")
	     (?\œô ú "S")
	     (?\œô û "s")
	     (?\œô ü "S")
	     (?\œô ı "s")
	     (?\œô ş "S")
	     (?\œô ÿ "s")
	     (?\œô¡  "S")
	     (?\œô¡¡ "s")
	     (?\œô¡¢ "T")
	     (?\œô¡£ "t")
	     (?\œô¡¤ "T")
	     (?\œô¡¥ "t")
	     (?\œô¡¦ "T/")
	     (?\œô¡§ "t/")
	     (?\œô¡¨ "U")
	     (?\œô¡© "u")
	     (?\œô¡ª "U")
	     (?\œô¡« "u")
	     (?\œô¡¬ "U")
	     (?\œô¡­ "u")
	     (?\œô¡® "U")
	     (?\œô¡¯ "u")
	     (?\œô¡° "U\"")
	     (?\œô¡± "u\"")
	     (?\œô¡² "U")
	     (?\œô¡³ "u")
	     (?\œô¡´ "W")
	     (?\œô¡µ "w")
	     (?\œô¡¶ "Y")
	     (?\œô¡· "y")
	     (?\œô¡¸ "Y")
	     (?\œô¡¹ "Z")
	     (?\œô¡º "z")
	     (?\œô¡» "Z")
	     (?\œô¡¼ "z")
	     (?\œô¡½ "Z")
	     (?\œô¡¾ "z")
	     (?\œô¡¿ "s1")
	     (?\œô¡Ç "C2")
	     (?\œô¡È "c2")
	     (?\œô¡Ñ "F2")
	     (?\œô¡Ò " f")
	     (?\œô¡Ø "K2")
	     (?\œô¡Ù "k2")
	     (?\œô¡à "O9")
	     (?\œô¡á "o9")
	     (?\œô¡â "OI")
	     (?\œô¡ã "oi")
	     (?\œô¡æ "yr")
	     (?\œô¡ï "U9")
	     (?\œô¡ğ "u9")
	     (?\œô¡õ "Z/")
	     (?\œô¡ö "z/")
	     (?\œô¡÷ "ED")
	     (?\œô¢­ "A")
	     (?\œô¢® "a")
	     (?\œô¢¯ "I")
	     (?\œô¢° "i")
	     (?\œô¢± "O")
	     (?\œô¢² "o")
	     (?\œô¢³ "U")
	     (?\œô¢´ "u")
	     (?\œô¢µ "U:-")
	     (?\œô¢¶ "u:-")
	     (?\œô¢· "U:'")
	     (?\œô¢¸ "u:'")
	     (?\œô¢¹ "U:<")
	     (?\œô¢º "u:<")
	     (?\œô¢» "U:!")
	     (?\œô¢¼ "u:!")
	     (?\œô¢¾ "A1")
	     (?\œô¢¿ "a1")
	     (?\œô¢À "A7")
	     (?\œô¢Á "a7")
	     (?\œô¢Â "A3")
	     (?\œô¢Ã "a3")
	     (?\œô¢Ä "G/")
	     (?\œô¢Å "g/")
	     (?\œô¢Æ "G")
	     (?\œô¢Ç "g")
	     (?\œô¢È "K")
	     (?\œô¢É "k")
	     (?\œô¢Ê "O")
	     (?\œô¢Ë "o")
	     (?\œô¢Ì "O1")
	     (?\œô¢Í "o1")
	     (?\œô¢Î "EZ")
	     (?\œô¢Ï "ez")
	     (?\œô¢Ğ "j")
	     (?\œô¢Ô "G")
	     (?\œô¢Õ "g")
	     (?\œô¢Ú "AA'")
	     (?\œô¢Û "aa'")
	     (?\œô¢Ü "AE'")
	     (?\œô¢İ "ae'")
	     (?\œô¢Ş "O/'")
	     (?\œô¢ß "o/'")
	     (?\œô¢à "A!!")
	     (?\œô¢á "a!!")
	     (?\œô¢â "A)")
	     (?\œô¢ã "a)")
	     (?\œô¢ä "E!!")
	     (?\œô¢å "e!!")
	     (?\œô¢æ "E)")
	     (?\œô¢ç "e)")
	     (?\œô¢è "I!!")
	     (?\œô¢é "i!!")
	     (?\œô¢ê "I)")
	     (?\œô¢ë "i)")
	     (?\œô¢ì "O!!")
	     (?\œô¢í "o!!")
	     (?\œô¢î "O)")
	     (?\œô¢ï "o)")
	     (?\œô¢ğ "R!!")
	     (?\œô¢ñ "r!!")
	     (?\œô¢ò "R)")
	     (?\œô¢ó "r)")
	     (?\œô¢ô "U!!")
	     (?\œô¢õ "u!!")
	     (?\œô¢ö "U)")
	     (?\œô¢÷ "u)")
	     (?\œô¢ı "Z")
	     (?\œô£Ñ "A")
	     (?\œô£Ò "A.")
	     (?\œô£Ó "b`")
	     (?\œô£Ô "O")
	     (?\œô£Ö "d.")
	     (?\œô£× "d`")
	     (?\œô£Ø "@<umd>")
	     (?\œô£Ù "@")
	     (?\œô£Ú "R")
	     (?\œô£Û "E")
	     (?\œô£Ü "V\"")
	     (?\œô£İ "R<umd>")
	     (?\œô£Ş "O\"")
	     (?\œô£ß "J")
	     (?\œô£à "g`")
	     (?\œô£á "g")
	     (?\œô£â "G")
	     (?\œô£ã "Q")
	     (?\œô£ä "o-")
	     (?\œô£å "j<rnd>")
	     (?\œô£æ "h<?>")
	     (?\œô£è "i\"")
	     (?\œô£é "I")
	     (?\œô£ê "I")
	     (?\œô£ë "L")
	     (?\œô£ì "L")
	     (?\œô£í "l.")
	     (?\œô£î "z<lat>")
	     (?\œô£ï "u-")
	     (?\œô£ğ "j<vel>")
	     (?\œô£ñ "M")
	     (?\œô£ó "n.")
	     (?\œô£ô "n\"")
	     (?\œô£õ "@.")
	     (?\œô£ö "&.")
	     (?\œô£÷ "U")
	     (?\œô£ù "r")
	     (?\œô£ú "*<lat>")
	     (?\œô£û "r.")
	     (?\œô£ı "*.")
	     (?\œô£ş "*")
	     (?\œô¤  "R")
	     (?\œô¤¡ "g\"")
	     (?\œô¤¢ "s.")
	     (?\œô¤£ "S")
	     (?\œô¤¤ "J`")
	     (?\œô¤§ "t!")
	     (?\œô¤¨ "t.")
	     (?\œô¤© "u\"")
	     (?\œô¤ª "U")
	     (?\œô¤« "r<lbd>")
	     (?\œô¤¬ "V")
	     (?\œô¤­ "w<vls>")
	     (?\œô¤® "l^")
	     (?\œô¤¯ "I.")
	     (?\œô¤° "z.")
	     (?\œô¤² "Z")
	     (?\œô¤´ "?")
	     (?\œô¤µ "H<vcd>")
	     (?\œô¤¶ "l!")
	     (?\œô¤· "c!")
	     (?\œô¤¸ "p!")
	     (?\œô¤¹ "b<trl>")
	     (?\œô¤» "G`")
	     (?\œô¤½ "j")
	     (?\œô¤¾ "k!")
	     (?\œô¤¿ "L")
	     (?\œô¤À "q`")
	     (?\œô¤Ä "d3")
	     (?\œô¤Æ "ts")
	     (?\œô¤Ç "tS")
	     (?\œô¤Ğ "<h>")
	     (?\œô¤Ñ "<?>")
	     (?\œô¤Ò ";")
	     (?\œô¤Ó "<r>")
	     (?\œô¤× "<w>")
	     (?\œô¤Û ";S")
	     (?\œô¤Ü "`")
	     (?\œô¤æ "^")
	     (?\œô¤ç "'<")
	     (?\œô¤è "|")
	     (?\œô¤é "1-")
	     (?\œô¤ë "1!")
	     (?\œô¤ğ ":")
	     (?\œô¤ñ ":\\")
	     (?\œô¤ö "+")
	     (?\œô¤÷ "-")
	     (?\œô¤ø "'(")
	     (?\œô¤ù "'.")
	     (?\œô¤ú "'0")
	     (?\œô¤û "';")
	     (?\œô¤ü "~")
	     (?\œô¤ı "'\"")
	     (?\œô¥¥ "_T")
	     (?\œô¥¦ "_H")
	     (?\œô¥§ "_M")
	     (?\œô¥¨ "_L")
	     (?\œô¥© "_B")
	     (?\œô¥¬ "_v")
	     (?\œô¥® "''")
	     (?\œô¥À "`")
	     (?\œô¥Á "'")
	     (?\œô¥Â "^")
	     (?\œô¥Ã "~")
	     (?\œô¥Ä "¯")
	     (?\œô¥Ç "·")
	     (?\œô¥È "¨")
	     (?\œô¥Ê "°")
	     (?\œô¥Ë "''")
	     (?\œô¥Í "|")
	     (?\œô¥Î "||")
	     (?\œô¥Ï "``")
	     (?\œô¥á ";")
	     (?\œô¥â ".")
	     (?\œô¥ã ".")
	     (?\œô¥ä "<?>")
	     (?\œô¥å "<o>")
	     (?\œô¥æ ",")
	     (?\œô¥ç "¸")
	     (?\œô¥é "-")
	     (?\œô¥ê "[")
	     (?\œô¥ë "<w>")
	     (?\œô¥ô "~")
	     (?\œô¥÷ "/")
	     (?\œô¥ø "/")
	     (?\œô¦  "`")
	     (?\œô¦¡ "'")
	     (?\œô¦¢ "~")
	     (?\œô¦¤ "'%")
	     (?\œô¦¥ "j3")
	     (?\œô¦§ "=")
	     (?\œô¦À "~~")
	     (?\œô¦Ô "'")
	     (?\œô¦Õ ",")
	     (?\œô¦Ú "j3")
	     (?\œô¦Ş "?%")
	     (?\œô¦ä "'*")
	     (?\œô¦å "'%")
	     (?\œô¦æ "A'")
	     (?\œô¦ç "·")
	     (?\œô¦è "E'")
	     (?\œô¦é "Y%")
	     (?\œô¦ê "I'")
	     (?\œô¦ì "O'")
	     (?\œô¦î "U%")
	     (?\œô¦ï "W%")
	     (?\œô¦ğ "i3")
	     (?\œô¦ñ "A")
	     (?\œô¦ò "B")
	     (?\œô¦ó "G")
	     (?\œô¦ô "D")
	     (?\œô¦õ "E")
	     (?\œô¦ö "Z")
	     (?\œô¦÷ "Y")
	     (?\œô¦ø "TH")
	     (?\œô¦ù "I")
	     (?\œô¦ú "K")
	     (?\œô¦û "L")
	     (?\œô¦ü "M")
	     (?\œô¦ı "N")
	     (?\œô¦ş "C")
	     (?\œô¦ÿ "O")
	     (?\œô§  "P")
	     (?\œô§¡ "R")
	     (?\œô§£ "S")
	     (?\œô§¤ "T")
	     (?\œô§¥ "U")
	     (?\œô§¦ "F")
	     (?\œô§§ "X")
	     (?\œô§¨ "Q")
	     (?\œô§© "W*")
	     (?\œô§ª "J")
	     (?\œô§« "V*")
	     (?\œô§¬ "a'")
	     (?\œô§­ "e'")
	     (?\œô§® "y%")
	     (?\œô§¯ "i'")
	     (?\œô§° "u3")
	     (?\œô§± "a")
	     (?\œô§² "b")
	     (?\œô§³ "g")
	     (?\œô§´ "d")
	     (?\œô§µ "e")
	     (?\œô§¶ "z")
	     (?\œô§· "y")
	     (?\œô§¸ "th")
	     (?\œô§¹ "i")
	     (?\œô§º "k")
	     (?\œô§» "l")
	     (?\œô§¼ "µ")
	     (?\œô§½ "n")
	     (?\œô§¾ "c")
	     (?\œô§¿ "o")
	     (?\œô§À "p")
	     (?\œô§Á "r")
	     (?\œô§Â "*s")
	     (?\œô§Ã "s")
	     (?\œô§Ä "t")
	     (?\œô§Å "u")
	     (?\œô§Æ "f")
	     (?\œô§Ç "x")
	     (?\œô§È "q")
	     (?\œô§É "w")
	     (?\œô§Ê "j")
	     (?\œô§Ë "v*")
	     (?\œô§Ì "o'")
	     (?\œô§Í "u%")
	     (?\œô§Î "w%")
	     (?\œô§Ğ "beta ")
	     (?\œô§Ñ "theta ")
	     (?\œô§Ò "upsi ")
	     (?\œô§Õ "phi ")
	     (?\œô§Ö "pi ")
	     (?\œô§× "k.")
	     (?\œô§Ú "T3")
	     (?\œô§Û "t3")
	     (?\œô§Ü "M3")
	     (?\œô§İ "m3")
	     (?\œô§Ş "K3")
	     (?\œô§ß "k3")
	     (?\œô§à "P3")
	     (?\œô§á "p3")
	     (?\œô§ğ "kappa ")
	     (?\œô§ñ "rho ")
	     (?\œô§ó "J")
	     (?\œô§ô "'%")
	     (?\œô§õ "j3")
	     (?\œô¨¡ "IO")
	     (?\œô¨¢ "D%")
	     (?\œô¨£ "G%")
	     (?\œô¨¤ "IE")
	     (?\œô¨¥ "DS")
	     (?\œô¨¦ "II")
	     (?\œô¨§ "YI")
	     (?\œô¨¨ "J%")
	     (?\œô¨© "LJ")
	     (?\œô¨ª "NJ")
	     (?\œô¨« "Ts")
	     (?\œô¨¬ "KJ")
	     (?\œô¨® "V%")
	     (?\œô¨¯ "DZ")
	     (?\œô¨° "A")
	     (?\œô¨± "B")
	     (?\œô¨² "V")
	     (?\œô¨³ "G")
	     (?\œô¨´ "D")
	     (?\œô¨µ "E")
	     (?\œô¨¶ "ZH")
	     (?\œô¨· "Z")
	     (?\œô¨¸ "I")
	     (?\œô¨¹ "J")
	     (?\œô¨º "K")
	     (?\œô¨» "L")
	     (?\œô¨¼ "M")
	     (?\œô¨½ "N")
	     (?\œô¨¾ "O")
	     (?\œô¨¿ "P")
	     (?\œô¨À "R")
	     (?\œô¨Á "S")
	     (?\œô¨Â "T")
	     (?\œô¨Ã "U")
	     (?\œô¨Ä "F")
	     (?\œô¨Å "H")
	     (?\œô¨Æ "C")
	     (?\œô¨Ç "CH")
	     (?\œô¨È "SH")
	     (?\œô¨É "SCH")
	     (?\œô¨Ê "\"")
	     (?\œô¨Ë "Y")
	     (?\œô¨Ì "'")
	     (?\œô¨Í "`E")
	     (?\œô¨Î "YU")
	     (?\œô¨Ï "YA")
	     (?\œô¨Ğ "a")
	     (?\œô¨Ñ "b")
	     (?\œô¨Ò "v")
	     (?\œô¨Ó "g")
	     (?\œô¨Ô "d")
	     (?\œô¨Õ "e")
	     (?\œô¨Ö "zh")
	     (?\œô¨× "z")
	     (?\œô¨Ø "i")
	     (?\œô¨Ù "j")
	     (?\œô¨Ú "k")
	     (?\œô¨Û "l")
	     (?\œô¨Ü "m")
	     (?\œô¨İ "n")
	     (?\œô¨Ş "o")
	     (?\œô¨ß "p")
	     (?\œô¨à "r")
	     (?\œô¨á "s")
	     (?\œô¨â "t")
	     (?\œô¨ã "u")
	     (?\œô¨ä "f")
	     (?\œô¨å "h")
	     (?\œô¨æ "c")
	     (?\œô¨ç "ch")
	     (?\œô¨è "sh")
	     (?\œô¨é "sch")
	     (?\œô¨ê "\"")
	     (?\œô¨ë "y")
	     (?\œô¨ì "'")
	     (?\œô¨í "`e")
	     (?\œô¨î "yu")
	     (?\œô¨ï "ya")
	     (?\œô¨ñ "io")
	     (?\œô¨ò "d%")
	     (?\œô¨ó "g%")
	     (?\œô¨ô "ie")
	     (?\œô¨õ "ds")
	     (?\œô¨ö "ii")
	     (?\œô¨÷ "yi")
	     (?\œô¨ø "j%")
	     (?\œô¨ù "lj")
	     (?\œô¨ú "nj")
	     (?\œô¨û "ts")
	     (?\œô¨ü "kj")
	     (?\œô¨ş "v%")
	     (?\œô¨ÿ "dz")
	     (?\œô©¢ "Y3")
	     (?\œô©£ "y3")
	     (?\œô©ª "O3")
	     (?\œô©« "o3")
	     (?\œô©² "F3")
	     (?\œô©³ "f3")
	     (?\œô©´ "V3")
	     (?\œô©µ "v3")
	     (?\œô©À "C3")
	     (?\œô©Á "c3")
	     (?\œô©Ğ "G3")
	     (?\œô©Ñ "g3")
	     (?\œôª´ "AE")
	     (?\œôªµ "ae")
	     (?\œô¬Ô "i")
	     (?\œô¬× "a")
	     (?\œô¬Ø "o")
	     (?\œô¬Ü "u")
	     (?\œô¬ß "h")
	     (?\œô¬â ":")
	     (?\œô¬ğ "#")
	     (?\œô¬ñ "B+")
	     (?\œô¬ò "G+")
	     (?\œô¬ó "D+")
	     (?\œô¬ô "H+")
	     (?\œô¬õ "W+")
	     (?\œô¬ö "Z+")
	     (?\œô¬÷ "X+")
	     (?\œô¬ø "Tj")
	     (?\œô¬ù "J+")
	     (?\œô¬ú "K%")
	     (?\œô¬û "K+")
	     (?\œô¬ü "L+")
	     (?\œô¬ı "M%")
	     (?\œô¬ş "M+")
	     (?\œô¬ÿ "N%")
	     (?\œô­  "N+")
	     (?\œô­¡ "S+")
	     (?\œô­¢ "E+")
	     (?\œô­£ "P%")
	     (?\œô­¤ "P+")
	     (?\œô­¥ "Zj")
	     (?\œô­¦ "ZJ")
	     (?\œô­§ "Q+")
	     (?\œô­¨ "R+")
	     (?\œô­© "Sh")
	     (?\œô­ª "T+")
	     (?\œô­° "v")
	     (?\œô­± "oy")
	     (?\œô­² "ey")
	     (?\œô­Ì ",+")
	     (?\œô­Û ";+")
	     (?\œô­ß "?+")
	     (?\œô­á "H'")
	     (?\œô­â "aM")
	     (?\œô­ã "aH")
	     (?\œô­ä "wH")
	     (?\œô­å "ah")
	     (?\œô­æ "yH")
	     (?\œô­ç "a+")
	     (?\œô­è "b+")
	     (?\œô­é "tm")
	     (?\œô­ê "t+")
	     (?\œô­ë "tk")
	     (?\œô­ì "g+")
	     (?\œô­í "hk")
	     (?\œô­î "x+")
	     (?\œô­ï "d+")
	     (?\œô­ğ "dk")
	     (?\œô­ñ "r+")
	     (?\œô­ò "z+")
	     (?\œô­ó "s+")
	     (?\œô­ô "sn")
	     (?\œô­õ "c+")
	     (?\œô­ö "dd")
	     (?\œô­÷ "tj")
	     (?\œô­ø "zH")
	     (?\œô­ù "e+")
	     (?\œô­ú "i+")
	     (?\œô®  "++")
	     (?\œô®¡ "f+")
	     (?\œô®¢ "q+")
	     (?\œô®£ "k+")
	     (?\œô®¤ "l+")
	     (?\œô®¥ "m+")
	     (?\œô®¦ "n+")
	     (?\œô®§ "h+")
	     (?\œô®¨ "w+")
	     (?\œô®© "j+")
	     (?\œô®ª "y+")
	     (?\œô®« ":+")
	     (?\œô®¬ "\"+")
	     (?\œô®­ "=+")
	     (?\œô®® "/+")
	     (?\œô®¯ "'+")
	     (?\œô®° "1+")
	     (?\œô®± "3+")
	     (?\œô®² "0+")
	     (?\œô®À "0a")
	     (?\œô®Á "1a")
	     (?\œô®Â "2a")
	     (?\œô®Ã "3a")
	     (?\œô®Ä "4a")
	     (?\œô®Å "5a")
	     (?\œô®Æ "6a")
	     (?\œô®Ç "7a")
	     (?\œô®È "8a")
	     (?\œô®É "9a")
	     (?\œô®Ğ "aS")
	     (?\œô®Ş "p+")
	     (?\œô®á "hH")
	     (?\œô®æ "tc")
	     (?\œô®ø "zj")
	     (?\œô¯¤ "v+")
	     (?\œô¯¯ "gf")
	     (?\œô¯ğ "0a")
	     (?\œô¯ñ "1a")
	     (?\œô¯ò "2a")
	     (?\œô¯ó "3a")
	     (?\œô¯ô "4a")
	     (?\œô¯õ "5a")
	     (?\œô¯ö "6a")
	     (?\œô¯÷ "7a")
	     (?\œô¯ø "8a")
	     (?\œô¯ù "9a")
	     (?\œôÍÀ "he")
	     (?\œôÍÁ "hu")
	     (?\œôÍÂ "hi")
	     (?\œôÍÃ "ha")
	     (?\œôÍÄ "hE")
	     (?\œôÍÅ "h")
	     (?\œôÍÆ "ho")
	     (?\œôÍÈ "le")
	     (?\œôÍÉ "lu")
	     (?\œôÍÊ "li")
	     (?\œôÍË "la")
	     (?\œôÍÌ "lE")
	     (?\œôÍÍ "l")
	     (?\œôÍÎ "lo")
	     (?\œôÍÏ "lWa")
	     (?\œôÍĞ "He")
	     (?\œôÍÑ "Hu")
	     (?\œôÍÒ "Hi")
	     (?\œôÍÓ "Ha")
	     (?\œôÍÔ "HE")
	     (?\œôÍÕ "H")
	     (?\œôÍÖ "Ho")
	     (?\œôÍ× "HWa")
	     (?\œôÍØ "me")
	     (?\œôÍÙ "mu")
	     (?\œôÍÚ "mi")
	     (?\œôÍÛ "ma")
	     (?\œôÍÜ "mE")
	     (?\œôÍİ "m")
	     (?\œôÍŞ "mo")
	     (?\œôÍß "mWa")
	     (?\œôÍà "`se")
	     (?\œôÍá "`su")
	     (?\œôÍâ "`si")
	     (?\œôÍã "`sa")
	     (?\œôÍä "`sE")
	     (?\œôÍå "`s")
	     (?\œôÍæ "`so")
	     (?\œôÍç "`sWa")
	     (?\œôÍè "re")
	     (?\œôÍé "ru")
	     (?\œôÍê "ri")
	     (?\œôÍë "ra")
	     (?\œôÍì "rE")
	     (?\œôÍí "r")
	     (?\œôÍî "ro")
	     (?\œôÍï "rWa")
	     (?\œôÍğ "se")
	     (?\œôÍñ "su")
	     (?\œôÍò "si")
	     (?\œôÍó "sa")
	     (?\œôÍô "sE")
	     (?\œôÍõ "s")
	     (?\œôÍö "so")
	     (?\œôÍ÷ "sWa")
	     (?\œôÍø "xe")
	     (?\œôÍù "xu")
	     (?\œôÍú "xi")
	     (?\œôÍû "xa")
	     (?\œôÍü "xE")
	     (?\œôÍı "xa")
	     (?\œôÍş "xo")
	     (?\œôÍÿ "xWa")
	     (?\œôÎ  "qe")
	     (?\œôÎ¡ "qu")
	     (?\œôÎ¢ "qi")
	     (?\œôÎ£ "qa")
	     (?\œôÎ¤ "qE")
	     (?\œôÎ¥ "q")
	     (?\œôÎ¦ "qo")
	     (?\œôÎ¨ "qWe")
	     (?\œôÎª "qWi")
	     (?\œôÎ« "qWa")
	     (?\œôÎ¬ "qWE")
	     (?\œôÎ­ "qW")
	     (?\œôÎ° "Qe")
	     (?\œôÎ± "Qu")
	     (?\œôÎ² "Qi")
	     (?\œôÎ³ "Qa")
	     (?\œôÎ´ "QE")
	     (?\œôÎµ "Q")
	     (?\œôÎ¶ "Qo")
	     (?\œôÎ¸ "QWe")
	     (?\œôÎº "QWi")
	     (?\œôÎ» "QWa")
	     (?\œôÎ¼ "QWE")
	     (?\œôÎ½ "QW")
	     (?\œôÎÀ "be")
	     (?\œôÎÁ "bu")
	     (?\œôÎÂ "bi")
	     (?\œôÎÃ "ba")
	     (?\œôÎÄ "bE")
	     (?\œôÎÅ "b")
	     (?\œôÎÆ "bo")
	     (?\œôÎÇ "bWa")
	     (?\œôÎÈ "ve")
	     (?\œôÎÉ "vu")
	     (?\œôÎÊ "vi")
	     (?\œôÎË "va")
	     (?\œôÎÌ "vE")
	     (?\œôÎÍ "v")
	     (?\œôÎÎ "vo")
	     (?\œôÎÏ "vWa")
	     (?\œôÎĞ "te")
	     (?\œôÎÑ "tu")
	     (?\œôÎÒ "ti")
	     (?\œôÎÓ "ta")
	     (?\œôÎÔ "tE")
	     (?\œôÎÕ "t")
	     (?\œôÎÖ "to")
	     (?\œôÎ× "tWa")
	     (?\œôÎØ "ce")
	     (?\œôÎÙ "cu")
	     (?\œôÎÚ "ci")
	     (?\œôÎÛ "ca")
	     (?\œôÎÜ "cE")
	     (?\œôÎİ "c")
	     (?\œôÎŞ "co")
	     (?\œôÎß "cWa")
	     (?\œôÎà "`he")
	     (?\œôÎá "`hu")
	     (?\œôÎâ "`hi")
	     (?\œôÎã "`ha")
	     (?\œôÎä "`hE")
	     (?\œôÎå "`h")
	     (?\œôÎæ "`ho")
	     (?\œôÎè "hWe")
	     (?\œôÎê "hWi")
	     (?\œôÎë "hWa")
	     (?\œôÎì "hWE")
	     (?\œôÎí "hW")
	     (?\œôÎğ "na")
	     (?\œôÎñ "nu")
	     (?\œôÎò "ni")
	     (?\œôÎó "na")
	     (?\œôÎô "nE")
	     (?\œôÎõ "n")
	     (?\œôÎö "no")
	     (?\œôÎ÷ "nWa")
	     (?\œôÎø "Ne")
	     (?\œôÎù "Nu")
	     (?\œôÎú "Ni")
	     (?\œôÎû "Na")
	     (?\œôÎü "NE")
	     (?\œôÎı "N")
	     (?\œôÎş "No")
	     (?\œôÎÿ "NWa")
	     (?\œôÏ  "e")
	     (?\œôÏ¡ "u")
	     (?\œôÏ¢ "i")
	     (?\œôÏ£ "a")
	     (?\œôÏ¤ "E")
	     (?\œôÏ¥ "I")
	     (?\œôÏ¦ "o")
	     (?\œôÏ§ "e3")
	     (?\œôÏ¨ "ke")
	     (?\œôÏ© "ku")
	     (?\œôÏª "ki")
	     (?\œôÏ« "ka")
	     (?\œôÏ¬ "kE")
	     (?\œôÏ­ "k")
	     (?\œôÏ® "ko")
	     (?\œôÏ° "kWe")
	     (?\œôÏ² "kWi")
	     (?\œôÏ³ "kWa")
	     (?\œôÏ´ "kWE")
	     (?\œôÏµ "kW")
	     (?\œôÏ¸ "Ke")
	     (?\œôÏ¹ "Ku")
	     (?\œôÏº "Ki")
	     (?\œôÏ» "Ka")
	     (?\œôÏ¼ "KE")
	     (?\œôÏ½ "K")
	     (?\œôÏ¾ "Ko")
	     (?\œôÏÀ "KWe")
	     (?\œôÏÂ "KWi")
	     (?\œôÏÃ "KWa")
	     (?\œôÏÄ "KWE")
	     (?\œôÏÅ "KW")
	     (?\œôÏÈ "we")
	     (?\œôÏÉ "wu")
	     (?\œôÏÊ "wi")
	     (?\œôÏË "wa")
	     (?\œôÏÌ "wE")
	     (?\œôÏÍ "w")
	     (?\œôÏÎ "wo")
	     (?\œôÏĞ "`e")
	     (?\œôÏÑ "`u")
	     (?\œôÏÒ "`i")
	     (?\œôÏÓ "`a")
	     (?\œôÏÔ "`E")
	     (?\œôÏÕ "`I")
	     (?\œôÏÖ "`o")
	     (?\œôÏØ "ze")
	     (?\œôÏÙ "zu")
	     (?\œôÏÚ "zi")
	     (?\œôÏÛ "za")
	     (?\œôÏÜ "zE")
	     (?\œôÏİ "z")
	     (?\œôÏŞ "zo")
	     (?\œôÏß "zWa")
	     (?\œôÏà "Ze")
	     (?\œôÏá "Zu")
	     (?\œôÏâ "Zi")
	     (?\œôÏã "Za")
	     (?\œôÏä "ZE")
	     (?\œôÏå "Z")
	     (?\œôÏæ "Zo")
	     (?\œôÏç "ZWa")
	     (?\œôÏè "ye")
	     (?\œôÏé "yu")
	     (?\œôÏê "yi")
	     (?\œôÏë "ya")
	     (?\œôÏì "yE")
	     (?\œôÏí "y")
	     (?\œôÏî "yo")
	     (?\œôÏï "yWa")
	     (?\œôÏğ "de")
	     (?\œôÏñ "du")
	     (?\œôÏò "di")
	     (?\œôÏó "da")
	     (?\œôÏô "dE")
	     (?\œôÏõ "d")
	     (?\œôÏö "do")
	     (?\œôÏ÷ "dWa")
	     (?\œôÏø "De")
	     (?\œôÏù "Du")
	     (?\œôÏú "Di")
	     (?\œôÏû "Da")
	     (?\œôÏü "DE")
	     (?\œôÏı "D")
	     (?\œôÏş "Do")
	     (?\œôÏÿ "DWa")
	     (?\œôĞ  "je")
	     (?\œôĞ¡ "ju")
	     (?\œôĞ¢ "ji")
	     (?\œôĞ£ "ja")
	     (?\œôĞ¤ "jE")
	     (?\œôĞ¥ "j")
	     (?\œôĞ¦ "jo")
	     (?\œôĞ§ "jWa")
	     (?\œôĞ¨ "ga")
	     (?\œôĞ© "gu")
	     (?\œôĞª "gi")
	     (?\œôĞ« "ga")
	     (?\œôĞ¬ "gE")
	     (?\œôĞ­ "g")
	     (?\œôĞ® "go")
	     (?\œôĞ° "gWu")
	     (?\œôĞ² "gWi")
	     (?\œôĞ³ "gWa")
	     (?\œôĞ´ "gWE")
	     (?\œôĞµ "gW")
	     (?\œôĞ¸ "Ge")
	     (?\œôĞ¹ "Gu")
	     (?\œôĞº "Gi")
	     (?\œôĞ» "Ga")
	     (?\œôĞ¼ "GE")
	     (?\œôĞ½ "G")
	     (?\œôĞ¾ "Go")
	     (?\œôĞ¿ "GWa")
	     (?\œôĞÀ "Te")
	     (?\œôĞÁ "Tu")
	     (?\œôĞÂ "Ti")
	     (?\œôĞÃ "Ta")
	     (?\œôĞÄ "TE")
	     (?\œôĞÅ "T")
	     (?\œôĞÆ "To")
	     (?\œôĞÇ "TWa")
	     (?\œôĞÈ "Ce")
	     (?\œôĞÉ "Ca")
	     (?\œôĞÊ "Cu")
	     (?\œôĞË "Ca")
	     (?\œôĞÌ "CE")
	     (?\œôĞÍ "C")
	     (?\œôĞÎ "Co")
	     (?\œôĞÏ "CWa")
	     (?\œôĞĞ "Pe")
	     (?\œôĞÑ "Pu")
	     (?\œôĞÒ "Pi")
	     (?\œôĞÓ "Pa")
	     (?\œôĞÔ "PE")
	     (?\œôĞÕ "P")
	     (?\œôĞÖ "Po")
	     (?\œôĞ× "PWa")
	     (?\œôĞØ "SWe")
	     (?\œôĞÙ "SWu")
	     (?\œôĞÚ "SWi")
	     (?\œôĞÛ "SWa")
	     (?\œôĞÜ "SWE")
	     (?\œôĞİ "SW")
	     (?\œôĞŞ "SWo")
	     (?\œôĞß "SWa")
	     (?\œôĞà "`Sa")
	     (?\œôĞá "`Su")
	     (?\œôĞâ "`Si")
	     (?\œôĞã "`Sa")
	     (?\œôĞä "`SE")
	     (?\œôĞå "`S")
	     (?\œôĞæ "`So")
	     (?\œôĞè "fa")
	     (?\œôĞé "fu")
	     (?\œôĞê "fi")
	     (?\œôĞë "fa")
	     (?\œôĞì "fE")
	     (?\œôĞí "o")
	     (?\œôĞî "fo")
	     (?\œôĞï "fWa")
	     (?\œôĞğ "pe")
	     (?\œôĞñ "pu")
	     (?\œôĞò "pi")
	     (?\œôĞó "pa")
	     (?\œôĞô "pE")
	     (?\œôĞõ "p")
	     (?\œôĞö "po")
	     (?\œôĞ÷ "pWa")
	     (?\œôĞø "mYa")
	     (?\œôĞù "rYa")
	     (?\œôĞú "fYa")
	     (?\œôÑ  " ")
	     (?\œôÑ¡ ":")
	     (?\œôÑ¢ "::")
	     (?\œôÑ£ ",")
	     (?\œôÑ¤ ";")
	     (?\œôÑ¥ "-:")
	     (?\œôÑ¦ ":-")
	     (?\œôÑ§ "`?")
	     (?\œôÑ¨ ":|:")
	     (?\œôÑ© "`1")
	     (?\œôÑª "`2")
	     (?\œôÑ« "`3")
	     (?\œôÑ¬ "`4")
	     (?\œôÑ­ "`5")
	     (?\œôÑ® "`6")
	     (?\œôÑ¯ "`7")
	     (?\œôÑ° "`8")
	     (?\œôÑ± "`9")
	     (?\œôÑ² "`10")
	     (?\œôÑ³ "`20")
	     (?\œôÑ´ "`30")
	     (?\œôÑµ "`40")
	     (?\œôÑ¶ "`50")
	     (?\œôÑ· "`60")
	     (?\œôÑ¸ "`70")
	     (?\œôÑ¹ "`80")
	     (?\œôÑº "`90")
	     (?\œôÑ» "`100")
	     (?\œôÑ¼ "`10000")
	     (?\œôíÀ "A-0")
	     (?\œôíÁ "a-0")
	     (?\œôíÂ "B.")
	     (?\œôíÃ "b.")
	     (?\œôíÄ "B-.")
	     (?\œôíÅ "b-.")
	     (?\œôíÆ "B_")
	     (?\œôíÇ "b_")
	     (?\œôíÈ "C,'")
	     (?\œôíÉ "c,'")
	     (?\œôíÊ "D.")
	     (?\œôíË "d.")
	     (?\œôíÌ "D-.")
	     (?\œôíÍ "d-.")
	     (?\œôíÎ "D_")
	     (?\œôíÏ "d_")
	     (?\œôíĞ "D,")
	     (?\œôíÑ "d,")
	     (?\œôíÒ "D->")
	     (?\œôíÓ "d->")
	     (?\œôíÔ "E-!")
	     (?\œôíÕ "e-!")
	     (?\œôíÖ "E-'")
	     (?\œôí× "e-'")
	     (?\œôíØ "E->")
	     (?\œôíÙ "e->")
	     (?\œôíÚ "E-?")
	     (?\œôíÛ "e-?")
	     (?\œôíÜ "E,(")
	     (?\œôíİ "e,(")
	     (?\œôíŞ "F.")
	     (?\œôíß "f.")
	     (?\œôíà "G-")
	     (?\œôíá "g-")
	     (?\œôíâ "H.")
	     (?\œôíã "h.")
	     (?\œôíä "H-.")
	     (?\œôíå "h-.")
	     (?\œôíæ "H:")
	     (?\œôíç "h:")
	     (?\œôíè "H,")
	     (?\œôíé "h,")
	     (?\œôíê "H-(")
	     (?\œôíë "h-(")
	     (?\œôíì "I-?")
	     (?\œôíí "i-?")
	     (?\œôíî "I:'")
	     (?\œôíï "i:'")
	     (?\œôíğ "K'")
	     (?\œôíñ "k'")
	     (?\œôíò "K-.")
	     (?\œôíó "k-.")
	     (?\œôíô "K_")
	     (?\œôíõ "k_")
	     (?\œôíö "L-.")
	     (?\œôí÷ "l-.")
	     (?\œôíø "L--.")
	     (?\œôíù "l--.")
	     (?\œôíú "L_")
	     (?\œôíû "l_")
	     (?\œôíü "L->")
	     (?\œôíı "l->")
	     (?\œôíş "M'")
	     (?\œôíÿ "m'")
	     (?\œôî  "M.")
	     (?\œôî¡ "m.")
	     (?\œôî¢ "M-.")
	     (?\œôî£ "m-.")
	     (?\œôî¤ "N.")
	     (?\œôî¥ "n.")
	     (?\œôî¦ "N-.")
	     (?\œôî§ "n-.")
	     (?\œôî¨ "N_")
	     (?\œôî© "n_")
	     (?\œôîª "N->")
	     (?\œôî« "n->")
	     (?\œôî¬ "O?'")
	     (?\œôî­ "o?'")
	     (?\œôî® "O?:")
	     (?\œôî¯ "o?:")
	     (?\œôî° "O-!")
	     (?\œôî± "o-!")
	     (?\œôî² "O-'")
	     (?\œôî³ "o-'")
	     (?\œôî´ "P'")
	     (?\œôîµ "p'")
	     (?\œôî¶ "P.")
	     (?\œôî· "p.")
	     (?\œôî¸ "R.")
	     (?\œôî¹ "r.")
	     (?\œôîº "R-.")
	     (?\œôî» "r-.")
	     (?\œôî¼ "R--.")
	     (?\œôî½ "r--.")
	     (?\œôî¾ "R_")
	     (?\œôî¿ "r_")
	     (?\œôîÀ "S.")
	     (?\œôîÁ "s.")
	     (?\œôîÂ "S-.")
	     (?\œôîÃ "s-.")
	     (?\œôîÄ "S'.")
	     (?\œôîÅ "s'.")
	     (?\œôîÆ "S<.")
	     (?\œôîÇ "s<.")
	     (?\œôîÈ "S.-.")
	     (?\œôîÉ "s.-.")
	     (?\œôîÊ "T.")
	     (?\œôîË "t.")
	     (?\œôîÌ "T-.")
	     (?\œôîÍ "t-.")
	     (?\œôîÎ "T_")
	     (?\œôîÏ "t_")
	     (?\œôîĞ "T->")
	     (?\œôîÑ "t->")
	     (?\œôîÒ "U--:")
	     (?\œôîÓ "u--:")
	     (?\œôîÔ "U-?")
	     (?\œôîÕ "u-?")
	     (?\œôîÖ "U->")
	     (?\œôî× "u->")
	     (?\œôîØ "U?'")
	     (?\œôîÙ "u?'")
	     (?\œôîÚ "U-:")
	     (?\œôîÛ "u-:")
	     (?\œôîÜ "V?")
	     (?\œôîİ "v?")
	     (?\œôîŞ "V-.")
	     (?\œôîß "v-.")
	     (?\œôîà "W!")
	     (?\œôîá "w!")
	     (?\œôîâ "W'")
	     (?\œôîã "w'")
	     (?\œôîä "W:")
	     (?\œôîå "w:")
	     (?\œôîæ "W.")
	     (?\œôîç "w.")
	     (?\œôîè "W-.")
	     (?\œôîé "w-.")
	     (?\œôîê "X.")
	     (?\œôîë "x.")
	     (?\œôîì "X:")
	     (?\œôîí "x:")
	     (?\œôîî "Y.")
	     (?\œôîï "y.")
	     (?\œôîğ "Z>")
	     (?\œôîñ "z>")
	     (?\œôîò "Z-.")
	     (?\œôîó "z-.")
	     (?\œôîô "Z_")
	     (?\œôîõ "z_")
	     (?\œôîö "h_")
	     (?\œôî÷ "t:")
	     (?\œôîø "w0")
	     (?\œôîù "y0")
	     (?\œôï  "A-.")
	     (?\œôï¡ "a-.")
	     (?\œôï¢ "A2")
	     (?\œôï£ "a2")
	     (?\œôï¤ "A>'")
	     (?\œôï¥ "a>'")
	     (?\œôï¦ "A>!")
	     (?\œôï§ "a>!")
	     (?\œôï¨ "A>2")
	     (?\œôï© "a>2")
	     (?\œôïª "A>?")
	     (?\œôï« "a>?")
	     (?\œôï¬ "A>-.")
	     (?\œôï­ "a>-.")
	     (?\œôï® "A('")
	     (?\œôï¯ "a('")
	     (?\œôï° "A(!")
	     (?\œôï± "a(!")
	     (?\œôï² "A(2")
	     (?\œôï³ "a(2")
	     (?\œôï´ "A(?")
	     (?\œôïµ "a(?")
	     (?\œôï¶ "A(-.")
	     (?\œôï· "a(-.")
	     (?\œôï¸ "E-.")
	     (?\œôï¹ "e-.")
	     (?\œôïº "E2")
	     (?\œôï» "e2")
	     (?\œôï¼ "E?")
	     (?\œôï½ "e?")
	     (?\œôï¾ "E>'")
	     (?\œôï¿ "e>'")
	     (?\œôïÀ "E>!")
	     (?\œôïÁ "e>!")
	     (?\œôïÂ "E>2")
	     (?\œôïÃ "e>2")
	     (?\œôïÄ "E>?")
	     (?\œôïÅ "e>?")
	     (?\œôïÆ "E>-.")
	     (?\œôïÇ "e>-.")
	     (?\œôïÈ "I2")
	     (?\œôïÉ "i2")
	     (?\œôïÊ "I-.")
	     (?\œôïË "i-.")
	     (?\œôïÌ "O-.")
	     (?\œôïÍ "o-.")
	     (?\œôïÎ "O2")
	     (?\œôïÏ "o2")
	     (?\œôïĞ "O>'")
	     (?\œôïÑ "o>'")
	     (?\œôïÒ "O>!")
	     (?\œôïÓ "o>!")
	     (?\œôïÔ "O>2")
	     (?\œôïÕ "o>2")
	     (?\œôïÖ "O>?")
	     (?\œôï× "o>?")
	     (?\œôïØ "O>-.")
	     (?\œôïÙ "o>-.")
	     (?\œôïÚ "O9'")
	     (?\œôïÛ "o9'")
	     (?\œôïÜ "O9!")
	     (?\œôïİ "o9!")
	     (?\œôïŞ "O92")
	     (?\œôïß "o92")
	     (?\œôïà "O9?")
	     (?\œôïá "o9?")
	     (?\œôïâ "O9-.")
	     (?\œôïã "o9-.")
	     (?\œôïä "U-.")
	     (?\œôïå "u-.")
	     (?\œôïæ "U2")
	     (?\œôïç "u2")
	     (?\œôïè "U9'")
	     (?\œôïé "u9'")
	     (?\œôïê "U9!")
	     (?\œôïë "u9!")
	     (?\œôïì "U92")
	     (?\œôïí "u92")
	     (?\œôïî "U9?")
	     (?\œôïï "u9?")
	     (?\œôïğ "U9-.")
	     (?\œôïñ "u9-.")
	     (?\œôïò "Y!")
	     (?\œôïó "y!")
	     (?\œôïô "Y-.")
	     (?\œôïõ "y-.")
	     (?\œôïö "Y2")
	     (?\œôï÷ "y2")
	     (?\œôïø "Y?")
	     (?\œôïù "y?")
	     (?\œôğ  "a")
	     (?\œôğ¡ "ha")
	     (?\œôğ¢ "`a")
	     (?\œôğ£ "h`a")
	     (?\œôğ¤ "a'")
	     (?\œôğ¥ "ha'")
	     (?\œôğ¦ "a~")
	     (?\œôğ§ "ha~")
	     (?\œôğ¨ "A")
	     (?\œôğ© "hA")
	     (?\œôğª "`A")
	     (?\œôğ« "h`A")
	     (?\œôğ¬ "A'")
	     (?\œôğ­ "hA'")
	     (?\œôğ® "A~")
	     (?\œôğ¯ "hA~")
	     (?\œôğ± "he")
	     (?\œôğ¹ "hE")
	     (?\œôğÑ "hi")
	     (?\œôğÙ "hI")
	     (?\œôğá "ho")
	     (?\œôğé "hO")
	     (?\œôğñ "hu")
	     (?\œôğù "hU")
	     (?\œôñÿ ",,")
	     (?\œôò  "?*")
	     (?\œôò¡ "?:")
	     (?\œôò­ ",!")
	     (?\œôò® ",'")
	     (?\œôò¯ "?,")
	     (?\œôò½ ";!")
	     (?\œôò¾ ";'")
	     (?\œôò¿ "?;")
	     (?\œôòÅ "rh")
	     (?\œôòÌ "Rh")
	     (?\œôòÍ "!:")
	     (?\œôòÏ "!*")
	     (?\œôòŞ ";;")
	     (?\œôòà " ")
	     (?\œôòá "  ")
	     (?\œôòâ " ")
	     (?\œôòã "  ")
	     (?\œôòä " ")
	     (?\œôòå " ")
	     (?\œôòæ " ")
	     (?\œôòç " ")
	     (?\œôòè " ")
	     (?\œôòé " ")
	     (?\œôòğ "-")
	     (?\œôòñ "-")
	     (?\œôòó "-")
	     (?\œôòô "--")
	     (?\œôòõ "-")
	     (?\œôòö "||")
	     (?\œôò÷ "=2")
	     (?\œôòø "`")
	     (?\œôòù "'")
	     (?\œôòú "'")
	     (?\œôòû "'")
	     (?\œôòü "\"")
	     (?\œôòı "\"")
	     (?\œôòş "\"")
	     (?\œôòÿ "\"")
	     (?\œôó  "/-")
	     (?\œôó¡ "/=")
	     (?\œôó¢ " o ")
	     (?\œôó¤ ".")
	     (?\œôó¥ "..")
	     (?\œôó¦ "...")
	     (?\œôó§ "·")
	     (?\œôó° " 0/00")
	     (?\œôó² "'")
	     (?\œôó³ "''")
	     (?\œôó´ "'''")
	     (?\œôóµ "`")
	     (?\œôó¶ "``")
	     (?\œôó· "```")
	     (?\œôó¸ "Ca")
	     (?\œôó¹ "<")
	     (?\œôóº ">")
	     (?\œôó» ":X")
	     (?\œôó¼ "!!")
	     (?\œôó¾ "'-")
	     (?\œôóÃ "-")
	     (?\œôóÄ "/")
	     (?\œôóÈ "?!")
	     (?\œôóÉ "!?")
	     (?\œôóğ "^0")
	     (?\œôóô "^4")
	     (?\œôóõ "^5")
	     (?\œôóö "^6")
	     (?\œôó÷ "^7")
	     (?\œôóø "^8")
	     (?\œôóù "^9")
	     (?\œôóú "^+")
	     (?\œôóû "^-")
	     (?\œôóü "^=")
	     (?\œôóı "^(")
	     (?\œôóş "^)")
	     (?\œôóÿ "^n")
	     (?\œôô  "_0")
	     (?\œôô¡ "_1")
	     (?\œôô¢ "_2")
	     (?\œôô£ "_3")
	     (?\œôô¤ "_4")
	     (?\œôô¥ "_5")
	     (?\œôô¦ "_6")
	     (?\œôô§ "_7")
	     (?\œôô¨ "_8")
	     (?\œôô© "_9")
	     (?\œôôª "_+")
	     (?\œôô« "_-")
	     (?\œôô¬ "_=")
	     (?\œôô­ "(")
	     (?\œôô® ")")
	     (?\œôôÃ "Ff")
	     (?\œôôÄ "Li")
	     (?\œôôÇ "Pt")
	     (?\œôôÉ "W=")
	     (?\œôôÌ "EUR")
	     (?\œôõÀ "a/c")
	     (?\œôõÁ "a/s")
	     (?\œôõÃ "oC")
	     (?\œôõÅ "c/o")
	     (?\œôõÆ "c/u")
	     (?\œôõÉ "oF")
	     (?\œôõÊ "g")
	     (?\œôõÎ "h")
	     (?\œôõÏ "\\hbar")
	     (?\œôõÑ "Im")
	     (?\œôõÓ "l")
	     (?\œôõÖ "No.")
	     (?\œôõ× "PO")
	     (?\œôõØ "P")
	     (?\œôõÜ "Re")
	     (?\œôõŞ "Rx")
	     (?\œôõà "(SM)")
	     (?\œôõá "TEL")
	     (?\œôõâ "(TM)")
	     (?\œôõæ "Ohm")
	     (?\œôõê "K")
	     (?\œôõë "Ang.")
	     (?\œôõî "est.")
	     (?\œôõô "o")
	     (?\œôõõ "Aleph ")
	     (?\œôõö "Bet ")
	     (?\œôõ÷ "Gimel ")
	     (?\œôõø "Dalet ")
	     (?\œôö³ " 1/3")
	     (?\œôö´ " 2/3")
	     (?\œôöµ " 1/5")
	     (?\œôö¶ " 2/5")
	     (?\œôö· " 3/5")
	     (?\œôö¸ " 4/5")
	     (?\œôö¹ " 1/6")
	     (?\œôöº " 5/6")
	     (?\œôö» " 1/8")
	     (?\œôö¼ " 3/8")
	     (?\œôö½ " 5/8")
	     (?\œôö¾ " 7/8")
	     (?\œôö¿ " 1/")
	     (?\œôöÀ "I")
	     (?\œôöÁ "II")
	     (?\œôöÂ "III")
	     (?\œôöÃ "IV")
	     (?\œôöÄ "V")
	     (?\œôöÅ "VI")
	     (?\œôöÆ "VII")
	     (?\œôöÇ "VIII")
	     (?\œôöÈ "IX")
	     (?\œôöÉ "X")
	     (?\œôöÊ "XI")
	     (?\œôöË "XII")
	     (?\œôöÌ "L")
	     (?\œôöÍ "C")
	     (?\œôöÎ "D")
	     (?\œôöÏ "M")
	     (?\œôöĞ "i")
	     (?\œôöÑ "ii")
	     (?\œôöÒ "iii")
	     (?\œôöÓ "iv")
	     (?\œôöÔ "v")
	     (?\œôöÕ "vi")
	     (?\œôöÖ "vii")
	     (?\œôö× "viii")
	     (?\œôöØ "ix")
	     (?\œôöÙ "x")
	     (?\œôöÚ "xi")
	     (?\œôöÛ "xii")
	     (?\œôöÜ "l")
	     (?\œôöİ "c")
	     (?\œôöŞ "d")
	     (?\œôöß "m")
	     (?\œôöà "1000RCD")
	     (?\œôöá "5000R")
	     (?\œôöâ "10000R")
	     (?\œôöğ "<-")
	     (?\œôöñ "-^")
	     (?\œôöò "->")
	     (?\œôöó "-v")
	     (?\œôöô "<->")
	     (?\œôöõ "UD")
	     (?\œôöö "<!!")
	     (?\œôö÷ "//>")
	     (?\œôöø "!!>")
	     (?\œôöù "<//")
	     (?\œô÷¨ "UD-")
	     (?\œô÷µ "RET")
	     (?\œô÷À ">V")
	     (?\œô÷Ğ "<=")
	     (?\œô÷Ñ "^^")
	     (?\œô÷Ò "=>")
	     (?\œô÷Ó "vv")
	     (?\œô÷Ô "<=>")
	     (?\œôø  "FA")
	     (?\œôø¢ "\\partial")
	     (?\œôø£ "TE")
	     (?\œôø¥ "{}")
	     (?\œôø¦ "Delta")
	     (?\œôø§ "Nabla")
	     (?\œôø¨ "(-")
	     (?\œôø© "!(-")
	     (?\œôøª "(-")
	     (?\œôø« "-)")
	     (?\œôø¬ "!-)")
	     (?\œôø­ "-)")
	     (?\œôø® " qed")
	     (?\œôø¯ "\\prod")
	     (?\œôø± "\\sum")
	     (?\œôø² " -")
	     (?\œôø³ "-/+")
	     (?\œôø´ ".+")
	     (?\œôøµ "/")
	     (?\œôø¶ " - ")
	     (?\œôø· "*")
	     (?\œôø¸ " ° ")
	     (?\œôø¹ "sb")
	     (?\œôøº " SQRT ")
	     (?\œôø» " ROOT³ ")
	     (?\œôø¼ " ROOT4 ")
	     (?\œôø½ "0(")
	     (?\œôø¾ "infty")
	     (?\œôø¿ "-L")
	     (?\œôøÀ "-V")
	     (?\œôøÅ "PP")
	     (?\œôøÆ " !PP ")
	     (?\œôøÇ "AND")
	     (?\œôøÈ "OR")
	     (?\œôøÉ "(U")
	     (?\œôøÊ ")U")
	     (?\œôøË "\int ")
	     (?\œôøÌ "DI")
	     (?\œôøÎ "Io")
	     (?\œôøÔ ".:")
	     (?\œôøÕ ":.")
	     (?\œôøÖ ":R")
	     (?\œôø× "::")
	     (?\œôøÜ "?1")
	     (?\œôøŞ "CG")
	     (?\œôøã "?-")
	     (?\œôøå "?=")
	     (?\œôøè "~=")
	     (?\œôøé " !~= ")
	     (?\œôøì "=?")
	     (?\œôøó "HI")
	     (?\œôøô ":=")
	     (?\œôøõ "=:")
	     (?\œôù  "!=")
	     (?\œôù¡ "=3")
	     (?\œôù¢ " !=3 ")
	     (?\œôù¤ "=<")
	     (?\œôù¥ ">=")
	     (?\œôù¦ ".LE.")
	     (?\œôù§ ".GE.")
	     (?\œôù¨ ".LT.NOT.EQ.")
	     (?\œôù© ".GT.NOT.EQ.")
	     (?\œôùª "<<")
	     (?\œôù« ">>")
	     (?\œôù® "!<")
	     (?\œôù¯ "!>")
	     (?\œôù¶ " <> ")
	     (?\œôù· " >< ")
	     (?\œôùÂ "(C")
	     (?\œôùÃ ")C")
	     (?\œôùÄ " !(C ")
	     (?\œôùÅ " !)C ")
	     (?\œôùÆ "(_")
	     (?\œôùÇ ")_")
	     (?\œôùÕ "(+)")
	     (?\œôùÖ "(-)")
	     (?\œôù× "(×)")
	     (?\œôùØ "(/)")
	     (?\œôùÙ "(·)")
	     (?\œôùÚ "(°)")
	     (?\œôùÛ "(*)")
	     (?\œôùÜ "(=)")
	     (?\œôùİ "(-)")
	     (?\œôùŞ "[+]")
	     (?\œôùß "[-]")
	     (?\œôùà "[×]")
	     (?\œôùá "[·]")
	     (?\œôùå "-T")
	     (?\œôùç " MODELS ")
	     (?\œôùè " TRUE ")
	     (?\œôùé " FORCES ")
	     (?\œôùì " !PROVES ")
	     (?\œôùí " NOT TRUE ")
	     (?\œôùî " !FORCES ")
	     (?\œôùò " NORMAL SUBGROUP OF ")
	     (?\œôùó " CONTAINS AS NORMAL SUBGROUP ")
	     (?\œôùô " NORMAL SUBGROUP OF OR EQUAL TO ")
	     (?\œôùõ " CONTAINS AS NORMAL SUBGROUP OR EQUAL TO ")
	     (?\œôùø " MULTIMAP ")
	     (?\œôùú " INTERCALATE ")
	     (?\œôùû " XOR ")
	     (?\œôùü " NAND ")
	     (?\œôú¥ " · ")
	     (?\œôú¶ "<.")
	     (?\œôú· ">.")
	     (?\œôú¸ "<<<")
	     (?\œôú¹ ">>>")
	     (?\œôúÎ ":3")
	     (?\œôúÏ ".3")
	     (?\œôúâ "Eh")
	     (?\œôúç "~~")
	     (?\œôúè "<7")
	     (?\œôúé ">7")
	     (?\œôúê "7<")
	     (?\œôúë "7>")
	     (?\œôúğ "NI")
	     (?\œôúò "(A")
	     (?\œôúõ "TR")
	     (?\œôúø "88")
	     (?\œôû  "Iu")
	     (?\œôû¡ "Il")
	     (?\œôû¢ ":(")
	     (?\œôû£ ":)")
	     (?\œôû¤ "|^|")
	     (?\œôû§ "[X]")
	     (?\œôû© "</")
	     (?\œôûª "/>")
	     (?\œôıã "Vs")
	     (?\œôş  "1h")
	     (?\œôş¡ "3h")
	     (?\œôş¢ "2h")
	     (?\œôş£ "4h")
	     (?\œôş¦ "1j")
	     (?\œôş§ "2j")
	     (?\œôş¨ "3j")
	     (?\œôş© "4j")
	     (?\œôşÀ "1-o")
	     (?\œôşÁ "2-o")
	     (?\œôşÂ "3-o")
	     (?\œôşÃ "4-o")
	     (?\œôşÄ "5-o")
	     (?\œôşÅ "6-o")
	     (?\œôşÆ "7-o")
	     (?\œôşÇ "8-o")
	     (?\œôşÈ "9-o")
	     (?\œôşÉ "10-o")
	     (?\œôşÊ "11-o")
	     (?\œôşË "12-o")
	     (?\œôşÌ "13-o")
	     (?\œôşÍ "14-o")
	     (?\œôşÎ "15-o")
	     (?\œôşÏ "16-o")
	     (?\œôşĞ "17-o")
	     (?\œôşÑ "18-o")
	     (?\œôşÒ "19-o")
	     (?\œôşÓ "20-o")
	     (?\œôşÔ "(1)")
	     (?\œôşÕ "(2)")
	     (?\œôşÖ "(3)")
	     (?\œôş× "(4)")
	     (?\œôşØ "(5)")
	     (?\œôşÙ "(6)")
	     (?\œôşÚ "(7)")
	     (?\œôşÛ "(8)")
	     (?\œôşÜ "(9)")
	     (?\œôşİ "(10)")
	     (?\œôşŞ "(11)")
	     (?\œôşß "(12)")
	     (?\œôşà "(13)")
	     (?\œôşá "(14)")
	     (?\œôşâ "(15)")
	     (?\œôşã "(16)")
	     (?\œôşä "(17)")
	     (?\œôşå "(18)")
	     (?\œôşæ "(19)")
	     (?\œôşç "(20)")
	     (?\œôşè "1.")
	     (?\œôşé "2.")
	     (?\œôşê "3.")
	     (?\œôşë "4.")
	     (?\œôşì "5.")
	     (?\œôşí "6.")
	     (?\œôşî "7.")
	     (?\œôşï "8.")
	     (?\œôşğ "9.")
	     (?\œôşñ "10.")
	     (?\œôşò "11.")
	     (?\œôşó "12.")
	     (?\œôşô "13.")
	     (?\œôşõ "14.")
	     (?\œôşö "15.")
	     (?\œôş÷ "16.")
	     (?\œôşø "17.")
	     (?\œôşù "18.")
	     (?\œôşú "19.")
	     (?\œôşû "20.")
	     (?\œôşü "(a)")
	     (?\œôşı "(b)")
	     (?\œôşş "(c)")
	     (?\œôşÿ "(d)")
	     (?\œôÿ  "(e)")
	     (?\œôÿ¡ "(f)")
	     (?\œôÿ¢ "(g)")
	     (?\œôÿ£ "(h)")
	     (?\œôÿ¤ "(i)")
	     (?\œôÿ¥ "(j)")
	     (?\œôÿ¦ "(k)")
	     (?\œôÿ§ "(l)")
	     (?\œôÿ¨ "(m)")
	     (?\œôÿ© "(n)")
	     (?\œôÿª "(o)")
	     (?\œôÿ« "(p)")
	     (?\œôÿ¬ "(q)")
	     (?\œôÿ­ "(r)")
	     (?\œôÿ® "(s)")
	     (?\œôÿ¯ "(t)")
	     (?\œôÿ° "(u)")
	     (?\œôÿ± "(v)")
	     (?\œôÿ² "(w)")
	     (?\œôÿ³ "(x)")
	     (?\œôÿ´ "(y)")
	     (?\œôÿµ "(z)")
	     (?\œôÿ¶ "A-o")
	     (?\œôÿ· "B-o")
	     (?\œôÿ¸ "C-o")
	     (?\œôÿ¹ "D-o")
	     (?\œôÿº "E-o")
	     (?\œôÿ» "F-o")
	     (?\œôÿ¼ "G-o")
	     (?\œôÿ½ "H-o")
	     (?\œôÿ¾ "I-o")
	     (?\œôÿ¿ "J-o")
	     (?\œôÿÀ "K-o")
	     (?\œôÿÁ "L-o")
	     (?\œôÿÂ "M-o")
	     (?\œôÿÃ "N-o")
	     (?\œôÿÄ "O-o")
	     (?\œôÿÅ "P-o")
	     (?\œôÿÆ "Q-o")
	     (?\œôÿÇ "R-o")
	     (?\œôÿÈ "S-o")
	     (?\œôÿÉ "T-o")
	     (?\œôÿÊ "U-o")
	     (?\œôÿË "V-o")
	     (?\œôÿÌ "W-o")
	     (?\œôÿÍ "X-o")
	     (?\œôÿÎ "Y-o")
	     (?\œôÿÏ "Z-o")
	     (?\œôÿĞ "a-o")
	     (?\œôÿÑ "b-o")
	     (?\œôÿÒ "c-o")
	     (?\œôÿÓ "d-o")
	     (?\œôÿÔ "e-o")
	     (?\œôÿÕ "f-o")
	     (?\œôÿÖ "g-o")
	     (?\œôÿ× "h-o")
	     (?\œôÿØ "i-o")
	     (?\œôÿÙ "j-o")
	     (?\œôÿÚ "k-o")
	     (?\œôÿÛ "l-o")
	     (?\œôÿÜ "m-o")
	     (?\œôÿİ "n-o")
	     (?\œôÿŞ "o-o")
	     (?\œôÿß "p-o")
	     (?\œôÿà "q-o")
	     (?\œôÿá "r-o")
	     (?\œôÿâ "s-o")
	     (?\œôÿã "t-o")
	     (?\œôÿä "u-o")
	     (?\œôÿå "v-o")
	     (?\œôÿæ "w-o")
	     (?\œôÿç "x-o")
	     (?\œôÿè "y-o")
	     (?\œôÿé "z-o")
	     (?\œôÿê "0-o")
	     (?\œò   "-")
	     (?\œò ¡ "=")
	     (?\œò ¢ "|")
	     (?\œò £ "|")
	     (?\œò ¤ "-")
	     (?\œò ¥ "=")
	     (?\œò ¦ "|")
	     (?\œò § "|")
	     (?\œò ¨ "-")
	     (?\œò © "=")
	     (?\œò ª "|")
	     (?\œò « "|")
	     (?\œò ¬ "+")
	     (?\œò ­ "+")
	     (?\œò ® "+")
	     (?\œò ¯ "+")
	     (?\œò ° "+")
	     (?\œò ± "+")
	     (?\œò ² "+")
	     (?\œò ³ "+")
	     (?\œò ´ "+")
	     (?\œò µ "+")
	     (?\œò ¶ "+")
	     (?\œò · "+")
	     (?\œò ¸ "+")
	     (?\œò ¹ "+")
	     (?\œò º "+")
	     (?\œò » "+")
	     (?\œò ¼ "+")
	     (?\œò ½ "+")
	     (?\œò ¾ "+")
	     (?\œò ¿ "+")
	     (?\œò À "+")
	     (?\œò Á "+")
	     (?\œò Â "+")
	     (?\œò Ã "+")
	     (?\œò Ä "+")
	     (?\œò Å "+")
	     (?\œò Æ "+")
	     (?\œò Ç "+")
	     (?\œò È "+")
	     (?\œò É "+")
	     (?\œò Ê "+")
	     (?\œò Ë "+")
	     (?\œò Ì "+")
	     (?\œò Í "+")
	     (?\œò Î "+")
	     (?\œò Ï "+")
	     (?\œò Ğ "+")
	     (?\œò Ñ "+")
	     (?\œò Ò "+")
	     (?\œò Ó "+")
	     (?\œò Ô "+")
	     (?\œò Õ "+")
	     (?\œò Ö "+")
	     (?\œò × "+")
	     (?\œò Ø "+")
	     (?\œò Ù "+")
	     (?\œò Ú "+")
	     (?\œò Û "+")
	     (?\œò Ü "+")
	     (?\œò İ "+")
	     (?\œò Ş "+")
	     (?\œò ß "+")
	     (?\œò à "+")
	     (?\œò á "+")
	     (?\œò â "+")
	     (?\œò ã "+")
	     (?\œò ä "+")
	     (?\œò å "+")
	     (?\œò æ "+")
	     (?\œò ç "+")
	     (?\œò è "+")
	     (?\œò é "+")
	     (?\œò ê "+")
	     (?\œò ë "+")
	     (?\œò ì "+")
	     (?\œò í "+")
	     (?\œò î "+")
	     (?\œò ï "+")
	     (?\œò ğ "+")
	     (?\œò ñ "+")
	     (?\œò ò "+")
	     (?\œò ó "+")
	     (?\œò ô "+")
	     (?\œò õ "+")
	     (?\œò ö "+")
	     (?\œò ÷ "+")
	     (?\œò ø "+")
	     (?\œò ù "+")
	     (?\œò ú "+")
	     (?\œò û "+")
	     (?\œò ü "+")
	     (?\œò ı "+")
	     (?\œò ş "+")
	     (?\œò ÿ "+")
	     (?\œò¡  "+")
	     (?\œò¡¡ "+")
	     (?\œò¡¢ "+")
	     (?\œò¡£ "+")
	     (?\œò¡¤ "+")
	     (?\œò¡¥ "+")
	     (?\œò¡¦ "+")
	     (?\œò¡§ "+")
	     (?\œò¡¨ "+")
	     (?\œò¡© "+")
	     (?\œò¡ª "+")
	     (?\œò¡« "+")
	     (?\œò¡¬ "+")
	     (?\œò¡± "/")
	     (?\œò¡² "\\")
	     (?\œò¡À "TB")
	     (?\œò¡Ä "LB")
	     (?\œò¡È "FB")
	     (?\œò¡Ì "lB")
	     (?\œò¡Ğ "RB")
	     (?\œò¡Ñ ".S")
	     (?\œò¡Ò ":S")
	     (?\œò¡Ó "?S")
	     (?\œò¡à "fS")
	     (?\œò¡á "OS")
	     (?\œò¡â "RO")
	     (?\œò¡ã "Rr")
	     (?\œò¡ä "RF")
	     (?\œò¡å "RY")
	     (?\œò¡æ "RH")
	     (?\œò¡ç "RZ")
	     (?\œò¡è "RK")
	     (?\œò¡é "RX")
	     (?\œò¡ê "sB")
	     (?\œò¡ì "SR")
	     (?\œò¡í "Or")
	     (?\œò¡ò "^")
	     (?\œò¡ó "uT")
	     (?\œò¡ö "|>")
	     (?\œò¡÷ "Tr")
	     (?\œò¡ú "|>")
	     (?\œò¡ü "v")
	     (?\œò¡ı "dT")
	     (?\œò¢  "<|")
	     (?\œò¢¡ "Tl")
	     (?\œò¢¤ "<|")
	     (?\œò¢¦ "Db")
	     (?\œò¢§ "Dw")
	     (?\œò¢ª "LZ")
	     (?\œò¢« "0m")
	     (?\œò¢® "0o")
	     (?\œò¢¯ "0M")
	     (?\œò¢° "0L")
	     (?\œò¢± "0R")
	     (?\œò¢¸ "Sn")
	     (?\œò¢¹ "Ic")
	     (?\œò¢Â "Fd")
	     (?\œò¢Ã "Bd")
	     (?\œò¢Ï "Ci")
	     (?\œò¢å "*2")
	     (?\œò¢æ "*1")
	     (?\œò¢î "TEL")
	     (?\œò¢ï "tel")
	     (?\œò¢ü "<--")
	     (?\œò¢ş "-->")
	     (?\œò£¡ "CAUTION ")
	     (?\œò£§ "XP")
	     (?\œò£¹ ":-(")
	     (?\œò£º ":-)")
	     (?\œò£» "(-:")
	     (?\œò£¼ "SU")
	     (?\œò£À "f.")
	     (?\œò£Â "m.")
	     (?\œò£à "cS")
	     (?\œò£á "cH")
	     (?\œò£â "cD")
	     (?\œò£ã "cC")
	     (?\œò£ä "cS-")
	     (?\œò£å "cH-")
	     (?\œò£æ "cD-")
	     (?\œò£ç "cC-")
	     (?\œò£é "Md")
	     (?\œò£ê "M8")
	     (?\œò£ë "M2")
	     (?\œò£ì "M16")
	     (?\œò£í "b")
	     (?\œò£î "Mx")
	     (?\œò£ï "#")
	     (?\œò¥Ó "X")
	     (?\œò¥× "X")
	     (?\œò¥à "-X")
	     (?\œò½À " ")
	     (?\œò½Á ",_")
	     (?\œò½Â "._")
	     (?\œò½Ã "+\"")
	     (?\œò½Ä "JIS")
	     (?\œò½Å "*_")
	     (?\œò½Æ ";_")
	     (?\œò½Ç "0_")
	     (?\œò½Ê "<+")
	     (?\œò½Ë ">+")
	     (?\œò½Ì "<'")
	     (?\œò½Í ">'")
	     (?\œò½Î "<\"")
	     (?\œò½Ï ">\"")
	     (?\œò½Ğ "(\"")
	     (?\œò½Ñ ")\"")
	     (?\œò½Ò "=T")
	     (?\œò½Ó "=_")
	     (?\œò½Ô "('")
	     (?\œò½Õ ")'")
	     (?\œò½Ö "(I")
	     (?\œò½× ")I")
	     (?\œò½Ú "[[")
	     (?\œò½Û "]]")
	     (?\œò½Ü "-?")
	     (?\œò½à "=T:)")
	     (?\œò½ÿ " ")
	     (?\œò¾¡ "A5")
	     (?\œò¾¢ "a5")
	     (?\œò¾£ "I5")
	     (?\œò¾¤ "i5")
	     (?\œò¾¥ "U5")
	     (?\œò¾¦ "u5")
	     (?\œò¾§ "E5")
	     (?\œò¾¨ "e5")
	     (?\œò¾© "O5")
	     (?\œò¾ª "o5")
	     (?\œò¾« "ka")
	     (?\œò¾¬ "ga")
	     (?\œò¾­ "ki")
	     (?\œò¾® "gi")
	     (?\œò¾¯ "ku")
	     (?\œò¾° "gu")
	     (?\œò¾± "ke")
	     (?\œò¾² "ge")
	     (?\œò¾³ "ko")
	     (?\œò¾´ "go")
	     (?\œò¾µ "sa")
	     (?\œò¾¶ "za")
	     (?\œò¾· "si")
	     (?\œò¾¸ "zi")
	     (?\œò¾¹ "su")
	     (?\œò¾º "zu")
	     (?\œò¾» "se")
	     (?\œò¾¼ "ze")
	     (?\œò¾½ "so")
	     (?\œò¾¾ "zo")
	     (?\œò¾¿ "ta")
	     (?\œò¾À "da")
	     (?\œò¾Á "ti")
	     (?\œò¾Â "di")
	     (?\œò¾Ã "tU")
	     (?\œò¾Ä "tu")
	     (?\œò¾Å "du")
	     (?\œò¾Æ "te")
	     (?\œò¾Ç "de")
	     (?\œò¾È "to")
	     (?\œò¾É "do")
	     (?\œò¾Ê "na")
	     (?\œò¾Ë "ni")
	     (?\œò¾Ì "nu")
	     (?\œò¾Í "ne")
	     (?\œò¾Î "no")
	     (?\œò¾Ï "ha")
	     (?\œò¾Ğ "ba")
	     (?\œò¾Ñ "pa")
	     (?\œò¾Ò "hi")
	     (?\œò¾Ó "bi")
	     (?\œò¾Ô "pi")
	     (?\œò¾Õ "hu")
	     (?\œò¾Ö "bu")
	     (?\œò¾× "pu")
	     (?\œò¾Ø "he")
	     (?\œò¾Ù "be")
	     (?\œò¾Ú "pe")
	     (?\œò¾Û "ho")
	     (?\œò¾Ü "bo")
	     (?\œò¾İ "po")
	     (?\œò¾Ş "ma")
	     (?\œò¾ß "mi")
	     (?\œò¾à "mu")
	     (?\œò¾á "me")
	     (?\œò¾â "mo")
	     (?\œò¾ã "yA")
	     (?\œò¾ä "ya")
	     (?\œò¾å "yU")
	     (?\œò¾æ "yu")
	     (?\œò¾ç "yO")
	     (?\œò¾è "yo")
	     (?\œò¾é "ra")
	     (?\œò¾ê "ri")
	     (?\œò¾ë "ru")
	     (?\œò¾ì "re")
	     (?\œò¾í "ro")
	     (?\œò¾î "wA")
	     (?\œò¾ï "wa")
	     (?\œò¾ğ "wi")
	     (?\œò¾ñ "we")
	     (?\œò¾ò "wo")
	     (?\œò¾ó "n5")
	     (?\œò¾ô "vu")
	     (?\œò¾û "\"5")
	     (?\œò¾ü "05")
	     (?\œò¾ı "*5")
	     (?\œò¾ş "+5")
	     (?\œò¿¡ "a6")
	     (?\œò¿¢ "A6")
	     (?\œò¿£ "i6")
	     (?\œò¿¤ "I6")
	     (?\œò¿¥ "u6")
	     (?\œò¿¦ "U6")
	     (?\œò¿§ "e6")
	     (?\œò¿¨ "E6")
	     (?\œò¿© "o6")
	     (?\œò¿ª "O6")
	     (?\œò¿« "Ka")
	     (?\œò¿¬ "Ga")
	     (?\œò¿­ "Ki")
	     (?\œò¿® "Gi")
	     (?\œò¿¯ "Ku")
	     (?\œò¿° "Gu")
	     (?\œò¿± "Ke")
	     (?\œò¿² "Ge")
	     (?\œò¿³ "Ko")
	     (?\œò¿´ "Go")
	     (?\œò¿µ "Sa")
	     (?\œò¿¶ "Za")
	     (?\œò¿· "Si")
	     (?\œò¿¸ "Zi")
	     (?\œò¿¹ "Su")
	     (?\œò¿º "Zu")
	     (?\œò¿» "Se")
	     (?\œò¿¼ "Ze")
	     (?\œò¿½ "So")
	     (?\œò¿¾ "Zo")
	     (?\œò¿¿ "Ta")
	     (?\œò¿À "Da")
	     (?\œò¿Á "Ti")
	     (?\œò¿Â "Di")
	     (?\œò¿Ã "TU")
	     (?\œò¿Ä "Tu")
	     (?\œò¿Å "Du")
	     (?\œò¿Æ "Te")
	     (?\œò¿Ç "De")
	     (?\œò¿È "To")
	     (?\œò¿É "Do")
	     (?\œò¿Ê "Na")
	     (?\œò¿Ë "Ni")
	     (?\œò¿Ì "Nu")
	     (?\œò¿Í "Ne")
	     (?\œò¿Î "No")
	     (?\œò¿Ï "Ha")
	     (?\œò¿Ğ "Ba")
	     (?\œò¿Ñ "Pa")
	     (?\œò¿Ò "Hi")
	     (?\œò¿Ó "Bi")
	     (?\œò¿Ô "Pi")
	     (?\œò¿Õ "Hu")
	     (?\œò¿Ö "Bu")
	     (?\œò¿× "Pu")
	     (?\œò¿Ø "He")
	     (?\œò¿Ù "Be")
	     (?\œò¿Ú "Pe")
	     (?\œò¿Û "Ho")
	     (?\œò¿Ü "Bo")
	     (?\œò¿İ "Po")
	     (?\œò¿Ş "Ma")
	     (?\œò¿ß "Mi")
	     (?\œò¿à "Mu")
	     (?\œò¿á "Me")
	     (?\œò¿â "Mo")
	     (?\œò¿ã "YA")
	     (?\œò¿ä "Ya")
	     (?\œò¿å "YU")
	     (?\œò¿æ "Yu")
	     (?\œò¿ç "YO")
	     (?\œò¿è "Yo")
	     (?\œò¿é "Ra")
	     (?\œò¿ê "Ri")
	     (?\œò¿ë "Ru")
	     (?\œò¿ì "Re")
	     (?\œò¿í "Ro")
	     (?\œò¿î "WA")
	     (?\œò¿ï "Wa")
	     (?\œò¿ğ "Wi")
	     (?\œò¿ñ "We")
	     (?\œò¿ò "Wo")
	     (?\œò¿ó "N6")
	     (?\œò¿ô "Vu")
	     (?\œò¿õ "KA")
	     (?\œò¿ö "KE")
	     (?\œò¿÷ "Va")
	     (?\œò¿ø "Vi")
	     (?\œò¿ù "Ve")
	     (?\œò¿ú "Vo")
	     (?\œò¿û ".6")
	     (?\œò¿ü "-6")
	     (?\œò¿ı "*6")
	     (?\œò¿ş "+6")
	     (?\œòÀ¥ "b4")
	     (?\œòÀ¦ "p4")
	     (?\œòÀ§ "m4")
	     (?\œòÀ¨ "f4")
	     (?\œòÀ© "d4")
	     (?\œòÀª "t4")
	     (?\œòÀ« "n4")
	     (?\œòÀ¬ "l4")
	     (?\œòÀ­ "g4")
	     (?\œòÀ® "k4")
	     (?\œòÀ¯ "h4")
	     (?\œòÀ° "j4")
	     (?\œòÀ± "q4")
	     (?\œòÀ² "x4")
	     (?\œòÀ³ "zh")
	     (?\œòÀ´ "ch")
	     (?\œòÀµ "sh")
	     (?\œòÀ¶ "r4")
	     (?\œòÀ· "z4")
	     (?\œòÀ¸ "c4")
	     (?\œòÀ¹ "s4")
	     (?\œòÀº "a4")
	     (?\œòÀ» "o4")
	     (?\œòÀ¼ "e4")
	     (?\œòÀ½ "eh4")
	     (?\œòÀ¾ "ai")
	     (?\œòÀ¿ "ei")
	     (?\œòÀÀ "au")
	     (?\œòÀÁ "ou")
	     (?\œòÀÂ "an")
	     (?\œòÀÃ "en")
	     (?\œòÀÄ "aN")
	     (?\œòÀÅ "eN")
	     (?\œòÀÆ "er")
	     (?\œòÀÇ "i4")
	     (?\œòÀÈ "u4")
	     (?\œòÀÉ "iu")
	     (?\œòÀÊ "v4")
	     (?\œòÀË "nG")
	     (?\œòÀÌ "gn")
	     (?\œòÂü "(JU)")
	     (?\œòÃ  "1c")
	     (?\œòÃ¡ "2c")
	     (?\œòÃ¢ "3c")
	     (?\œòÃ£ "4c")
	     (?\œòÃ¤ "5c")
	     (?\œòÃ¥ "6c")
	     (?\œòÃ¦ "7c")
	     (?\œòÃ§ "8c")
	     (?\œòÃ¨ "9c")
	     (?\œòÃ© "10c")
	     (?\œòÃÿ "KSC")
	     (?\œòÇÂ "am")
	     (?\œòÇØ "pm")
	     (?\œóè  "ff")
	     (?\œóè¡ "fi")
	     (?\œóè¢ "fl")
	     (?\œóè£ "ffi")
	     (?\œóè¤ "ffl")
	     (?\œóè¥ "St")
	     (?\œóè¦ "st")
	     (?\œóñ½ "3+;")
	     (?\œóñÂ "aM.")
	     (?\œóñÄ "aH.")
	     (?\œóñÈ "ah.")
	     (?\œóñÍ "a+-")
	     (?\œóñÎ "a+.")
	     (?\œóñÏ "b+-")
	     (?\œóñĞ "b+.")
	     (?\œóñÑ "b+,")
	     (?\œóñÒ "b+;")
	     (?\œóñÓ "tm-")
	     (?\œóñÔ "tm.")
	     (?\œóñÕ "t+-")
	     (?\œóñÖ "t+.")
	     (?\œóñ× "t+,")
	     (?\œóñØ "t+;")
	     (?\œóñÙ "tk-")
	     (?\œóñÚ "tk.")
	     (?\œóñÛ "tk,")
	     (?\œóñÜ "tk;")
	     (?\œóñİ "g+-")
	     (?\œóñŞ "g+.")
	     (?\œóñß "g+,")
	     (?\œóñà "g+;")
	     (?\œóñá "hk-")
	     (?\œóñâ "hk.")
	     (?\œóñã "hk,")
	     (?\œóñä "hk;")
	     (?\œóñå "x+-")
	     (?\œóñæ "x+.")
	     (?\œóñç "x+,")
	     (?\œóñè "x+;")
	     (?\œóñé "d+-")
	     (?\œóñê "d+.")
	     (?\œóñë "dk-")
	     (?\œóñì "dk.")
	     (?\œóñí "r+-")
	     (?\œóñî "r+.")
	     (?\œóñï "z+-")
	     (?\œóñğ "z+.")
	     (?\œóññ "s+-")
	     (?\œóñò "s+.")
	     (?\œóñó "s+,")
	     (?\œóñô "s+;")
	     (?\œóñõ "sn-")
	     (?\œóñö "sn.")
	     (?\œóñ÷ "sn,")
	     (?\œóñø "sn;")
	     (?\œóñù "c+-")
	     (?\œóñú "c+.")
	     (?\œóñû "c+,")
	     (?\œóñü "c+;")
	     (?\œóñı "dd-")
	     (?\œóñş "dd.")
	     (?\œóñÿ "dd,")
	     (?\œóò  "dd;")
	     (?\œóò¡ "tj-")
	     (?\œóò¢ "tj.")
	     (?\œóò£ "tj,")
	     (?\œóò¤ "tj;")
	     (?\œóò¥ "zH-")
	     (?\œóò¦ "zH.")
	     (?\œóò§ "zH,")
	     (?\œóò¨ "zH;")
	     (?\œóò© "e+-")
	     (?\œóòª "e+.")
	     (?\œóò« "e+,")
	     (?\œóò¬ "e+;")
	     (?\œóò­ "i+-")
	     (?\œóò® "i+.")
	     (?\œóò¯ "i+,")
	     (?\œóò° "i+;")
	     (?\œóò± "f+-")
	     (?\œóò² "f+.")
	     (?\œóò³ "f+,")
	     (?\œóò´ "f+;")
	     (?\œóòµ "q+-")
	     (?\œóò¶ "q+.")
	     (?\œóò· "q+,")
	     (?\œóò¸ "q+;")
	     (?\œóò¹ "k+-")
	     (?\œóòº "k+.")
	     (?\œóò» "k+,")
	     (?\œóò¼ "k+;")
	     (?\œóò½ "l+-")
	     (?\œóò¾ "l+.")
	     (?\œóò¿ "l+,")
	     (?\œóòÀ "l+;")
	     (?\œóòÁ "m+-")
	     (?\œóòÂ "m+.")
	     (?\œóòÃ "m+,")
	     (?\œóòÄ "m+;")
	     (?\œóòÅ "n+-")
	     (?\œóòÆ "n+.")
	     (?\œóòÇ "n+,")
	     (?\œóòÈ "n+;")
	     (?\œóòÉ "h+-")
	     (?\œóòÊ "h+.")
	     (?\œóòË "h+,")
	     (?\œóòÌ "h+;")
	     (?\œóòÍ "w+-")
	     (?\œóòÎ "w+.")
	     (?\œóòÏ "j+-")
	     (?\œóòĞ "j+.")
	     (?\œóòÑ "y+-")
	     (?\œóòÒ "y+.")
	     (?\œóòÓ "y+,")
	     (?\œóòÔ "y+;")
	     (?\œóòÕ "lM-")
	     (?\œóòÖ "lM.")
	     (?\œóò× "lH-")
	     (?\œóòØ "lH.")
	     (?\œóòÙ "lh-")
	     (?\œóòÚ "lh.")
	     (?\œóòÛ "la-")
	     (?\œóòÜ "la.")
	     (?\œóòá "!")
	     (?\œóòâ "\"")
	     (?\œóòã "#")
	     (?\œóòä "$")
	     (?\œóòå "%")
	     (?\œóòæ "&")
	     (?\œóòç "'")
	     (?\œóòè "(")
	     (?\œóòé ")")
	     (?\œóòê "*")
	     (?\œóòë "+")
	     (?\œóòì ",")
	     (?\œóòí "-")
	     (?\œóòî ".")
	     (?\œóòï "/")
	     (?\œóòğ "0")
	     (?\œóòñ "1")
	     (?\œóòò "2")
	     (?\œóòó "3")
	     (?\œóòô "4")
	     (?\œóòõ "5")
	     (?\œóòö "6")
	     (?\œóò÷ "7")
	     (?\œóòø "8")
	     (?\œóòù "9")
	     (?\œóòú ":")
	     (?\œóòû ";")
	     (?\œóòü "<")
	     (?\œóòı "=")
	     (?\œóòş ">")
	     (?\œóòÿ "?")
	     (?\œóó  "@")
	     (?\œóó¡ "A")
	     (?\œóó¢ "B")
	     (?\œóó£ "C")
	     (?\œóó¤ "D")
	     (?\œóó¥ "E")
	     (?\œóó¦ "F")
	     (?\œóó§ "G")
	     (?\œóó¨ "H")
	     (?\œóó© "I")
	     (?\œóóª "J")
	     (?\œóó« "K")
	     (?\œóó¬ "L")
	     (?\œóó­ "M")
	     (?\œóó® "N")
	     (?\œóó¯ "O")
	     (?\œóó° "P")
	     (?\œóó± "Q")
	     (?\œóó² "R")
	     (?\œóó³ "S")
	     (?\œóó´ "T")
	     (?\œóóµ "U")
	     (?\œóó¶ "V")
	     (?\œóó· "W")
	     (?\œóó¸ "X")
	     (?\œóó¹ "Y")
	     (?\œóóº "Z")
	     (?\œóó» "[")
	     (?\œóó¼ "\\")
	     (?\œóó½ "]")
	     (?\œóó¾ "^")
	     (?\œóó¿ "_")
	     (?\œóóÀ "`")
	     (?\œóóÁ "a")
	     (?\œóóÂ "b")
	     (?\œóóÃ "c")
	     (?\œóóÄ "d")
	     (?\œóóÅ "e")
	     (?\œóóÆ "f")
	     (?\œóóÇ "g")
	     (?\œóóÈ "h")
	     (?\œóóÉ "i")
	     (?\œóóÊ "j")
	     (?\œóóË "k")
	     (?\œóóÌ "l")
	     (?\œóóÍ "m")
	     (?\œóóÎ "n")
	     (?\œóóÏ "o")
	     (?\œóóĞ "p")
	     (?\œóóÑ "q")
	     (?\œóóÒ "r")
	     (?\œóóÓ "s")
	     (?\œóóÔ "t")
	     (?\œóóÕ "u")
	     (?\œóóÖ "v")
	     (?\œóó× "w")
	     (?\œóóØ "x")
	     (?\œóóÙ "y")
	     (?\œóóÚ "z")
	     (?\œóóÛ "{")
	     (?\œóóÜ "|")
	     (?\œóóİ "}")
	     (?\œóóŞ "~")
	     (?\œóóá ".")
	     (?\œóóâ "\"")
	     (?\œóóã "\"")
	     (?\œóóä ",")))))
    (aset standard-display-table
	  (make-char 'mule-unicode-0100-24ff) nil)
    (aset standard-display-table
	  (make-char 'mule-unicode-2500-33ff) nil)
    (aset standard-display-table
	  (make-char 'mule-unicode-e000-ffff) nil))
  (setq latin1-display-ucs-per-lynx (not latin1-display-ucs-per-lynx))
  (redraw-display))

(provide 'latin1-disp)

;;; latin1-disp.el ends here
