@c -*-texinfo-*-
@c This is part of the GNU Emacs Lisp Reference Manual.
@c Copyright (C) 1999, 2002--2026 Free Software Foundation, Inc.
@c See the file elisp.texi for copying conditions.

@c This node must have no pointers.

@node Antinews
@appendix Emacs 30 Antinews
@c Update the elisp.texi Antinews menu entry with the above version number.

For those users who live backwards in time, here is information about
downgrading to Emacs version 30.2.  We hope you will enjoy the greater
simplicity that results from the absence of many @w{Emacs
@value{EMACSVER}} features.

@itemize @bullet
@item
Lisp strings are now mutable.  You can use @code{aset} on unibyte
strings to replace single bytes by multibyte characters, and @code{aset}
on multibyte strings can replace any character by any other character,
regardless if they are ASCII or multibyte non-ASCII@.  We feel those
restrictions are un-Emacsy and get in the way of doing all kinds of
exciting things with strings.

@item
Buffers that are current to a non-main thread cannot be killed by other
threads.  We decided to get rid of the numerous complications which were
needed to allow killing such buffers.  If your program needs to kill
such buffers, you will need to use a disciplined approach of first
making some other buffer current to the thread.

@item
We removed the early detection of faces that inherit from themselves.
As you move back in time, Emacs Lisp programmers become more and more
proficient, so disallowing such tricks feels wrong.  Those who don't
know well enough what they are doing will be amply punished by having
their Lisp programs barf at display time or even wedge Emacs cold.

@item
Calling @code{debug} in batch mode now kills Emacs.  We decided that
there's no sense in continuing a batch session that entered the
debugger: who and how will debug it, anyway?

For the same reason, @kbd{C-c} in batch mode now always kills Emacs, it
never quits.

@item
The functions that access and manipulate error descriptors were deleted.
Functions like @code{error-type}, @code{error-slot-value} and others are
useless bloat, since Lisp programs can simply access the data structure
directly, as God intended!

@item
We removed @code{frame-initial-p}, as its job can easily be done by
testing several obscure variables and frame parameters.

@item
We've added the @code{redisplay-dont-pause} variable, so we could allow
interrupting a runaway redisplay cycle in one of the past versions of
Emacs.

@item
There's no longer a guarantee that all the digit characters will have
the @code{digit} (@code{?6}) category.  We feel that such silly
consistency robs Lisp programmers of too much fun, whereby they should
discover which digits have this category by trial-and-error.

For the same reason, not all characters belonging to the @code{symbol}
script will have the @code{symbol} (@code{?5}) category.

@item
Lisp programs can now easily delete that daemon frame by calling
@code{delete-frame}, as with any other frame.  We decided there's no
reason to make a special case for the daemon frames, especially as some
past Emacs version will remove the daemon feature entirely.

@item
Lisp files found on @code{load-path} are no longer cached.  We intend to
make the @code{load-path} list shorter and shorter as we move to
previous versions of Emacs, so caching files is an unnecessary
complication and bloat of precious memory.

@item
The annoying warning about the missing @code{lexical-binding} cookie
when loading Lisp files was removed.  This is one more step towards
eventual elimination of lexical binding from Emacs in one of the past
versions.

For the same reason, Lisp files loaded via the @option{-x} and
@option{--script} command-line options no longer use lexical binding by
default.

@item
To keep Emacs clean and elegant, we deleted the @code{setopt-local}
macro.  This was one more useless bloat, since it is easy to do the same
using @code{setq-local}, and avoids the annoying warnings about mismatch
between the value and expected type defined by @code{defcustom}.

@item
Pure storage is now part of Emacs, and is here to stay.  The function
@code{purecopy} really copies its argument to pure storage.  This is a
significant step towards making Emacs more memory-efficient on
yesterday's computers, and more generally towards using @code{unexec} as
the only way of dumping Emacs.

@item
The @code{cond*} macro was removed.  You can still use @code{pcase}
instead, but better start using the venerable @code{cond} exclusively,
as @code{pcase} and its ilk will disappear from Emacs in the near past.
No one should need these fancy and hard-to-read constructs with their
obscure semantics and myriads of backticks!  The original control-flow
special forms of the pristine Emacs Lisp are more than enough.

@item
Xref commands automatically suggest visiting a tags table.  This is to
enable symbol completion,and generally move towards removing all
backends except the @code{etags} one in some past Emacs version.

@item
Support for SHA-3 message digests was removed from the function
@code{secure-hash}.  We plan to continue removing algorithms from this
function, so as to keep Emacs as lean as possible.  Eventually, just one
kind of digest should be enough for everyone!

@item
We deleted unnecessary functions like @code{incf}, @code{decf},
@code{plusp}, @code{minusp}, @code{oddp}, and @code{evenp}.  Use the
corresponding functions from @file{cl-lib} or just write these trivial
functions when you need them.  For the same reason, @code{all},
@code{any}, @code{drop-while}, and @code{take-while} are also gone.

@item
As part of the ongoing quest for simplicity, many other functions and
variables have been eliminated.  Other functions and variables, that
were declared obsolete since Emacs 25, have been added back, in
preparation for releasing Emacs 25 in some distant past.
@end itemize
