#ifndef EMACS_IGC_TYPES_H
#define EMACS_IGC_TYPES_H

enum igc_obj_type
{
  IGC_OBJ_INVALID,
  IGC_OBJ_PAD,
  IGC_OBJ_FWD,
  IGC_OBJ_CONS,
  IGC_OBJ_SYMBOL,
  IGC_OBJ_INTERVAL,
  IGC_OBJ_STRING,
  IGC_OBJ_STRING_DATA,
  IGC_OBJ_VECTOR,
  IGC_OBJ_MARKER_VECTOR,
  IGC_OBJ_ITREE_TREE,
  IGC_OBJ_ITREE_NODE,
  IGC_OBJ_IMAGE,
  IGC_OBJ_IMAGE_CACHE,
  IGC_OBJ_FACE,
  IGC_OBJ_FACE_CACHE,
  IGC_OBJ_FLOAT,
  IGC_OBJ_BLV,
  IGC_OBJ_HANDLER,
  IGC_OBJ_BYTES,
  IGC_OBJ_BUILTIN_SYMBOL,
  IGC_OBJ_BUILTIN_THREAD,
  IGC_OBJ_BUILTIN_SUBR,
  IGC_OBJ_DUMPED_CODE_SPACE_MASKS,
  IGC_OBJ_DUMPED_BUFFER_TEXT,
  IGC_OBJ_DUMPED_BIGNUM_DATA,
  IGC_OBJ_DUMPED_BYTES,
#ifndef USE_EPHEMERON_POOL
  IGC_OBJ_WEAK_HASH_TABLE_WEAK_PART,
  IGC_OBJ_WEAK_HASH_TABLE_STRONG_PART,
#endif
#ifdef USE_EPHEMERON_POOL
  IGC_OBJ_PAIR_VECTOR,
  IGC_OBJ_WEAK_KEY_PAIR_VECTOR,
  IGC_OBJ_WEAK_VALUE_PAIR_VECTOR,
  IGC_OBJ_WEAK_OR_PAIR_VECTOR,
  IGC_OBJ_WEAK_AND_PAIR_VECTOR,
#endif
  IGC_OBJ_NUM_TYPES
};

enum
{
  IGC_HEADER_TAG_BITS = 2,
  IGC_HEADER_TYPE_BITS = 6,
  IGC_HEADER_HASH_BITS = 24,
#if INTPTR_MAX <= INT_MAX
  IGC_HEADER_NWORDS_BITS = 31,
#else
  IGC_HEADER_NWORDS_BITS = 32,
#endif
  IGC_HEADER_TAG_MASK = (1 << IGC_HEADER_TAG_BITS) - 1,
  IGC_HEADER_TYPE_MASK = (1 << IGC_HEADER_TYPE_BITS) - 1,
  IGC_HEADER_HASH_MASK = (1 << IGC_HEADER_HASH_BITS) - 1,

  IGC_HEADER_TAG_SHIFT = 0,
  IGC_HEADER_TYPE_SHIFT = IGC_HEADER_TAG_SHIFT + IGC_HEADER_TAG_BITS,
  IGC_HEADER_HASH_SHIFT
  = IGC_HEADER_TYPE_SHIFT + IGC_HEADER_TYPE_BITS,
  IGC_HEADER_NWORDS_SHIFT = 64 - IGC_HEADER_NWORDS_BITS,
};

static_assert (IGC_OBJ_NUM_TYPES - 1 < (1 << IGC_HEADER_TYPE_BITS));

enum igc_tag
{
  IGC_TAG_NULL = 0,   /* entire value must be 0 to avoid MPS issues */
  IGC_TAG_OBJ = 1,    /* IGC object */
  IGC_TAG_EXTHDR = 2, /* pointer to aligned external header */
};

union gc_header
{
#ifndef WORDS_BIGENDIAN
  struct
  {
    enum igc_tag tag : IGC_HEADER_TAG_BITS;
    enum igc_obj_type obj_type : IGC_HEADER_TYPE_BITS;
    size_t hash : IGC_HEADER_HASH_BITS;
# if INTPTR_MAX <= INT_MAX
    size_t tag2 : 1;
# endif
    size_t nwords : IGC_HEADER_NWORDS_BITS;
  } s;
#endif
  uint64_t v;
  GCALIGNED_UNION_MEMBER
};

#endif /* EMACS_IGC_TYPES_H */
