;;; AUTOGENERATED

(in-package :lem-base16-themes)

;; Scheme: apprentice
;; Scheme author: romainl

(define-base16-color-theme "apprentice"
  :base00 "#262626"
  :base01 "#303030"
  :base02 "#333333"
  :base03 "#6C6C6C"
  :base04 "#787878"
  :base05 "#BCBCBC"
  :base06 "#C9C9C9"
  :base07 "#FFFFFF"
  :base08 "#5F8787"
  :base09 "#FF8700"
  :base0A "#5F8787"
  :base0B "#87AF87"
  :base0C "#5F875F"
  :base0D "#FFFFAF"
  :base0E "#87AFD7"
  :base0F "#5F87AF")

;; Scheme: atelier-cave-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-cave-light"
  :base00 "#efecf4"
  :base01 "#e2dfe7"
  :base02 "#8b8792"
  :base03 "#7e7887"
  :base04 "#655f6d"
  :base05 "#585260"
  :base06 "#26232a"
  :base07 "#19171c"
  :base08 "#be4678"
  :base09 "#aa573c"
  :base0A "#a06e3b"
  :base0B "#2a9292"
  :base0C "#398bc6"
  :base0D "#576ddb"
  :base0E "#955ae7"
  :base0F "#bf40bf")

;; Scheme: atelier-cave
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-cave"
  :base00 "#19171c"
  :base01 "#26232a"
  :base02 "#585260"
  :base03 "#655f6d"
  :base04 "#7e7887"
  :base05 "#8b8792"
  :base06 "#e2dfe7"
  :base07 "#efecf4"
  :base08 "#be4678"
  :base09 "#aa573c"
  :base0A "#a06e3b"
  :base0B "#2a9292"
  :base0C "#398bc6"
  :base0D "#576ddb"
  :base0E "#955ae7"
  :base0F "#bf40bf")

;; Scheme: atelier-dune-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-dune-light"
  :base00 "#fefbec"
  :base01 "#e8e4cf"
  :base02 "#a6a28c"
  :base03 "#999580"
  :base04 "#7d7a68"
  :base05 "#6e6b5e"
  :base06 "#292824"
  :base07 "#20201d"
  :base08 "#d73737"
  :base09 "#b65611"
  :base0A "#ae9513"
  :base0B "#60ac39"
  :base0C "#1fad83"
  :base0D "#6684e1"
  :base0E "#b854d4"
  :base0F "#d43552")

;; Scheme: atelier-dune
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-dune"
  :base00 "#20201d"
  :base01 "#292824"
  :base02 "#6e6b5e"
  :base03 "#7d7a68"
  :base04 "#999580"
  :base05 "#a6a28c"
  :base06 "#e8e4cf"
  :base07 "#fefbec"
  :base08 "#d73737"
  :base09 "#b65611"
  :base0A "#ae9513"
  :base0B "#60ac39"
  :base0C "#1fad83"
  :base0D "#6684e1"
  :base0E "#b854d4"
  :base0F "#d43552")

;; Scheme: atelier-estuary-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-estuary-light"
  :base00 "#f4f3ec"
  :base01 "#e7e6df"
  :base02 "#929181"
  :base03 "#878573"
  :base04 "#6c6b5a"
  :base05 "#5f5e4e"
  :base06 "#302f27"
  :base07 "#22221b"
  :base08 "#ba6236"
  :base09 "#ae7313"
  :base0A "#a5980d"
  :base0B "#7d9726"
  :base0C "#5b9d48"
  :base0D "#36a166"
  :base0E "#5f9182"
  :base0F "#9d6c7c")

;; Scheme: atelier-estuary
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-estuary"
  :base00 "#22221b"
  :base01 "#302f27"
  :base02 "#5f5e4e"
  :base03 "#6c6b5a"
  :base04 "#878573"
  :base05 "#929181"
  :base06 "#e7e6df"
  :base07 "#f4f3ec"
  :base08 "#ba6236"
  :base09 "#ae7313"
  :base0A "#a5980d"
  :base0B "#7d9726"
  :base0C "#5b9d48"
  :base0D "#36a166"
  :base0E "#5f9182"
  :base0F "#9d6c7c")

;; Scheme: atelier-forest-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-forest-light"
  :base00 "#f1efee"
  :base01 "#e6e2e0"
  :base02 "#a8a19f"
  :base03 "#9c9491"
  :base04 "#766e6b"
  :base05 "#68615e"
  :base06 "#2c2421"
  :base07 "#1b1918"
  :base08 "#f22c40"
  :base09 "#df5320"
  :base0A "#c38418"
  :base0B "#7b9726"
  :base0C "#3d97b8"
  :base0D "#407ee7"
  :base0E "#6666ea"
  :base0F "#c33ff3")

;; Scheme: atelier-forest
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-forest"
  :base00 "#1b1918"
  :base01 "#2c2421"
  :base02 "#68615e"
  :base03 "#766e6b"
  :base04 "#9c9491"
  :base05 "#a8a19f"
  :base06 "#e6e2e0"
  :base07 "#f1efee"
  :base08 "#f22c40"
  :base09 "#df5320"
  :base0A "#c38418"
  :base0B "#7b9726"
  :base0C "#3d97b8"
  :base0D "#407ee7"
  :base0E "#6666ea"
  :base0F "#c33ff3")

;; Scheme: atelier-heath-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-heath-light"
  :base00 "#f7f3f7"
  :base01 "#d8cad8"
  :base02 "#ab9bab"
  :base03 "#9e8f9e"
  :base04 "#776977"
  :base05 "#695d69"
  :base06 "#292329"
  :base07 "#1b181b"
  :base08 "#ca402b"
  :base09 "#a65926"
  :base0A "#bb8a35"
  :base0B "#918b3b"
  :base0C "#159393"
  :base0D "#516aec"
  :base0E "#7b59c0"
  :base0F "#cc33cc")

;; Scheme: atelier-heath
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-heath"
  :base00 "#1b181b"
  :base01 "#292329"
  :base02 "#695d69"
  :base03 "#776977"
  :base04 "#9e8f9e"
  :base05 "#ab9bab"
  :base06 "#d8cad8"
  :base07 "#f7f3f7"
  :base08 "#ca402b"
  :base09 "#a65926"
  :base0A "#bb8a35"
  :base0B "#918b3b"
  :base0C "#159393"
  :base0D "#516aec"
  :base0E "#7b59c0"
  :base0F "#cc33cc")

;; Scheme: atelier-lakeside-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-lakeside-light"
  :base00 "#ebf8ff"
  :base01 "#c1e4f6"
  :base02 "#7ea2b4"
  :base03 "#7195a8"
  :base04 "#5a7b8c"
  :base05 "#516d7b"
  :base06 "#1f292e"
  :base07 "#161b1d"
  :base08 "#d22d72"
  :base09 "#935c25"
  :base0A "#8a8a0f"
  :base0B "#568c3b"
  :base0C "#2d8f6f"
  :base0D "#257fad"
  :base0E "#6b6bb8"
  :base0F "#b72dd2")

;; Scheme: atelier-lakeside
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-lakeside"
  :base00 "#161b1d"
  :base01 "#1f292e"
  :base02 "#516d7b"
  :base03 "#5a7b8c"
  :base04 "#7195a8"
  :base05 "#7ea2b4"
  :base06 "#c1e4f6"
  :base07 "#ebf8ff"
  :base08 "#d22d72"
  :base09 "#935c25"
  :base0A "#8a8a0f"
  :base0B "#568c3b"
  :base0C "#2d8f6f"
  :base0D "#257fad"
  :base0E "#6b6bb8"
  :base0F "#b72dd2")

;; Scheme: atelier-plateau-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-plateau-light"
  :base00 "#f4ecec"
  :base01 "#e7dfdf"
  :base02 "#8a8585"
  :base03 "#7e7777"
  :base04 "#655d5d"
  :base05 "#585050"
  :base06 "#292424"
  :base07 "#1b1818"
  :base08 "#ca4949"
  :base09 "#b45a3c"
  :base0A "#a06e3b"
  :base0B "#4b8b8b"
  :base0C "#5485b6"
  :base0D "#7272ca"
  :base0E "#8464c4"
  :base0F "#bd5187")

;; Scheme: atelier-plateau
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-plateau"
  :base00 "#1b1818"
  :base01 "#292424"
  :base02 "#585050"
  :base03 "#655d5d"
  :base04 "#7e7777"
  :base05 "#8a8585"
  :base06 "#e7dfdf"
  :base07 "#f4ecec"
  :base08 "#ca4949"
  :base09 "#b45a3c"
  :base0A "#a06e3b"
  :base0B "#4b8b8b"
  :base0C "#5485b6"
  :base0D "#7272ca"
  :base0E "#8464c4"
  :base0F "#bd5187")

;; Scheme: atelier-savanna-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-savanna-light"
  :base00 "#ecf4ee"
  :base01 "#dfe7e2"
  :base02 "#87928a"
  :base03 "#78877d"
  :base04 "#5f6d64"
  :base05 "#526057"
  :base06 "#232a25"
  :base07 "#171c19"
  :base08 "#b16139"
  :base09 "#9f713c"
  :base0A "#a07e3b"
  :base0B "#489963"
  :base0C "#1c9aa0"
  :base0D "#478c90"
  :base0E "#55859b"
  :base0F "#867469")

;; Scheme: atelier-savanna
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-savanna"
  :base00 "#171c19"
  :base01 "#232a25"
  :base02 "#526057"
  :base03 "#5f6d64"
  :base04 "#78877d"
  :base05 "#87928a"
  :base06 "#dfe7e2"
  :base07 "#ecf4ee"
  :base08 "#b16139"
  :base09 "#9f713c"
  :base0A "#a07e3b"
  :base0B "#489963"
  :base0C "#1c9aa0"
  :base0D "#478c90"
  :base0E "#55859b"
  :base0F "#867469")

;; Scheme: atelier-seaside-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-seaside-light"
  :base00 "#f4fbf4"
  :base01 "#cfe8cf"
  :base02 "#8ca68c"
  :base03 "#809980"
  :base04 "#687d68"
  :base05 "#5e6e5e"
  :base06 "#242924"
  :base07 "#131513"
  :base08 "#e6193c"
  :base09 "#87711d"
  :base0A "#98981b"
  :base0B "#29a329"
  :base0C "#1999b3"
  :base0D "#3d62f5"
  :base0E "#ad2bee"
  :base0F "#e619c3")

;; Scheme: atelier-seaside
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-seaside"
  :base00 "#131513"
  :base01 "#242924"
  :base02 "#5e6e5e"
  :base03 "#687d68"
  :base04 "#809980"
  :base05 "#8ca68c"
  :base06 "#cfe8cf"
  :base07 "#f4fbf4"
  :base08 "#e6193c"
  :base09 "#87711d"
  :base0A "#98981b"
  :base0B "#29a329"
  :base0C "#1999b3"
  :base0D "#3d62f5"
  :base0E "#ad2bee"
  :base0F "#e619c3")

;; Scheme: atelier-sulphurpool-light
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-sulphurpool-light"
  :base00 "#f5f7ff"
  :base01 "#dfe2f1"
  :base02 "#979db4"
  :base03 "#898ea4"
  :base04 "#6b7394"
  :base05 "#5e6687"
  :base06 "#293256"
  :base07 "#202746"
  :base08 "#c94922"
  :base09 "#c76b29"
  :base0A "#c08b30"
  :base0B "#ac9739"
  :base0C "#22a2c9"
  :base0D "#3d8fd1"
  :base0E "#6679cc"
  :base0F "#9c637a")

;; Scheme: atelier-sulphurpool
;; Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

(define-base16-color-theme "atelier-sulphurpool"
  :base00 "#202746"
  :base01 "#293256"
  :base02 "#5e6687"
  :base03 "#6b7394"
  :base04 "#898ea4"
  :base05 "#979db4"
  :base06 "#dfe2f1"
  :base07 "#f5f7ff"
  :base08 "#c94922"
  :base09 "#c76b29"
  :base0A "#c08b30"
  :base0B "#ac9739"
  :base0C "#22a2c9"
  :base0D "#3d8fd1"
  :base0E "#6679cc"
  :base0F "#9c637a")

;; Scheme: atlas
;; Scheme author: Alex Lende (https://ajlende.com)

(define-base16-color-theme "atlas"
  :base00 "#002635"
  :base01 "#00384d"
  :base02 "#517F8D"
  :base03 "#6C8B91"
  :base04 "#869696"
  :base05 "#a1a19a"
  :base06 "#e6e6dc"
  :base07 "#fafaf8"
  :base08 "#ff5a67"
  :base09 "#f08e48"
  :base0A "#ffcc1b"
  :base0B "#7fc06e"
  :base0C "#14747e"
  :base0D "#5dd7b9"
  :base0E "#9a70a4"
  :base0F "#c43060")

;; Scheme: black-metal-bathory
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-bathory"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#e78a53"
  :base0B "#fbcb97"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-burzum
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-burzum"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#99bbaa"
  :base0B "#ddeecc"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-dark-funeral
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-dark-funeral"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#5f81a5"
  :base0B "#d0dfee"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-gorgoroth
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-gorgoroth"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#8c7f70"
  :base0B "#9b8d7f"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-immortal
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-immortal"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#556677"
  :base0B "#7799bb"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-khold
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-khold"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#974b46"
  :base0B "#eceee3"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-marduk
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-marduk"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#626b67"
  :base0B "#a5aaa7"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-mayhem
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-mayhem"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#eecc6c"
  :base0B "#f3ecd4"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-nile
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-nile"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#777755"
  :base0B "#aa9988"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal-venom
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal-venom"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#79241f"
  :base0B "#f8f7f2"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: black-metal
;; Scheme author: metalelf0 (https://github.com/metalelf0)

(define-base16-color-theme "black-metal"
  :base00 "#000000"
  :base01 "#121212"
  :base02 "#222222"
  :base03 "#333333"
  :base04 "#999999"
  :base05 "#c1c1c1"
  :base06 "#999999"
  :base07 "#c1c1c1"
  :base08 "#5f8787"
  :base09 "#aaaaaa"
  :base0A "#a06666"
  :base0B "#dd9999"
  :base0C "#aaaaaa"
  :base0D "#888888"
  :base0E "#999999"
  :base0F "#444444")

;; Scheme: brogrammer
;; Scheme author: Vik Ramanujam (http://github.com/piggyslasher)

(define-base16-color-theme "brogrammer"
  :base00 "#1f1f1f"
  :base01 "#f81118"
  :base02 "#2dc55e"
  :base03 "#ecba0f"
  :base04 "#2a84d2"
  :base05 "#4e5ab7"
  :base06 "#1081d6"
  :base07 "#d6dbe5"
  :base08 "#d6dbe5"
  :base09 "#de352e"
  :base0A "#1dd361"
  :base0B "#f3bd09"
  :base0C "#1081d6"
  :base0D "#5350b9"
  :base0E "#0f7ddb"
  :base0F "#ffffff")

;; Scheme: brushtrees-dark
;; Scheme author: Abraham White &lt;abelincoln.white@gmail.com&gt;

(define-base16-color-theme "brushtrees-dark"
  :base00 "#485867"
  :base01 "#5A6D7A"
  :base02 "#6D828E"
  :base03 "#8299A1"
  :base04 "#98AFB5"
  :base05 "#B0C5C8"
  :base06 "#C9DBDC"
  :base07 "#E3EFEF"
  :base08 "#b38686"
  :base09 "#d8bba2"
  :base0A "#aab386"
  :base0B "#87b386"
  :base0C "#86b3b3"
  :base0D "#868cb3"
  :base0E "#b386b2"
  :base0F "#b39f9f")

;; Scheme: brushtrees
;; Scheme author: Abraham White &lt;abelincoln.white@gmail.com&gt;

(define-base16-color-theme "brushtrees"
  :base00 "#E3EFEF"
  :base01 "#C9DBDC"
  :base02 "#B0C5C8"
  :base03 "#98AFB5"
  :base04 "#8299A1"
  :base05 "#6D828E"
  :base06 "#5A6D7A"
  :base07 "#485867"
  :base08 "#b38686"
  :base09 "#d8bba2"
  :base0A "#aab386"
  :base0B "#87b386"
  :base0C "#86b3b3"
  :base0D "#868cb3"
  :base0E "#b386b2"
  :base0F "#b39f9f")

;; Scheme: circus
;; Scheme author: Stephan Boyer (https://github.com/stepchowfun) and Esther Wang (https://github.com/ewang12)

(define-base16-color-theme "circus"
  :base00 "#191919"
  :base01 "#202020"
  :base02 "#303030"
  :base03 "#5f5a60"
  :base04 "#505050"
  :base05 "#a7a7a7"
  :base06 "#808080"
  :base07 "#ffffff"
  :base08 "#dc657d"
  :base09 "#4bb1a7"
  :base0A "#c3ba63"
  :base0B "#84b97c"
  :base0C "#4bb1a7"
  :base0D "#639ee4"
  :base0E "#b888e2"
  :base0F "#b888e2")

;; Scheme: classic-dark
;; Scheme author: Jason Heeris (http://heeris.id.au)

(define-base16-color-theme "classic-dark"
  :base00 "#151515"
  :base01 "#202020"
  :base02 "#303030"
  :base03 "#505050"
  :base04 "#B0B0B0"
  :base05 "#D0D0D0"
  :base06 "#E0E0E0"
  :base07 "#F5F5F5"
  :base08 "#AC4142"
  :base09 "#D28445"
  :base0A "#F4BF75"
  :base0B "#90A959"
  :base0C "#75B5AA"
  :base0D "#6A9FB5"
  :base0E "#AA759F"
  :base0F "#8F5536")

;; Scheme: classic-light
;; Scheme author: Jason Heeris (http://heeris.id.au)

(define-base16-color-theme "classic-light"
  :base00 "#F5F5F5"
  :base01 "#E0E0E0"
  :base02 "#D0D0D0"
  :base03 "#B0B0B0"
  :base04 "#505050"
  :base05 "#303030"
  :base06 "#202020"
  :base07 "#151515"
  :base08 "#AC4142"
  :base09 "#D28445"
  :base0A "#F4BF75"
  :base0B "#90A959"
  :base0C "#75B5AA"
  :base0D "#6A9FB5"
  :base0E "#AA759F"
  :base0F "#8F5536")

;; Scheme: codeschool
;; Scheme author: blockloop

(define-base16-color-theme "codeschool"
  :base00 "#232c31"
  :base01 "#1c3657"
  :base02 "#2a343a"
  :base03 "#3f4944"
  :base04 "#84898c"
  :base05 "#9ea7a6"
  :base06 "#a7cfa3"
  :base07 "#b5d8f6"
  :base08 "#2a5491"
  :base09 "#43820d"
  :base0A "#a03b1e"
  :base0B "#237986"
  :base0C "#b02f30"
  :base0D "#484d79"
  :base0E "#c59820"
  :base0F "#c98344")

;; Scheme: colors
;; Scheme author: mrmrs (http://clrs.cc)

(define-base16-color-theme "colors"
  :base00 "#111111"
  :base01 "#333333"
  :base02 "#555555"
  :base03 "#777777"
  :base04 "#999999"
  :base05 "#bbbbbb"
  :base06 "#dddddd"
  :base07 "#ffffff"
  :base08 "#ff4136"
  :base09 "#ff851b"
  :base0A "#ffdc00"
  :base0B "#2ecc40"
  :base0C "#7fdbff"
  :base0D "#0074d9"
  :base0E "#b10dc9"
  :base0F "#85144b")

;; Scheme: cupertino
;; Scheme author: Defman21

(define-base16-color-theme "cupertino"
  :base00 "#ffffff"
  :base01 "#c0c0c0"
  :base02 "#c0c0c0"
  :base03 "#808080"
  :base04 "#808080"
  :base05 "#404040"
  :base06 "#404040"
  :base07 "#5e5e5e"
  :base08 "#c41a15"
  :base09 "#eb8500"
  :base0A "#826b28"
  :base0B "#007400"
  :base0C "#318495"
  :base0D "#0000ff"
  :base0E "#a90d91"
  :base0F "#826b28")

;; Scheme: danqing-light
;; Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)

(define-base16-color-theme "danqing-light"
  :base00 "#fcfefd"
  :base01 "#ecf6f2"
  :base02 "#e0f0eF"
  :base03 "#cad8d2"
  :base04 "#9da8a3"
  :base05 "#5a605d"
  :base06 "#434846"
  :base07 "#2d302f"
  :base08 "#F9906F"
  :base09 "#B38A61"
  :base0A "#F0C239"
  :base0B "#8AB361"
  :base0C "#30DFF3"
  :base0D "#B0A4E3"
  :base0E "#CCA4E3"
  :base0F "#CA6924")

;; Scheme: danqing
;; Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)

(define-base16-color-theme "danqing"
  :base00 "#2d302f"
  :base01 "#434846"
  :base02 "#5a605d"
  :base03 "#9da8a3"
  :base04 "#cad8d2"
  :base05 "#e0f0eF"
  :base06 "#ecf6f2"
  :base07 "#fcfefd"
  :base08 "#F9906F"
  :base09 "#B38A61"
  :base0A "#F0C239"
  :base0B "#8AB361"
  :base0C "#30DFF3"
  :base0D "#B0A4E3"
  :base0E "#CCA4E3"
  :base0F "#CA6924")

;; Scheme: darcula
;; Scheme author: jetbrains

(define-base16-color-theme "darcula"
  :base00 "#2b2b2b"
  :base01 "#323232"
  :base02 "#323232"
  :base03 "#606366"
  :base04 "#a4a3a3"
  :base05 "#a9b7c6"
  :base06 "#ffc66d"
  :base07 "#ffffff"
  :base08 "#4eade5"
  :base09 "#689757"
  :base0A "#bbb529"
  :base0B "#6a8759"
  :base0C "#629755"
  :base0D "#9876aa"
  :base0E "#cc7832"
  :base0F "#808080")

;; Scheme: darkmoss
;; Scheme author: Gabriel Avanzi (https://github.com/avanzzzi)

(define-base16-color-theme "darkmoss"
  :base00 "#171e1f"
  :base01 "#252c2d"
  :base02 "#373c3d"
  :base03 "#555e5f"
  :base04 "#818f80"
  :base05 "#c7c7a5"
  :base06 "#e3e3c8"
  :base07 "#e1eaef"
  :base08 "#ff4658"
  :base09 "#e6db74"
  :base0A "#fdb11f"
  :base0B "#499180"
  :base0C "#66d9ef"
  :base0D "#498091"
  :base0E "#9bc0c8"
  :base0F "#d27b53")

;; Scheme: darkviolet
;; Scheme author: ruler501 (https://github.com/ruler501/base16-darkviolet)

(define-base16-color-theme "darkviolet"
  :base00 "#000000"
  :base01 "#231a40"
  :base02 "#432d59"
  :base03 "#593380"
  :base04 "#00ff00"
  :base05 "#b08ae6"
  :base06 "#9045e6"
  :base07 "#a366ff"
  :base08 "#a82ee6"
  :base09 "#bb66cc"
  :base0A "#f29df2"
  :base0B "#4595e6"
  :base0C "#40dfff"
  :base0D "#4136d9"
  :base0E "#7e5ce6"
  :base0F "#a886bf")

;; Scheme: cupcake
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "cupcake"
  :base00 "#fbf1f2"
  :base01 "#f2f1f4"
  :base02 "#d8d5dd"
  :base03 "#bfb9c6"
  :base04 "#a59daf"
  :base05 "#8b8198"
  :base06 "#72677E"
  :base07 "#585062"
  :base08 "#D57E85"
  :base09 "#EBB790"
  :base0A "#DCB16C"
  :base0B "#A3B367"
  :base0C "#69A9A7"
  :base0D "#7297B9"
  :base0E "#BB99B4"
  :base0F "#BAA58C")

;; Scheme: default-dark
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "default-dark"
  :base00 "#181818"
  :base01 "#282828"
  :base02 "#383838"
  :base03 "#585858"
  :base04 "#b8b8b8"
  :base05 "#d8d8d8"
  :base06 "#e8e8e8"
  :base07 "#f8f8f8"
  :base08 "#ab4642"
  :base09 "#dc9656"
  :base0A "#f7ca88"
  :base0B "#a1b56c"
  :base0C "#86c1b9"
  :base0D "#7cafc2"
  :base0E "#ba8baf"
  :base0F "#a16946")

;; Scheme: default-light
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "default-light"
  :base00 "#f8f8f8"
  :base01 "#e8e8e8"
  :base02 "#d8d8d8"
  :base03 "#b8b8b8"
  :base04 "#585858"
  :base05 "#383838"
  :base06 "#282828"
  :base07 "#181818"
  :base08 "#ab4642"
  :base09 "#dc9656"
  :base0A "#f7ca88"
  :base0B "#a1b56c"
  :base0C "#86c1b9"
  :base0D "#7cafc2"
  :base0E "#ba8baf"
  :base0F "#a16946")

;; Scheme: eighties
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "eighties"
  :base00 "#2d2d2d"
  :base01 "#393939"
  :base02 "#515151"
  :base03 "#747369"
  :base04 "#a09f93"
  :base05 "#d3d0c8"
  :base06 "#e8e6df"
  :base07 "#f2f0ec"
  :base08 "#f2777a"
  :base09 "#f99157"
  :base0A "#ffcc66"
  :base0B "#99cc99"
  :base0C "#66cccc"
  :base0D "#6699cc"
  :base0E "#cc99cc"
  :base0F "#d27b53")

;; Scheme: mocha
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "mocha"
  :base00 "#3B3228"
  :base01 "#534636"
  :base02 "#645240"
  :base03 "#7e705a"
  :base04 "#b8afad"
  :base05 "#d0c8c6"
  :base06 "#e9e1dd"
  :base07 "#f5eeeb"
  :base08 "#cb6077"
  :base09 "#d28b71"
  :base0A "#f4bc87"
  :base0B "#beb55b"
  :base0C "#7bbda4"
  :base0D "#8ab3b5"
  :base0E "#a89bb9"
  :base0F "#bb9584")

;; Scheme: ocean
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "ocean"
  :base00 "#2b303b"
  :base01 "#343d46"
  :base02 "#4f5b66"
  :base03 "#65737e"
  :base04 "#a7adba"
  :base05 "#c0c5ce"
  :base06 "#dfe1e8"
  :base07 "#eff1f5"
  :base08 "#bf616a"
  :base09 "#d08770"
  :base0A "#ebcb8b"
  :base0B "#a3be8c"
  :base0C "#96b5b4"
  :base0D "#8fa1b3"
  :base0E "#b48ead"
  :base0F "#ab7967")

;; Scheme: dirtysea
;; Scheme author: Kahlil (Kal) Hodgson

(define-base16-color-theme "dirtysea"
  :base00 "#e0e0e0"
  :base01 "#d0dad0"
  :base02 "#d0d0d0"
  :base03 "#707070"
  :base04 "#202020"
  :base05 "#000000"
  :base06 "#f8f8f8"
  :base07 "#c4d9c4"
  :base08 "#840000"
  :base09 "#006565"
  :base0A "#755B00"
  :base0B "#730073"
  :base0C "#755B00"
  :base0D "#007300"
  :base0E "#000090"
  :base0F "#755B00")

;; Scheme: dracula
;; Scheme author: Mike Barkmin (http://github.com/mikebarkmin) based on Dracula Theme (http://github.com/dracula)

(define-base16-color-theme "dracula"
  :base00 "#282936"
  :base01 "#3a3c4e"
  :base02 "#4d4f68"
  :base03 "#626483"
  :base04 "#62d6e8"
  :base05 "#e9e9f4"
  :base06 "#f1f2f8"
  :base07 "#f7f7fb"
  :base08 "#ea51b2"
  :base09 "#b45bcf"
  :base0A "#00f769"
  :base0B "#ebff87"
  :base0C "#a1efe4"
  :base0D "#62d6e8"
  :base0E "#b45bcf"
  :base0F "#00f769")

;; Scheme: edge-dark
;; Scheme author: cjayross (https://github.com/cjayross)

(define-base16-color-theme "edge-dark"
  :base00 "#262729"
  :base01 "#88909f"
  :base02 "#b7bec9"
  :base03 "#3e4249"
  :base04 "#73b3e7"
  :base05 "#b7bec9"
  :base06 "#d390e7"
  :base07 "#3e4249"
  :base08 "#e77171"
  :base09 "#e77171"
  :base0A "#dbb774"
  :base0B "#a1bf78"
  :base0C "#5ebaa5"
  :base0D "#73b3e7"
  :base0E "#d390e7"
  :base0F "#5ebaa5")

;; Scheme: edge-light
;; Scheme author: cjayross (https://github.com/cjayross)

(define-base16-color-theme "edge-light"
  :base00 "#fafafa"
  :base01 "#7c9f4b"
  :base02 "#d69822"
  :base03 "#5e646f"
  :base04 "#6587bf"
  :base05 "#5e646f"
  :base06 "#b870ce"
  :base07 "#5e646f"
  :base08 "#db7070"
  :base09 "#db7070"
  :base0A "#d69822"
  :base0B "#7c9f4b"
  :base0C "#509c93"
  :base0D "#6587bf"
  :base0E "#b870ce"
  :base0F "#509c93")

;; Scheme: equilibrium-dark
;; Scheme author: Carlo Abelli

(define-base16-color-theme "equilibrium-dark"
  :base00 "#0c1118"
  :base01 "#181c22"
  :base02 "#22262d"
  :base03 "#7b776e"
  :base04 "#949088"
  :base05 "#afaba2"
  :base06 "#cac6bd"
  :base07 "#e7e2d9"
  :base08 "#f04339"
  :base09 "#df5923"
  :base0A "#bb8801"
  :base0B "#7f8b00"
  :base0C "#00948b"
  :base0D "#008dd1"
  :base0E "#6a7fd2"
  :base0F "#e3488e")

;; Scheme: equilibrium-gray-dark
;; Scheme author: Carlo Abelli

(define-base16-color-theme "equilibrium-gray-dark"
  :base00 "#111111"
  :base01 "#1b1b1b"
  :base02 "#262626"
  :base03 "#777777"
  :base04 "#919191"
  :base05 "#ababab"
  :base06 "#c6c6c6"
  :base07 "#e2e2e2"
  :base08 "#f04339"
  :base09 "#df5923"
  :base0A "#bb8801"
  :base0B "#7f8b00"
  :base0C "#00948b"
  :base0D "#008dd1"
  :base0E "#6a7fd2"
  :base0F "#e3488e")

;; Scheme: equilibrium-gray-light
;; Scheme author: Carlo Abelli

(define-base16-color-theme "equilibrium-gray-light"
  :base00 "#f1f1f1"
  :base01 "#e2e2e2"
  :base02 "#d4d4d4"
  :base03 "#777777"
  :base04 "#5e5e5e"
  :base05 "#474747"
  :base06 "#303030"
  :base07 "#1b1b1b"
  :base08 "#d02023"
  :base09 "#bf3e05"
  :base0A "#9d6f00"
  :base0B "#637200"
  :base0C "#007a72"
  :base0D "#0073b5"
  :base0E "#4e66b6"
  :base0F "#c42775")

;; Scheme: equilibrium-light
;; Scheme author: Carlo Abelli

(define-base16-color-theme "equilibrium-light"
  :base00 "#f5f0e7"
  :base01 "#e7e2d9"
  :base02 "#d8d4cb"
  :base03 "#73777f"
  :base04 "#5a5f66"
  :base05 "#43474e"
  :base06 "#2c3138"
  :base07 "#181c22"
  :base08 "#d02023"
  :base09 "#bf3e05"
  :base0A "#9d6f00"
  :base0B "#637200"
  :base0C "#007a72"
  :base0D "#0073b5"
  :base0E "#4e66b6"
  :base0F "#c42775")

;; Scheme: decaf
;; Scheme author: Alex Mirrington (https://github.com/alexmirrington)

(define-base16-color-theme "decaf"
  :base00 "#2d2d2d"
  :base01 "#393939"
  :base02 "#515151"
  :base03 "#777777"
  :base04 "#b4b7b4"
  :base05 "#cccccc"
  :base06 "#e0e0e0"
  :base07 "#ffffff"
  :base08 "#ff7f7b"
  :base09 "#ffbf70"
  :base0A "#ffd67c"
  :base0B "#beda78"
  :base0C "#bed6ff"
  :base0D "#90bee1"
  :base0E "#efb3f7"
  :base0F "#ff93b3")

;; Scheme: espresso
;; Scheme author: Unknown. Maintained by Alex Mirrington (https://github.com/alexmirrington)

(define-base16-color-theme "espresso"
  :base00 "#2d2d2d"
  :base01 "#393939"
  :base02 "#515151"
  :base03 "#777777"
  :base04 "#b4b7b4"
  :base05 "#cccccc"
  :base06 "#e0e0e0"
  :base07 "#ffffff"
  :base08 "#d25252"
  :base09 "#f9a959"
  :base0A "#ffc66d"
  :base0B "#a5c261"
  :base0C "#bed6ff"
  :base0D "#6c99bb"
  :base0E "#d197d9"
  :base0F "#f97394")

;; Scheme: eva-dim
;; Scheme author: kjakapat (https://github.com/kjakapat)

(define-base16-color-theme "eva-dim"
  :base00 "#2a3b4d"
  :base01 "#3d566f"
  :base02 "#4b6988"
  :base03 "#55799c"
  :base04 "#7e90a3"
  :base05 "#9fa2a6"
  :base06 "#d6d7d9"
  :base07 "#ffffff"
  :base08 "#c4676c"
  :base09 "#ff9966"
  :base0A "#cfd05d"
  :base0B "#5de561"
  :base0C "#4b8f77"
  :base0D "#1ae1dc"
  :base0E "#9c6cd3"
  :base0F "#bb64a9")

;; Scheme: eva
;; Scheme author: kjakapat (https://github.com/kjakapat)

(define-base16-color-theme "eva"
  :base00 "#2a3b4d"
  :base01 "#3d566f"
  :base02 "#4b6988"
  :base03 "#55799c"
  :base04 "#7e90a3"
  :base05 "#9fa2a6"
  :base06 "#d6d7d9"
  :base07 "#ffffff"
  :base08 "#c4676c"
  :base09 "#ff9966"
  :base0A "#ffff66"
  :base0B "#66ff66"
  :base0C "#4b8f77"
  :base0D "#15f4ee"
  :base0E "#9c6cd3"
  :base0F "#bb64a9")

;; Scheme: everforest-dark
;; Scheme author: Sainnhe Park (sainnhe@gmail.com)

(define-base16-color-theme "everforest-dark"
  :base00 "#2b3339"
  :base01 "#323c41"
  :base02 "#383f45"
  :base03 "#868d80"
  :base04 "#d3c6aa"
  :base05 "#d3c6aa"
  :base06 "#e9e8d2"
  :base07 "#fff9e8"
  :base08 "#7fbbb3"
  :base09 "#d699b6"
  :base0A "#83c092"
  :base0B "#dbbc7f"
  :base0C "#e69875"
  :base0D "#a7c080"
  :base0E "#e67e80"
  :base0F "#d699b6")

;; Scheme: framer
;; Scheme author: Framer (Maintained by Jesse Hoyos)

(define-base16-color-theme "framer"
  :base00 "#181818"
  :base01 "#151515"
  :base02 "#464646"
  :base03 "#747474"
  :base04 "#B9B9B9"
  :base05 "#D0D0D0"
  :base06 "#E8E8E8"
  :base07 "#EEEEEE"
  :base08 "#FD886B"
  :base09 "#FC4769"
  :base0A "#FECB6E"
  :base0B "#32CCDC"
  :base0C "#ACDDFD"
  :base0D "#20BCFC"
  :base0E "#BA8CFC"
  :base0F "#B15F4A")

;; Scheme: fruit-soda
;; Scheme author: jozip

(define-base16-color-theme "fruit-soda"
  :base00 "#f1ecf1"
  :base01 "#e0dee0"
  :base02 "#d8d5d5"
  :base03 "#b5b4b6"
  :base04 "#979598"
  :base05 "#515151"
  :base06 "#474545"
  :base07 "#2d2c2c"
  :base08 "#fe3e31"
  :base09 "#fe6d08"
  :base0A "#f7e203"
  :base0B "#47f74c"
  :base0C "#0f9cfd"
  :base0D "#2931df"
  :base0E "#611fce"
  :base0F "#b16f40")

;; Scheme: gigavolt
;; Scheme author: Aidan Swope (http://github.com/Whillikers)

(define-base16-color-theme "gigavolt"
  :base00 "#202126"
  :base01 "#2d303d"
  :base02 "#5a576e"
  :base03 "#a1d2e6"
  :base04 "#cad3ff"
  :base05 "#e9e7e1"
  :base06 "#eff0f9"
  :base07 "#f2fbff"
  :base08 "#ff661a"
  :base09 "#19f988"
  :base0A "#ffdc2d"
  :base0B "#f2e6a9"
  :base0C "#fb6acb"
  :base0D "#40bfff"
  :base0E "#ae94f9"
  :base0F "#6187ff")

;; Scheme: github
;; Scheme author: Defman21

(define-base16-color-theme "github"
  :base00 "#ffffff"
  :base01 "#f5f5f5"
  :base02 "#c8c8fa"
  :base03 "#969896"
  :base04 "#e8e8e8"
  :base05 "#333333"
  :base06 "#ffffff"
  :base07 "#ffffff"
  :base08 "#ed6a43"
  :base09 "#0086b3"
  :base0A "#795da3"
  :base0B "#183691"
  :base0C "#183691"
  :base0D "#795da3"
  :base0E "#a71d5d"
  :base0F "#333333")

;; Scheme: gruber
;; Scheme author: Patel, Nimai &lt;nimai.m.patel@gmail.com&gt;, colors from www.github.com/rexim/gruber-darker-theme

(define-base16-color-theme "gruber"
  :base00 "#181818"
  :base01 "#453d41"
  :base02 "#665c7f"
  :base03 "#9dae93"
  :base04 "#e4e4ef"
  :base05 "#f4f4ff"
  :base06 "#f5f5f5"
  :base07 "#e4e4ef"
  :base08 "#f43841"
  :base09 "#c73c3f"
  :base0A "#ffdd33"
  :base0B "#73c936"
  :base0C "#95a99f"
  :base0D "#96a6c8"
  :base0E "#9e95c7"
  :base0F "#cc8c3c")

;; Scheme: gruvbox-dark-hard
;; Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

(define-base16-color-theme "gruvbox-dark-hard"
  :base00 "#1d2021"
  :base01 "#3c3836"
  :base02 "#504945"
  :base03 "#665c54"
  :base04 "#bdae93"
  :base05 "#d5c4a1"
  :base06 "#ebdbb2"
  :base07 "#fbf1c7"
  :base08 "#fb4934"
  :base09 "#fe8019"
  :base0A "#fabd2f"
  :base0B "#b8bb26"
  :base0C "#8ec07c"
  :base0D "#83a598"
  :base0E "#d3869b"
  :base0F "#d65d0e")

;; Scheme: gruvbox-dark-medium
;; Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

(define-base16-color-theme "gruvbox-dark-medium"
  :base00 "#282828"
  :base01 "#3c3836"
  :base02 "#504945"
  :base03 "#665c54"
  :base04 "#bdae93"
  :base05 "#d5c4a1"
  :base06 "#ebdbb2"
  :base07 "#fbf1c7"
  :base08 "#fb4934"
  :base09 "#fe8019"
  :base0A "#fabd2f"
  :base0B "#b8bb26"
  :base0C "#8ec07c"
  :base0D "#83a598"
  :base0E "#d3869b"
  :base0F "#d65d0e")

;; Scheme: gruvbox-dark-pale
;; Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

(define-base16-color-theme "gruvbox-dark-pale"
  :base00 "#262626"
  :base01 "#3a3a3a"
  :base02 "#4e4e4e"
  :base03 "#8a8a8a"
  :base04 "#949494"
  :base05 "#dab997"
  :base06 "#d5c4a1"
  :base07 "#ebdbb2"
  :base08 "#d75f5f"
  :base09 "#ff8700"
  :base0A "#ffaf00"
  :base0B "#afaf00"
  :base0C "#85ad85"
  :base0D "#83adad"
  :base0E "#d485ad"
  :base0F "#d65d0e")

;; Scheme: gruvbox-dark-soft
;; Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

(define-base16-color-theme "gruvbox-dark-soft"
  :base00 "#32302f"
  :base01 "#3c3836"
  :base02 "#504945"
  :base03 "#665c54"
  :base04 "#bdae93"
  :base05 "#d5c4a1"
  :base06 "#ebdbb2"
  :base07 "#fbf1c7"
  :base08 "#fb4934"
  :base09 "#fe8019"
  :base0A "#fabd2f"
  :base0B "#b8bb26"
  :base0C "#8ec07c"
  :base0D "#83a598"
  :base0E "#d3869b"
  :base0F "#d65d0e")

;; Scheme: gruvbox-light-hard
;; Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

(define-base16-color-theme "gruvbox-light-hard"
  :base00 "#f9f5d7"
  :base01 "#ebdbb2"
  :base02 "#d5c4a1"
  :base03 "#bdae93"
  :base04 "#665c54"
  :base05 "#504945"
  :base06 "#3c3836"
  :base07 "#282828"
  :base08 "#9d0006"
  :base09 "#af3a03"
  :base0A "#b57614"
  :base0B "#79740e"
  :base0C "#427b58"
  :base0D "#076678"
  :base0E "#8f3f71"
  :base0F "#d65d0e")

;; Scheme: gruvbox-light-medium
;; Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

(define-base16-color-theme "gruvbox-light-medium"
  :base00 "#fbf1c7"
  :base01 "#ebdbb2"
  :base02 "#d5c4a1"
  :base03 "#bdae93"
  :base04 "#665c54"
  :base05 "#504945"
  :base06 "#3c3836"
  :base07 "#282828"
  :base08 "#9d0006"
  :base09 "#af3a03"
  :base0A "#b57614"
  :base0B "#79740e"
  :base0C "#427b58"
  :base0D "#076678"
  :base0E "#8f3f71"
  :base0F "#d65d0e")

;; Scheme: gruvbox-light-soft
;; Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

(define-base16-color-theme "gruvbox-light-soft"
  :base00 "#f2e5bc"
  :base01 "#ebdbb2"
  :base02 "#d5c4a1"
  :base03 "#bdae93"
  :base04 "#665c54"
  :base05 "#504945"
  :base06 "#3c3836"
  :base07 "#282828"
  :base08 "#9d0006"
  :base09 "#af3a03"
  :base0A "#b57614"
  :base0B "#79740e"
  :base0C "#427b58"
  :base0D "#076678"
  :base0E "#8f3f71"
  :base0F "#d65d0e")

;; Scheme: hardcore
;; Scheme author: Chris Caller

(define-base16-color-theme "hardcore"
  :base00 "#212121"
  :base01 "#303030"
  :base02 "#353535"
  :base03 "#4A4A4A"
  :base04 "#707070"
  :base05 "#cdcdcd"
  :base06 "#e5e5e5"
  :base07 "#ffffff"
  :base08 "#f92672"
  :base09 "#fd971f"
  :base0A "#e6db74"
  :base0B "#a6e22e"
  :base0C "#708387"
  :base0D "#66d9ef"
  :base0E "#9e6ffe"
  :base0F "#e8b882")

;; Scheme: heetch-light
;; Scheme author: Geoffrey Teale (tealeg@gmail.com)

(define-base16-color-theme "heetch-light"
  :base00 "#feffff"
  :base01 "#392551"
  :base02 "#7b6d8b"
  :base03 "#9c92a8"
  :base04 "#ddd6e5"
  :base05 "#5a496e"
  :base06 "#470546"
  :base07 "#190134"
  :base08 "#27d9d5"
  :base09 "#bdb6c5"
  :base0A "#5ba2b6"
  :base0B "#f80059"
  :base0C "#c33678"
  :base0D "#47f9f5"
  :base0E "#bd0152"
  :base0F "#dedae2")

;; Scheme: heetch
;; Scheme author: Geoffrey Teale (tealeg@gmail.com)

(define-base16-color-theme "heetch"
  :base00 "#190134"
  :base01 "#392551"
  :base02 "#5A496E"
  :base03 "#7B6D8B"
  :base04 "#9C92A8"
  :base05 "#BDB6C5"
  :base06 "#DEDAE2"
  :base07 "#FEFFFF"
  :base08 "#27D9D5"
  :base09 "#5BA2B6"
  :base0A "#8F6C97"
  :base0B "#C33678"
  :base0C "#F80059"
  :base0D "#BD0152"
  :base0E "#82034C"
  :base0F "#470546")

;; Scheme: helios
;; Scheme author: Alex Meyer (https://github.com/reyemxela)

(define-base16-color-theme "helios"
  :base00 "#1d2021"
  :base01 "#383c3e"
  :base02 "#53585b"
  :base03 "#6f7579"
  :base04 "#cdcdcd"
  :base05 "#d5d5d5"
  :base06 "#dddddd"
  :base07 "#e5e5e5"
  :base08 "#d72638"
  :base09 "#eb8413"
  :base0A "#f19d1a"
  :base0B "#88b92d"
  :base0C "#1ba595"
  :base0D "#1e8bac"
  :base0E "#be4264"
  :base0F "#c85e0d")

;; Scheme: horizon-dark
;; Scheme author: Michaël Ball (http://github.com/michael-ball/)

(define-base16-color-theme "horizon-dark"
  :base00 "#1C1E26"
  :base01 "#232530"
  :base02 "#2E303E"
  :base03 "#6F6F70"
  :base04 "#9DA0A2"
  :base05 "#CBCED0"
  :base06 "#DCDFE4"
  :base07 "#E3E6EE"
  :base08 "#E93C58"
  :base09 "#E58D7D"
  :base0A "#EFB993"
  :base0B "#EFAF8E"
  :base0C "#24A8B4"
  :base0D "#DF5273"
  :base0E "#B072D1"
  :base0F "#E4A382")

;; Scheme: horizon-light
;; Scheme author: Michaël Ball (http://github.com/michael-ball/)

(define-base16-color-theme "horizon-light"
  :base00 "#FDF0ED"
  :base01 "#FADAD1"
  :base02 "#F9CBBE"
  :base03 "#BDB3B1"
  :base04 "#948C8A"
  :base05 "#403C3D"
  :base06 "#302C2D"
  :base07 "#201C1D"
  :base08 "#F7939B"
  :base09 "#F6661E"
  :base0A "#FBE0D9"
  :base0B "#94E1B0"
  :base0C "#DC3318"
  :base0D "#DA103F"
  :base0E "#1D8991"
  :base0F "#E58C92")

;; Scheme: horizon-terminal-dark
;; Scheme author: Michaël Ball (http://github.com/michael-ball/)

(define-base16-color-theme "horizon-terminal-dark"
  :base00 "#1C1E26"
  :base01 "#232530"
  :base02 "#2E303E"
  :base03 "#6F6F70"
  :base04 "#9DA0A2"
  :base05 "#CBCED0"
  :base06 "#DCDFE4"
  :base07 "#E3E6EE"
  :base08 "#E95678"
  :base09 "#FAB795"
  :base0A "#FAC29A"
  :base0B "#29D398"
  :base0C "#59E1E3"
  :base0D "#26BBD9"
  :base0E "#EE64AC"
  :base0F "#F09383")

;; Scheme: horizon-terminal-light
;; Scheme author: Michaël Ball (http://github.com/michael-ball/)

(define-base16-color-theme "horizon-terminal-light"
  :base00 "#FDF0ED"
  :base01 "#FADAD1"
  :base02 "#F9CBBE"
  :base03 "#BDB3B1"
  :base04 "#948C8A"
  :base05 "#403C3D"
  :base06 "#302C2D"
  :base07 "#201C1D"
  :base08 "#E95678"
  :base09 "#F9CEC3"
  :base0A "#FADAD1"
  :base0B "#29D398"
  :base0C "#59E1E3"
  :base0D "#26BBD9"
  :base0E "#EE64AC"
  :base0F "#F9CBBE")

;; Scheme: humanoid-dark
;; Scheme author: Thomas (tasmo) Friese

(define-base16-color-theme "humanoid-dark"
  :base00 "#232629"
  :base01 "#333b3d"
  :base02 "#484e54"
  :base03 "#60615d"
  :base04 "#c0c0bd"
  :base05 "#f8f8f2"
  :base06 "#fcfcf6"
  :base07 "#fcfcfc"
  :base08 "#f11235"
  :base09 "#ff9505"
  :base0A "#ffb627"
  :base0B "#02d849"
  :base0C "#0dd9d6"
  :base0D "#00a6fb"
  :base0E "#f15ee3"
  :base0F "#b27701")

;; Scheme: humanoid-light
;; Scheme author: Thomas (tasmo) Friese

(define-base16-color-theme "humanoid-light"
  :base00 "#f8f8f2"
  :base01 "#efefe9"
  :base02 "#deded8"
  :base03 "#c0c0bd"
  :base04 "#60615d"
  :base05 "#232629"
  :base06 "#2f3337"
  :base07 "#070708"
  :base08 "#b0151a"
  :base09 "#ff3d00"
  :base0A "#ffb627"
  :base0B "#388e3c"
  :base0C "#008e8e"
  :base0D "#0082c9"
  :base0E "#700f98"
  :base0F "#b27701")

;; Scheme: ia-dark
;; Scheme author: iA Inc. (modified by aramisgithub)

(define-base16-color-theme "ia-dark"
  :base00 "#1a1a1a"
  :base01 "#222222"
  :base02 "#1d414d"
  :base03 "#767676"
  :base04 "#b8b8b8"
  :base05 "#cccccc"
  :base06 "#e8e8e8"
  :base07 "#f8f8f8"
  :base08 "#d88568"
  :base09 "#d86868"
  :base0A "#b99353"
  :base0B "#83a471"
  :base0C "#7c9cae"
  :base0D "#8eccdd"
  :base0E "#b98eb2"
  :base0F "#8b6c37")

;; Scheme: ia-light
;; Scheme author: iA Inc. (modified by aramisgithub)

(define-base16-color-theme "ia-light"
  :base00 "#f6f6f6"
  :base01 "#dedede"
  :base02 "#bde5f2"
  :base03 "#898989"
  :base04 "#767676"
  :base05 "#181818"
  :base06 "#e8e8e8"
  :base07 "#f8f8f8"
  :base08 "#9c5a02"
  :base09 "#c43e18"
  :base0A "#c48218"
  :base0B "#38781c"
  :base0C "#2d6bb1"
  :base0D "#48bac2"
  :base0E "#a94598"
  :base0F "#8b6c37")

;; Scheme: icy
;; Scheme author: icyphox (https://icyphox.ga)

(define-base16-color-theme "icy"
  :base00 "#021012"
  :base01 "#031619"
  :base02 "#041f23"
  :base03 "#052e34"
  :base04 "#064048"
  :base05 "#095b67"
  :base06 "#0c7c8c"
  :base07 "#109cb0"
  :base08 "#16c1d9"
  :base09 "#b3ebf2"
  :base0A "#80deea"
  :base0B "#4dd0e1"
  :base0C "#26c6da"
  :base0D "#00bcd4"
  :base0E "#00acc1"
  :base0F "#0097a7")

;; Scheme: kimber
;; Scheme author: Mishka Nguyen (https://github.com/akhsiM)

(define-base16-color-theme "kimber"
  :base00 "#222222"
  :base01 "#313131"
  :base02 "#555D55"
  :base03 "#644646"
  :base04 "#5A5A5A"
  :base05 "#DEDEE7"
  :base06 "#C3C3B4"
  :base07 "#FFFFE6"
  :base08 "#C88C8C"
  :base09 "#476C88"
  :base0A "#D8B56D"
  :base0B "#99C899"
  :base0C "#78B4B4"
  :base0D "#537C9C"
  :base0E "#86CACD"
  :base0F "#704F4F")

;; Scheme: materia
;; Scheme author: Defman21

(define-base16-color-theme "materia"
  :base00 "#263238"
  :base01 "#2C393F"
  :base02 "#37474F"
  :base03 "#707880"
  :base04 "#C9CCD3"
  :base05 "#CDD3DE"
  :base06 "#D5DBE5"
  :base07 "#FFFFFF"
  :base08 "#EC5F67"
  :base09 "#EA9560"
  :base0A "#FFCC00"
  :base0B "#8BD649"
  :base0C "#80CBC4"
  :base0D "#89DDFF"
  :base0E "#82AAFF"
  :base0F "#EC5F67")

;; Scheme: material-vivid
;; Scheme author: joshyrobot

(define-base16-color-theme "material-vivid"
  :base00 "#202124"
  :base01 "#27292c"
  :base02 "#323639"
  :base03 "#44464d"
  :base04 "#676c71"
  :base05 "#80868b"
  :base06 "#9e9e9e"
  :base07 "#ffffff"
  :base08 "#f44336"
  :base09 "#ff9800"
  :base0A "#ffeb3b"
  :base0B "#00e676"
  :base0C "#00bcd4"
  :base0D "#2196f3"
  :base0E "#673ab7"
  :base0F "#8d6e63")

;; Scheme: material-darker
;; Scheme author: Nate Peterson

(define-base16-color-theme "material-darker"
  :base00 "#212121"
  :base01 "#303030"
  :base02 "#353535"
  :base03 "#4A4A4A"
  :base04 "#B2CCD6"
  :base05 "#EEFFFF"
  :base06 "#EEFFFF"
  :base07 "#FFFFFF"
  :base08 "#F07178"
  :base09 "#F78C6C"
  :base0A "#FFCB6B"
  :base0B "#C3E88D"
  :base0C "#89DDFF"
  :base0D "#82AAFF"
  :base0E "#C792EA"
  :base0F "#FF5370")

;; Scheme: material-lighter
;; Scheme author: Nate Peterson

(define-base16-color-theme "material-lighter"
  :base00 "#FAFAFA"
  :base01 "#E7EAEC"
  :base02 "#CCEAE7"
  :base03 "#CCD7DA"
  :base04 "#8796B0"
  :base05 "#80CBC4"
  :base06 "#80CBC4"
  :base07 "#FFFFFF"
  :base08 "#FF5370"
  :base09 "#F76D47"
  :base0A "#FFB62C"
  :base0B "#91B859"
  :base0C "#39ADB5"
  :base0D "#6182B8"
  :base0E "#7C4DFF"
  :base0F "#E53935")

;; Scheme: material-palenight
;; Scheme author: Nate Peterson

(define-base16-color-theme "material-palenight"
  :base00 "#292D3E"
  :base01 "#444267"
  :base02 "#32374D"
  :base03 "#676E95"
  :base04 "#8796B0"
  :base05 "#959DCB"
  :base06 "#959DCB"
  :base07 "#FFFFFF"
  :base08 "#F07178"
  :base09 "#F78C6C"
  :base0A "#FFCB6B"
  :base0B "#C3E88D"
  :base0C "#89DDFF"
  :base0D "#82AAFF"
  :base0E "#C792EA"
  :base0F "#FF5370")

;; Scheme: material
;; Scheme author: Nate Peterson

(define-base16-color-theme "material"
  :base00 "#263238"
  :base01 "#2E3C43"
  :base02 "#314549"
  :base03 "#546E7A"
  :base04 "#B2CCD6"
  :base05 "#EEFFFF"
  :base06 "#EEFFFF"
  :base07 "#FFFFFF"
  :base08 "#F07178"
  :base09 "#F78C6C"
  :base0A "#FFCB6B"
  :base0B "#C3E88D"
  :base0C "#89DDFF"
  :base0D "#82AAFF"
  :base0E "#C792EA"
  :base0F "#FF5370")

;; Scheme: mellow-purple
;; Scheme author: gidsi

(define-base16-color-theme "mellow-purple"
  :base00 "#1e0528"
  :base01 "#1A092D"
  :base02 "#331354"
  :base03 "#320f55"
  :base04 "#873582"
  :base05 "#ffeeff"
  :base06 "#ffeeff"
  :base07 "#f8c0ff"
  :base08 "#00d9e9"
  :base09 "#aa00a3"
  :base0A "#955ae7"
  :base0B "#05cb0d"
  :base0C "#b900b1"
  :base0D "#550068"
  :base0E "#8991bb"
  :base0F "#4d6fff")

;; Scheme: mexico-light
;; Scheme author: Sheldon Johnson

(define-base16-color-theme "mexico-light"
  :base00 "#f8f8f8"
  :base01 "#e8e8e8"
  :base02 "#d8d8d8"
  :base03 "#b8b8b8"
  :base04 "#585858"
  :base05 "#383838"
  :base06 "#282828"
  :base07 "#181818"
  :base08 "#ab4642"
  :base09 "#dc9656"
  :base0A "#f79a0e"
  :base0B "#538947"
  :base0C "#4b8093"
  :base0D "#7cafc2"
  :base0E "#96609e"
  :base0F "#a16946")

;; Scheme: nebula
;; Scheme author: Gabriel Fontes (https://github.com/Misterio77)

(define-base16-color-theme "nebula"
  :base00 "#22273b"
  :base01 "#414f60"
  :base02 "#5a8380"
  :base03 "#6e6f72"
  :base04 "#87888b"
  :base05 "#a4a6a9"
  :base06 "#c7c9cd"
  :base07 "#8dbdaa"
  :base08 "#777abc"
  :base09 "#94929e"
  :base0A "#4f9062"
  :base0B "#6562a8"
  :base0C "#226f68"
  :base0D "#4d6bb6"
  :base0E "#716cae"
  :base0F "#8c70a7")

;; Scheme: nord
;; Scheme author: arcticicestudio

(define-base16-color-theme "nord"
  :base00 "#2E3440"
  :base01 "#3B4252"
  :base02 "#434C5E"
  :base03 "#4C566A"
  :base04 "#D8DEE9"
  :base05 "#E5E9F0"
  :base06 "#ECEFF4"
  :base07 "#8FBCBB"
  :base08 "#BF616A"
  :base09 "#D08770"
  :base0A "#EBCB8B"
  :base0B "#A3BE8C"
  :base0C "#88C0D0"
  :base0D "#81A1C1"
  :base0E "#B48EAD"
  :base0F "#5E81AC")

;; Scheme: nova
;; Scheme author: George Essig (https://github.com/gessig), Trevor D. Miller (https://trevordmiller.com)

(define-base16-color-theme "nova"
  :base00 "#3C4C55"
  :base01 "#556873"
  :base02 "#6A7D89"
  :base03 "#899BA6"
  :base04 "#899BA6"
  :base05 "#C5D4DD"
  :base06 "#899BA6"
  :base07 "#556873"
  :base08 "#83AFE5"
  :base09 "#7FC1CA"
  :base0A "#A8CE93"
  :base0B "#7FC1CA"
  :base0C "#F2C38F"
  :base0D "#83AFE5"
  :base0E "#9A93E1"
  :base0F "#F2C38F")

;; Scheme: one-light
;; Scheme author: Daniel Pfeifer (http://github.com/purpleKarrot)

(define-base16-color-theme "one-light"
  :base00 "#fafafa"
  :base01 "#f0f0f1"
  :base02 "#e5e5e6"
  :base03 "#a0a1a7"
  :base04 "#696c77"
  :base05 "#383a42"
  :base06 "#202227"
  :base07 "#090a0b"
  :base08 "#ca1243"
  :base09 "#d75f00"
  :base0A "#c18401"
  :base0B "#50a14f"
  :base0C "#0184bc"
  :base0D "#4078f2"
  :base0E "#a626a4"
  :base0F "#986801")

;; Scheme: onedark
;; Scheme author: Lalit Magant (http://github.com/tilal6991)

(define-base16-color-theme "onedark"
  :base00 "#282c34"
  :base01 "#353b45"
  :base02 "#3e4451"
  :base03 "#545862"
  :base04 "#565c64"
  :base05 "#abb2bf"
  :base06 "#b6bdca"
  :base07 "#c8ccd4"
  :base08 "#e06c75"
  :base09 "#d19a66"
  :base0A "#e5c07b"
  :base0B "#98c379"
  :base0C "#56b6c2"
  :base0D "#61afef"
  :base0E "#c678dd"
  :base0F "#be5046")

;; Scheme: outrun-dark
;; Scheme author: Hugo Delahousse (http://github.com/hugodelahousse/)

(define-base16-color-theme "outrun-dark"
  :base00 "#00002A"
  :base01 "#20204A"
  :base02 "#30305A"
  :base03 "#50507A"
  :base04 "#B0B0DA"
  :base05 "#D0D0FA"
  :base06 "#E0E0FF"
  :base07 "#F5F5FF"
  :base08 "#FF4242"
  :base09 "#FC8D28"
  :base0A "#F3E877"
  :base0B "#59F176"
  :base0C "#0EF0F0"
  :base0D "#66B0FF"
  :base0E "#F10596"
  :base0F "#F003EF")

;; Scheme: papercolor-dark
;; Scheme author: Jon Leopard (http://github.com/jonleopard) based on PaperColor Theme (https://github.com/NLKNguyen/papercolor-theme)

(define-base16-color-theme "papercolor-dark"
  :base00 "#1c1c1c"
  :base01 "#af005f"
  :base02 "#5faf00"
  :base03 "#d7af5f"
  :base04 "#5fafd7"
  :base05 "#808080"
  :base06 "#d7875f"
  :base07 "#d0d0d0"
  :base08 "#585858"
  :base09 "#5faf5f"
  :base0A "#afd700"
  :base0B "#af87d7"
  :base0C "#ffaf00"
  :base0D "#ff5faf"
  :base0E "#00afaf"
  :base0F "#5f8787")

;; Scheme: papercolor-light
;; Scheme author: Jon Leopard (http://github.com/jonleopard) based on PaperColor Theme (https://github.com/NLKNguyen/papercolor-theme)

(define-base16-color-theme "papercolor-light"
  :base00 "#eeeeee"
  :base01 "#af0000"
  :base02 "#008700"
  :base03 "#5f8700"
  :base04 "#0087af"
  :base05 "#444444"
  :base06 "#005f87"
  :base07 "#878787"
  :base08 "#bcbcbc"
  :base09 "#d70000"
  :base0A "#d70087"
  :base0B "#8700af"
  :base0C "#d75f00"
  :base0D "#d75f00"
  :base0E "#005faf"
  :base0F "#005f87")

;; Scheme: pasque
;; Scheme author: Gabriel Fontes (https://github.com/Misterio77)

(define-base16-color-theme "pasque"
  :base00 "#271C3A"
  :base01 "#100323"
  :base02 "#3E2D5C"
  :base03 "#5D5766"
  :base04 "#BEBCBF"
  :base05 "#DEDCDF"
  :base06 "#EDEAEF"
  :base07 "#BBAADD"
  :base08 "#A92258"
  :base09 "#918889"
  :base0A "#804ead"
  :base0B "#C6914B"
  :base0C "#7263AA"
  :base0D "#8E7DC6"
  :base0E "#953B9D"
  :base0F "#59325C")

;; Scheme: pinky
;; Scheme author: Benjamin (https://github.com/b3nj5m1n)

(define-base16-color-theme "pinky"
  :base00 "#171517"
  :base01 "#1b181b"
  :base02 "#1d1b1d"
  :base03 "#383338"
  :base04 "#e7dbdb"
  :base05 "#f5f5f5"
  :base06 "#ffffff"
  :base07 "#f7f3f7"
  :base08 "#ffa600"
  :base09 "#00ff66"
  :base0A "#20df6c"
  :base0B "#ff0066"
  :base0C "#6600ff"
  :base0D "#00ffff"
  :base0E "#007fff"
  :base0F "#df206c")

;; Scheme: porple
;; Scheme author: Niek den Breeje (https://github.com/AuditeMarlow)

(define-base16-color-theme "porple"
  :base00 "#292c36"
  :base01 "#333344"
  :base02 "#474160"
  :base03 "#65568a"
  :base04 "#b8b8b8"
  :base05 "#d8d8d8"
  :base06 "#e8e8e8"
  :base07 "#f8f8f8"
  :base08 "#f84547"
  :base09 "#d28e5d"
  :base0A "#efa16b"
  :base0B "#95c76f"
  :base0C "#64878f"
  :base0D "#8485ce"
  :base0E "#b74989"
  :base0F "#986841")

;; Scheme: qualia
;; Scheme author: isaacwhanson

(define-base16-color-theme "qualia"
  :base00 "#101010"
  :base01 "#454545"
  :base02 "#454545"
  :base03 "#454545"
  :base04 "#808080"
  :base05 "#C0C0C0"
  :base06 "#C0C0C0"
  :base07 "#454545"
  :base08 "#EFA6A2"
  :base09 "#A3B8EF"
  :base0A "#E6A3DC"
  :base0B "#80C990"
  :base0C "#C8C874"
  :base0D "#50CACD"
  :base0E "#E0AF85"
  :base0F "#808080")

;; Scheme: rebecca
;; Scheme author: Victor Borja (http://github.com/vic) based on Rebecca Theme (http://github.com/vic/rebecca-theme)

(define-base16-color-theme "rebecca"
  :base00 "#292a44"
  :base01 "#663399"
  :base02 "#383a62"
  :base03 "#666699"
  :base04 "#a0a0c5"
  :base05 "#f1eff8"
  :base06 "#ccccff"
  :base07 "#53495d"
  :base08 "#a0a0c5"
  :base09 "#efe4a1"
  :base0A "#ae81ff"
  :base0B "#6dfedf"
  :base0C "#8eaee0"
  :base0D "#2de0a7"
  :base0E "#7aa5ff"
  :base0F "#ff79c6")

;; Scheme: rose-pine-dawn
;; Scheme author: Emilia Dunfelt &lt;sayhi@dunfelt.se&gt;

(define-base16-color-theme "rose-pine-dawn"
  :base00 "#faf4ed"
  :base01 "#fffaf3"
  :base02 "#f2e9de"
  :base03 "#9893a5"
  :base04 "#6e6a86"
  :base05 "#575279"
  :base06 "#555169"
  :base07 "#26233a"
  :base08 "#1f1d2e"
  :base09 "#b4637a"
  :base0A "#ea9d34"
  :base0B "#d7827e"
  :base0C "#286983"
  :base0D "#56949f"
  :base0E "#907aa9"
  :base0F "#c5c3ce")

;; Scheme: rose-pine-moon
;; Scheme author: Emilia Dunfelt &lt;sayhi@dunfelt.se&gt;

(define-base16-color-theme "rose-pine-moon"
  :base00 "#232136"
  :base01 "#2a273f"
  :base02 "#393552"
  :base03 "#59546d"
  :base04 "#817c9c"
  :base05 "#e0def4"
  :base06 "#f5f5f7"
  :base07 "#d9d7e1"
  :base08 "#ecebf0"
  :base09 "#eb6f92"
  :base0A "#f6c177"
  :base0B "#ea9a97"
  :base0C "#3e8fb0"
  :base0D "#9ccfd8"
  :base0E "#c4a7e7"
  :base0F "#b9b9bc")

;; Scheme: rose-pine
;; Scheme author: Emilia Dunfelt &lt;sayhi@dunfelt.se&gt;

(define-base16-color-theme "rose-pine"
  :base00 "#191724"
  :base01 "#1f1d2e"
  :base02 "#26233a"
  :base03 "#555169"
  :base04 "#6e6a86"
  :base05 "#e0def4"
  :base06 "#f0f0f3"
  :base07 "#c5c3ce"
  :base08 "#e2e1e7"
  :base09 "#eb6f92"
  :base0A "#f6c177"
  :base0B "#ebbcba"
  :base0C "#31748f"
  :base0D "#9ccfd8"
  :base0E "#c4a7e7"
  :base0F "#e5e5e5")

;; Scheme: sagelight
;; Scheme author: Carter Veldhuizen

(define-base16-color-theme "sagelight"
  :base00 "#f8f8f8"
  :base01 "#e8e8e8"
  :base02 "#d8d8d8"
  :base03 "#b8b8b8"
  :base04 "#585858"
  :base05 "#383838"
  :base06 "#282828"
  :base07 "#181818"
  :base08 "#fa8480"
  :base09 "#ffaa61"
  :base0A "#ffdc61"
  :base0B "#a0d2c8"
  :base0C "#a2d6f5"
  :base0D "#a0a7d2"
  :base0E "#c8a0d2"
  :base0F "#d2b2a0")

;; Scheme: sakura
;; Scheme author: Misterio77 (http://github.com/Misterio77)

(define-base16-color-theme "sakura"
  :base00 "#feedf3"
  :base01 "#f8e2e7"
  :base02 "#e0ccd1"
  :base03 "#755f64"
  :base04 "#665055"
  :base05 "#564448"
  :base06 "#42383a"
  :base07 "#33292b"
  :base08 "#df2d52"
  :base09 "#f6661e"
  :base0A "#c29461"
  :base0B "#2e916d"
  :base0C "#1d8991"
  :base0D "#006e93"
  :base0E "#5e2180"
  :base0F "#ba0d35")

;; Scheme: sandcastle
;; Scheme author: George Essig (https://github.com/gessig)

(define-base16-color-theme "sandcastle"
  :base00 "#282c34"
  :base01 "#2c323b"
  :base02 "#3e4451"
  :base03 "#665c54"
  :base04 "#928374"
  :base05 "#a89984"
  :base06 "#d5c4a1"
  :base07 "#fdf4c1"
  :base08 "#83a598"
  :base09 "#a07e3b"
  :base0A "#a07e3b"
  :base0B "#528b8b"
  :base0C "#83a598"
  :base0D "#83a598"
  :base0E "#d75f5f"
  :base0F "#a87322")

;; Scheme: shades-of-purple
;; Scheme author: Iolar Demartini Junior (http://github.com/demartini) based on Shades of Purple Theme (https://github.com/ahmadawais/shades-of-purple-vscode).

(define-base16-color-theme "shades-of-purple"
  :base00 "#1e1e3f"
  :base01 "#43d426"
  :base02 "#f1d000"
  :base03 "#808080"
  :base04 "#6871ff"
  :base05 "#c7c7c7"
  :base06 "#ff77ff"
  :base07 "#ffffff"
  :base08 "#d90429"
  :base09 "#f92a1c"
  :base0A "#ffe700"
  :base0B "#3ad900"
  :base0C "#00c5c7"
  :base0D "#6943ff"
  :base0E "#ff2c70"
  :base0F "#79e8fb")

;; Scheme: silk-dark
;; Scheme author: Gabriel Fontes (https://github.com/Misterio77)

(define-base16-color-theme "silk-dark"
  :base00 "#0e3c46"
  :base01 "#1D494E"
  :base02 "#2A5054"
  :base03 "#587073"
  :base04 "#9DC8CD"
  :base05 "#C7DBDD"
  :base06 "#CBF2F7"
  :base07 "#D2FAFF"
  :base08 "#fb6953"
  :base09 "#fcab74"
  :base0A "#fce380"
  :base0B "#73d8ad"
  :base0C "#3fb2b9"
  :base0D "#46bddd"
  :base0E "#756b8a"
  :base0F "#9b647b")

;; Scheme: silk-light
;; Scheme author: Gabriel Fontes (https://github.com/Misterio77)

(define-base16-color-theme "silk-light"
  :base00 "#E9F1EF"
  :base01 "#CCD4D3"
  :base02 "#90B7B6"
  :base03 "#5C787B"
  :base04 "#4B5B5F"
  :base05 "#385156"
  :base06 "#0e3c46"
  :base07 "#D2FAFF"
  :base08 "#CF432E"
  :base09 "#D27F46"
  :base0A "#CFAD25"
  :base0B "#6CA38C"
  :base0C "#329CA2"
  :base0D "#39AAC9"
  :base0E "#6E6582"
  :base0F "#865369")

;; Scheme: snazzy
;; Scheme author: Chawye Hsu (https://github.com/chawyehsu) based on Hyper Snazzy Theme (https://github.com/sindresorhus/hyper-snazzy)

(define-base16-color-theme "snazzy"
  :base00 "#282a36"
  :base01 "#34353e"
  :base02 "#43454f"
  :base03 "#78787e"
  :base04 "#a5a5a9"
  :base05 "#e2e4e5"
  :base06 "#eff0eb"
  :base07 "#f1f1f0"
  :base08 "#ff5c57"
  :base09 "#ff9f43"
  :base0A "#f3f99d"
  :base0B "#5af78e"
  :base0C "#9aedfe"
  :base0D "#57c7ff"
  :base0E "#ff6ac1"
  :base0F "#b2643c")

;; Scheme: solarflare-light
;; Scheme author: Chuck Harmston (https://chuck.harmston.ch)

(define-base16-color-theme "solarflare-light"
  :base00 "#F5F7FA"
  :base01 "#E8E9ED"
  :base02 "#A6AFB8"
  :base03 "#85939E"
  :base04 "#667581"
  :base05 "#586875"
  :base06 "#222E38"
  :base07 "#18262F"
  :base08 "#EF5253"
  :base09 "#E66B2B"
  :base0A "#E4B51C"
  :base0B "#7CC844"
  :base0C "#52CBB0"
  :base0D "#33B5E1"
  :base0E "#A363D5"
  :base0F "#D73C9A")

;; Scheme: solarflare
;; Scheme author: Chuck Harmston (https://chuck.harmston.ch)

(define-base16-color-theme "solarflare"
  :base00 "#18262F"
  :base01 "#222E38"
  :base02 "#586875"
  :base03 "#667581"
  :base04 "#85939E"
  :base05 "#A6AFB8"
  :base06 "#E8E9ED"
  :base07 "#F5F7FA"
  :base08 "#EF5253"
  :base09 "#E66B2B"
  :base0A "#E4B51C"
  :base0B "#7CC844"
  :base0C "#52CBB0"
  :base0D "#33B5E1"
  :base0E "#A363D5"
  :base0F "#D73C9A")

;; Scheme: solarized-dark
;; Scheme author: Ethan Schoonover (modified by aramisgithub)

(define-base16-color-theme "solarized-dark"
  :base00 "#002b36"
  :base01 "#073642"
  :base02 "#586e75"
  :base03 "#657b83"
  :base04 "#839496"
  :base05 "#93a1a1"
  :base06 "#eee8d5"
  :base07 "#fdf6e3"
  :base08 "#dc322f"
  :base09 "#cb4b16"
  :base0A "#b58900"
  :base0B "#859900"
  :base0C "#2aa198"
  :base0D "#268bd2"
  :base0E "#6c71c4"
  :base0F "#d33682")

;; Scheme: solarized-light
;; Scheme author: Ethan Schoonover (modified by aramisgithub)

(define-base16-color-theme "solarized-light"
  :base00 "#fdf6e3"
  :base01 "#eee8d5"
  :base02 "#93a1a1"
  :base03 "#839496"
  :base04 "#657b83"
  :base05 "#586e75"
  :base06 "#073642"
  :base07 "#002b36"
  :base08 "#dc322f"
  :base09 "#cb4b16"
  :base0A "#b58900"
  :base0B "#859900"
  :base0C "#2aa198"
  :base0D "#268bd2"
  :base0E "#6c71c4"
  :base0F "#d33682")

;; Scheme: summercamp
;; Scheme author: zoe firi (zoefiri.github.io)

(define-base16-color-theme "summercamp"
  :base00 "#1c1810"
  :base01 "#2a261c"
  :base02 "#3a3527"
  :base03 "#504b38"
  :base04 "#5f5b45"
  :base05 "#736e55"
  :base06 "#bab696"
  :base07 "#f8f5de"
  :base08 "#e35142"
  :base09 "#fba11b"
  :base0A "#f2ff27"
  :base0B "#5ceb5a"
  :base0C "#5aebbc"
  :base0D "#489bf0"
  :base0E "#FF8080"
  :base0F "#F69BE7")

;; Scheme: summerfruit-dark
;; Scheme author: Christopher Corley (http://christop.club/)

(define-base16-color-theme "summerfruit-dark"
  :base00 "#151515"
  :base01 "#202020"
  :base02 "#303030"
  :base03 "#505050"
  :base04 "#B0B0B0"
  :base05 "#D0D0D0"
  :base06 "#E0E0E0"
  :base07 "#FFFFFF"
  :base08 "#FF0086"
  :base09 "#FD8900"
  :base0A "#ABA800"
  :base0B "#00C918"
  :base0C "#1FAAAA"
  :base0D "#3777E6"
  :base0E "#AD00A1"
  :base0F "#CC6633")

;; Scheme: summerfruit-light
;; Scheme author: Christopher Corley (http://christop.club/)

(define-base16-color-theme "summerfruit-light"
  :base00 "#FFFFFF"
  :base01 "#E0E0E0"
  :base02 "#D0D0D0"
  :base03 "#B0B0B0"
  :base04 "#000000"
  :base05 "#101010"
  :base06 "#151515"
  :base07 "#202020"
  :base08 "#FF0086"
  :base09 "#FD8900"
  :base0A "#ABA800"
  :base0B "#00C918"
  :base0C "#1FAAAA"
  :base0D "#3777E6"
  :base0E "#AD00A1"
  :base0F "#CC6633")

;; Scheme: synth-midnight-dark
;; Scheme author: Michaël Ball (http://github.com/michael-ball/)

(define-base16-color-theme "synth-midnight-dark"
  :base00 "#050608"
  :base01 "#1a1b1c"
  :base02 "#28292a"
  :base03 "#474849"
  :base04 "#a3a5a6"
  :base05 "#c1c3c4"
  :base06 "#cfd1d2"
  :base07 "#dddfe0"
  :base08 "#b53b50"
  :base09 "#ea770d"
  :base0A "#c9d364"
  :base0B "#06ea61"
  :base0C "#42fff9"
  :base0D "#03aeff"
  :base0E "#ea5ce2"
  :base0F "#cd6320")

;; Scheme: synth-midnight-light
;; Scheme author: Michaël Ball (http://github.com/michael-ball/)

(define-base16-color-theme "synth-midnight-light"
  :base00 "#dddfe0"
  :base01 "#cfd1d2"
  :base02 "#c1c3c4"
  :base03 "#a3a5a6"
  :base04 "#474849"
  :base05 "#28292a"
  :base06 "#1a1b1c"
  :base07 "#050608"
  :base08 "#b53b50"
  :base09 "#ea770d"
  :base0A "#c9d364"
  :base0B "#06ea61"
  :base0C "#42fff9"
  :base0D "#03aeff"
  :base0E "#ea5ce2"
  :base0F "#cd6320")

;; Scheme: tango
;; Scheme author: @Schnouki, based on the Tango Desktop Project

(define-base16-color-theme "tango"
  :base00 "#2e3436"
  :base01 "#8ae234"
  :base02 "#fce94f"
  :base03 "#555753"
  :base04 "#729fcf"
  :base05 "#d3d7cf"
  :base06 "#ad7fa8"
  :base07 "#eeeeec"
  :base08 "#cc0000"
  :base09 "#ef2929"
  :base0A "#c4a000"
  :base0B "#4e9a06"
  :base0C "#06989a"
  :base0D "#3465a4"
  :base0E "#75507b"
  :base0F "#34e2e2")

;; Scheme: tender
;; Scheme author: Jacobo Tabernero (https://github/com/jacoborus/tender.vim)

(define-base16-color-theme "tender"
  :base00 "#282828"
  :base01 "#383838"
  :base02 "#484848"
  :base03 "#4c4c4c"
  :base04 "#b8b8b8"
  :base05 "#eeeeee"
  :base06 "#e8e8e8"
  :base07 "#feffff"
  :base08 "#f43753"
  :base09 "#dc9656"
  :base0A "#ffc24b"
  :base0B "#c9d05c"
  :base0C "#73cef4"
  :base0D "#b3deef"
  :base0E "#d3b987"
  :base0F "#a16946")

;; Scheme: twilight
;; Scheme author: David Hart (https://github.com/hartbit)

(define-base16-color-theme "twilight"
  :base00 "#1e1e1e"
  :base01 "#323537"
  :base02 "#464b50"
  :base03 "#5f5a60"
  :base04 "#838184"
  :base05 "#a7a7a7"
  :base06 "#c3c3c3"
  :base07 "#ffffff"
  :base08 "#cf6a4c"
  :base09 "#cda869"
  :base0A "#f9ee98"
  :base0B "#8f9d6a"
  :base0C "#afc4db"
  :base0D "#7587a6"
  :base0E "#9b859d"
  :base0F "#9b703f")

;; Scheme: 3024
;; Scheme author: Jan T. Sott (http://github.com/idleberg)

(define-base16-color-theme "3024"
  :base00 "#090300"
  :base01 "#3a3432"
  :base02 "#4a4543"
  :base03 "#5c5855"
  :base04 "#807d7c"
  :base05 "#a5a2a2"
  :base06 "#d6d5d4"
  :base07 "#f7f7f7"
  :base08 "#db2d20"
  :base09 "#e8bbd0"
  :base0A "#fded02"
  :base0B "#01a252"
  :base0C "#b5e4f4"
  :base0D "#01a0e4"
  :base0E "#a16a94"
  :base0F "#cdab53")

;; Scheme: apathy
;; Scheme author: Jannik Siebert (https://github.com/janniks)

(define-base16-color-theme "apathy"
  :base00 "#031A16"
  :base01 "#0B342D"
  :base02 "#184E45"
  :base03 "#2B685E"
  :base04 "#5F9C92"
  :base05 "#81B5AC"
  :base06 "#A7CEC8"
  :base07 "#D2E7E4"
  :base08 "#3E9688"
  :base09 "#3E7996"
  :base0A "#3E4C96"
  :base0B "#883E96"
  :base0C "#963E4C"
  :base0D "#96883E"
  :base0E "#4C963E"
  :base0F "#3E965B")

;; Scheme: ashes
;; Scheme author: Jannik Siebert (https://github.com/janniks)

(define-base16-color-theme "ashes"
  :base00 "#1C2023"
  :base01 "#393F45"
  :base02 "#565E65"
  :base03 "#747C84"
  :base04 "#ADB3BA"
  :base05 "#C7CCD1"
  :base06 "#DFE2E5"
  :base07 "#F3F4F5"
  :base08 "#C7AE95"
  :base09 "#C7C795"
  :base0A "#AEC795"
  :base0B "#95C7AE"
  :base0C "#95AEC7"
  :base0D "#AE95C7"
  :base0E "#C795AE"
  :base0F "#C79595")

;; Scheme: bespin
;; Scheme author: Jan T. Sott

(define-base16-color-theme "bespin"
  :base00 "#28211c"
  :base01 "#36312e"
  :base02 "#5e5d5c"
  :base03 "#666666"
  :base04 "#797977"
  :base05 "#8a8986"
  :base06 "#9d9b97"
  :base07 "#baae9e"
  :base08 "#cf6a4c"
  :base09 "#cf7d34"
  :base0A "#f9ee98"
  :base0B "#54be0d"
  :base0C "#afc4db"
  :base0D "#5ea6ea"
  :base0E "#9b859d"
  :base0F "#937121")

;; Scheme: brewer
;; Scheme author: Timothée Poisot (http://github.com/tpoisot)

(define-base16-color-theme "brewer"
  :base00 "#0c0d0e"
  :base01 "#2e2f30"
  :base02 "#515253"
  :base03 "#737475"
  :base04 "#959697"
  :base05 "#b7b8b9"
  :base06 "#dadbdc"
  :base07 "#fcfdfe"
  :base08 "#e31a1c"
  :base09 "#e6550d"
  :base0A "#dca060"
  :base0B "#31a354"
  :base0C "#80b1d3"
  :base0D "#3182bd"
  :base0E "#756bb1"
  :base0F "#b15928")

;; Scheme: bright
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "bright"
  :base00 "#000000"
  :base01 "#303030"
  :base02 "#505050"
  :base03 "#b0b0b0"
  :base04 "#d0d0d0"
  :base05 "#e0e0e0"
  :base06 "#f5f5f5"
  :base07 "#ffffff"
  :base08 "#fb0120"
  :base09 "#fc6d24"
  :base0A "#fda331"
  :base0B "#a1c659"
  :base0C "#76c7b7"
  :base0D "#6fb3d2"
  :base0E "#d381c3"
  :base0F "#be643c")

;; Scheme: chalk
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "chalk"
  :base00 "#151515"
  :base01 "#202020"
  :base02 "#303030"
  :base03 "#505050"
  :base04 "#b0b0b0"
  :base05 "#d0d0d0"
  :base06 "#e0e0e0"
  :base07 "#f5f5f5"
  :base08 "#fb9fb1"
  :base09 "#eda987"
  :base0A "#ddb26f"
  :base0B "#acc267"
  :base0C "#12cfc0"
  :base0D "#6fc2ef"
  :base0E "#e1a3ee"
  :base0F "#deaf8f")

;; Scheme: darktooth
;; Scheme author: Jason Milkins (https://github.com/jasonm23)

(define-base16-color-theme "darktooth"
  :base00 "#1D2021"
  :base01 "#32302F"
  :base02 "#504945"
  :base03 "#665C54"
  :base04 "#928374"
  :base05 "#A89984"
  :base06 "#D5C4A1"
  :base07 "#FDF4C1"
  :base08 "#FB543F"
  :base09 "#FE8625"
  :base0A "#FAC03B"
  :base0B "#95C085"
  :base0C "#8BA59B"
  :base0D "#0D6678"
  :base0E "#8F4673"
  :base0F "#A87322")

;; Scheme: embers
;; Scheme author: Jannik Siebert (https://github.com/janniks)

(define-base16-color-theme "embers"
  :base00 "#16130F"
  :base01 "#2C2620"
  :base02 "#433B32"
  :base03 "#5A5047"
  :base04 "#8A8075"
  :base05 "#A39A90"
  :base06 "#BEB6AE"
  :base07 "#DBD6D1"
  :base08 "#826D57"
  :base09 "#828257"
  :base0A "#6D8257"
  :base0B "#57826D"
  :base0C "#576D82"
  :base0D "#6D5782"
  :base0E "#82576D"
  :base0F "#825757")

;; Scheme: flat
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "flat"
  :base00 "#2C3E50"
  :base01 "#34495E"
  :base02 "#7F8C8D"
  :base03 "#95A5A6"
  :base04 "#BDC3C7"
  :base05 "#e0e0e0"
  :base06 "#f5f5f5"
  :base07 "#ECF0F1"
  :base08 "#E74C3C"
  :base09 "#E67E22"
  :base0A "#F1C40F"
  :base0B "#2ECC71"
  :base0C "#1ABC9C"
  :base0D "#3498DB"
  :base0E "#9B59B6"
  :base0F "#be643c")

;; Scheme: google-dark
;; Scheme author: Seth Wright (http://sethawright.com)

(define-base16-color-theme "google-dark"
  :base00 "#1d1f21"
  :base01 "#282a2e"
  :base02 "#373b41"
  :base03 "#969896"
  :base04 "#b4b7b4"
  :base05 "#c5c8c6"
  :base06 "#e0e0e0"
  :base07 "#ffffff"
  :base08 "#CC342B"
  :base09 "#F96A38"
  :base0A "#FBA922"
  :base0B "#198844"
  :base0C "#3971ED"
  :base0D "#3971ED"
  :base0E "#A36AC7"
  :base0F "#3971ED")

;; Scheme: google-light
;; Scheme author: Seth Wright (http://sethawright.com)

(define-base16-color-theme "google-light"
  :base00 "#ffffff"
  :base01 "#e0e0e0"
  :base02 "#c5c8c6"
  :base03 "#b4b7b4"
  :base04 "#969896"
  :base05 "#373b41"
  :base06 "#282a2e"
  :base07 "#1d1f21"
  :base08 "#CC342B"
  :base09 "#F96A38"
  :base0A "#FBA922"
  :base0B "#198844"
  :base0C "#3971ED"
  :base0D "#3971ED"
  :base0E "#A36AC7"
  :base0F "#3971ED")

;; Scheme: grayscale-dark
;; Scheme author: Alexandre Gavioli (https://github.com/Alexx2/)

(define-base16-color-theme "grayscale-dark"
  :base00 "#101010"
  :base01 "#252525"
  :base02 "#464646"
  :base03 "#525252"
  :base04 "#ababab"
  :base05 "#b9b9b9"
  :base06 "#e3e3e3"
  :base07 "#f7f7f7"
  :base08 "#7c7c7c"
  :base09 "#999999"
  :base0A "#a0a0a0"
  :base0B "#8e8e8e"
  :base0C "#868686"
  :base0D "#686868"
  :base0E "#747474"
  :base0F "#5e5e5e")

;; Scheme: grayscale-light
;; Scheme author: Alexandre Gavioli (https://github.com/Alexx2/)

(define-base16-color-theme "grayscale-light"
  :base00 "#f7f7f7"
  :base01 "#e3e3e3"
  :base02 "#b9b9b9"
  :base03 "#ababab"
  :base04 "#525252"
  :base05 "#464646"
  :base06 "#252525"
  :base07 "#101010"
  :base08 "#7c7c7c"
  :base09 "#999999"
  :base0A "#a0a0a0"
  :base0B "#8e8e8e"
  :base0C "#868686"
  :base0D "#686868"
  :base0E "#747474"
  :base0F "#5e5e5e")

;; Scheme: greenscreen
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "greenscreen"
  :base00 "#001100"
  :base01 "#003300"
  :base02 "#005500"
  :base03 "#007700"
  :base04 "#009900"
  :base05 "#00bb00"
  :base06 "#00dd00"
  :base07 "#00ff00"
  :base08 "#007700"
  :base09 "#009900"
  :base0A "#007700"
  :base0B "#00bb00"
  :base0C "#005500"
  :base0D "#009900"
  :base0E "#00bb00"
  :base0F "#005500")

;; Scheme: harmonic-dark
;; Scheme author: Jannik Siebert (https://github.com/janniks)

(define-base16-color-theme "harmonic-dark"
  :base00 "#0b1c2c"
  :base01 "#223b54"
  :base02 "#405c79"
  :base03 "#627e99"
  :base04 "#aabcce"
  :base05 "#cbd6e2"
  :base06 "#e5ebf1"
  :base07 "#f7f9fb"
  :base08 "#bf8b56"
  :base09 "#bfbf56"
  :base0A "#8bbf56"
  :base0B "#56bf8b"
  :base0C "#568bbf"
  :base0D "#8b56bf"
  :base0E "#bf568b"
  :base0F "#bf5656")

;; Scheme: harmonic-light
;; Scheme author: Jannik Siebert (https://github.com/janniks)

(define-base16-color-theme "harmonic-light"
  :base00 "#f7f9fb"
  :base01 "#e5ebf1"
  :base02 "#cbd6e2"
  :base03 "#aabcce"
  :base04 "#627e99"
  :base05 "#405c79"
  :base06 "#223b54"
  :base07 "#0b1c2c"
  :base08 "#bf8b56"
  :base09 "#bfbf56"
  :base0A "#8bbf56"
  :base0B "#56bf8b"
  :base0C "#568bbf"
  :base0D "#8b56bf"
  :base0E "#bf568b"
  :base0F "#bf5656")

;; Scheme: hopscotch
;; Scheme author: Jan T. Sott

(define-base16-color-theme "hopscotch"
  :base00 "#322931"
  :base01 "#433b42"
  :base02 "#5c545b"
  :base03 "#797379"
  :base04 "#989498"
  :base05 "#b9b5b8"
  :base06 "#d5d3d5"
  :base07 "#ffffff"
  :base08 "#dd464c"
  :base09 "#fd8b19"
  :base0A "#fdcc59"
  :base0B "#8fc13e"
  :base0C "#149b93"
  :base0D "#1290bf"
  :base0E "#c85e7c"
  :base0F "#b33508")

;; Scheme: irblack
;; Scheme author: Timothée Poisot (http://timotheepoisot.fr)

(define-base16-color-theme "irblack"
  :base00 "#000000"
  :base01 "#242422"
  :base02 "#484844"
  :base03 "#6c6c66"
  :base04 "#918f88"
  :base05 "#b5b3aa"
  :base06 "#d9d7cc"
  :base07 "#fdfbee"
  :base08 "#ff6c60"
  :base09 "#e9c062"
  :base0A "#ffffb6"
  :base0B "#a8ff60"
  :base0C "#c6c5fe"
  :base0D "#96cbfe"
  :base0E "#ff73fd"
  :base0F "#b18a3d")

;; Scheme: isotope
;; Scheme author: Jan T. Sott

(define-base16-color-theme "isotope"
  :base00 "#000000"
  :base01 "#404040"
  :base02 "#606060"
  :base03 "#808080"
  :base04 "#c0c0c0"
  :base05 "#d0d0d0"
  :base06 "#e0e0e0"
  :base07 "#ffffff"
  :base08 "#ff0000"
  :base09 "#ff9900"
  :base0A "#ff0099"
  :base0B "#33ff00"
  :base0C "#00ffff"
  :base0D "#0066ff"
  :base0E "#cc00ff"
  :base0F "#3300ff")

;; Scheme: macintosh
;; Scheme author: Rebecca Bettencourt (http://www.kreativekorp.com)

(define-base16-color-theme "macintosh"
  :base00 "#000000"
  :base01 "#404040"
  :base02 "#404040"
  :base03 "#808080"
  :base04 "#808080"
  :base05 "#c0c0c0"
  :base06 "#c0c0c0"
  :base07 "#ffffff"
  :base08 "#dd0907"
  :base09 "#ff6403"
  :base0A "#fbf305"
  :base0B "#1fb714"
  :base0C "#02abea"
  :base0D "#0000d3"
  :base0E "#4700a5"
  :base0F "#90713a")

;; Scheme: marrakesh
;; Scheme author: Alexandre Gavioli (http://github.com/Alexx2/)

(define-base16-color-theme "marrakesh"
  :base00 "#201602"
  :base01 "#302e00"
  :base02 "#5f5b17"
  :base03 "#6c6823"
  :base04 "#86813b"
  :base05 "#948e48"
  :base06 "#ccc37a"
  :base07 "#faf0a5"
  :base08 "#c35359"
  :base09 "#b36144"
  :base0A "#a88339"
  :base0B "#18974e"
  :base0C "#75a738"
  :base0D "#477ca1"
  :base0E "#8868b3"
  :base0F "#b3588e")

;; Scheme: monokai
;; Scheme author: Wimer Hazenberg (http://www.monokai.nl)

(define-base16-color-theme "monokai"
  :base00 "#272822"
  :base01 "#383830"
  :base02 "#49483e"
  :base03 "#75715e"
  :base04 "#a59f85"
  :base05 "#f8f8f2"
  :base06 "#f5f4f1"
  :base07 "#f9f8f5"
  :base08 "#f92672"
  :base09 "#fd971f"
  :base0A "#f4bf75"
  :base0B "#a6e22e"
  :base0C "#a1efe4"
  :base0D "#66d9ef"
  :base0E "#ae81ff"
  :base0F "#cc6633")

;; Scheme: oceanicnext
;; Scheme author: https://github.com/voronianski/oceanic-next-color-scheme

(define-base16-color-theme "oceanicnext"
  :base00 "#1B2B34"
  :base01 "#343D46"
  :base02 "#4F5B66"
  :base03 "#65737E"
  :base04 "#A7ADBA"
  :base05 "#C0C5CE"
  :base06 "#CDD3DE"
  :base07 "#D8DEE9"
  :base08 "#EC5f67"
  :base09 "#F99157"
  :base0A "#FAC863"
  :base0B "#99C794"
  :base0C "#5FB3B3"
  :base0D "#6699CC"
  :base0E "#C594C5"
  :base0F "#AB7967")

;; Scheme: paraiso
;; Scheme author: Jan T. Sott

(define-base16-color-theme "paraiso"
  :base00 "#2f1e2e"
  :base01 "#41323f"
  :base02 "#4f424c"
  :base03 "#776e71"
  :base04 "#8d8687"
  :base05 "#a39e9b"
  :base06 "#b9b6b0"
  :base07 "#e7e9db"
  :base08 "#ef6155"
  :base09 "#f99b15"
  :base0A "#fec418"
  :base0B "#48b685"
  :base0C "#5bc4bf"
  :base0D "#06b6ef"
  :base0E "#815ba4"
  :base0F "#e96ba8")

;; Scheme: phd
;; Scheme author: Hennig Hasemann (http://leetless.de/vim.html)

(define-base16-color-theme "phd"
  :base00 "#061229"
  :base01 "#2a3448"
  :base02 "#4d5666"
  :base03 "#717885"
  :base04 "#9a99a3"
  :base05 "#b8bbc2"
  :base06 "#dbdde0"
  :base07 "#ffffff"
  :base08 "#d07346"
  :base09 "#f0a000"
  :base0A "#fbd461"
  :base0B "#99bf52"
  :base0C "#72b9bf"
  :base0D "#5299bf"
  :base0E "#9989cc"
  :base0F "#b08060")

;; Scheme: pico
;; Scheme author: PICO-8 (http://www.lexaloffle.com/pico-8.php)

(define-base16-color-theme "pico"
  :base00 "#000000"
  :base01 "#1d2b53"
  :base02 "#7e2553"
  :base03 "#008751"
  :base04 "#ab5236"
  :base05 "#5f574f"
  :base06 "#c2c3c7"
  :base07 "#fff1e8"
  :base08 "#ff004d"
  :base09 "#ffa300"
  :base0A "#fff024"
  :base0B "#00e756"
  :base0C "#29adff"
  :base0D "#83769c"
  :base0E "#ff77a8"
  :base0F "#ffccaa")

;; Scheme: pop
;; Scheme author: Chris Kempson (http://chriskempson.com)

(define-base16-color-theme "pop"
  :base00 "#000000"
  :base01 "#202020"
  :base02 "#303030"
  :base03 "#505050"
  :base04 "#b0b0b0"
  :base05 "#d0d0d0"
  :base06 "#e0e0e0"
  :base07 "#ffffff"
  :base08 "#eb008a"
  :base09 "#f29333"
  :base0A "#f8ca12"
  :base0B "#37b349"
  :base0C "#00aabb"
  :base0D "#0e5a94"
  :base0E "#b31e8d"
  :base0F "#7a2d00")

;; Scheme: railscasts
;; Scheme author: Ryan Bates (http://railscasts.com)

(define-base16-color-theme "railscasts"
  :base00 "#2b2b2b"
  :base01 "#272935"
  :base02 "#3a4055"
  :base03 "#5a647e"
  :base04 "#d4cfc9"
  :base05 "#e6e1dc"
  :base06 "#f4f1ed"
  :base07 "#f9f7f3"
  :base08 "#da4939"
  :base09 "#cc7833"
  :base0A "#ffc66d"
  :base0B "#a5c261"
  :base0C "#519f50"
  :base0D "#6d9cbe"
  :base0E "#b6b3eb"
  :base0F "#bc9458")

;; Scheme: seti
;; Scheme author:

(define-base16-color-theme "seti"
  :base00 "#151718"
  :base01 "#282a2b"
  :base02 "#3B758C"
  :base03 "#41535B"
  :base04 "#43a5d5"
  :base05 "#d6d6d6"
  :base06 "#eeeeee"
  :base07 "#ffffff"
  :base08 "#Cd3f45"
  :base09 "#db7b55"
  :base0A "#e6cd69"
  :base0B "#9fca56"
  :base0C "#55dbbe"
  :base0D "#55b5db"
  :base0E "#a074c4"
  :base0F "#8a553f")

;; Scheme: shapeshifter
;; Scheme author: Tyler Benziger (http://tybenz.com)

(define-base16-color-theme "shapeshifter"
  :base00 "#f9f9f9"
  :base01 "#e0e0e0"
  :base02 "#ababab"
  :base03 "#555555"
  :base04 "#343434"
  :base05 "#102015"
  :base06 "#040404"
  :base07 "#000000"
  :base08 "#e92f2f"
  :base09 "#e09448"
  :base0A "#dddd13"
  :base0B "#0ed839"
  :base0C "#23edda"
  :base0D "#3b48e3"
  :base0E "#f996e2"
  :base0F "#69542d")

;; Scheme: spacemacs
;; Scheme author: Nasser Alshammari (https://github.com/nashamri/spacemacs-theme)

(define-base16-color-theme "spacemacs"
  :base00 "#1f2022"
  :base01 "#282828"
  :base02 "#444155"
  :base03 "#585858"
  :base04 "#b8b8b8"
  :base05 "#a3a3a3"
  :base06 "#e8e8e8"
  :base07 "#f8f8f8"
  :base08 "#f2241f"
  :base09 "#ffa500"
  :base0A "#b1951d"
  :base0B "#67b11d"
  :base0C "#2d9574"
  :base0D "#4f97d7"
  :base0E "#a31db1"
  :base0F "#b03060")

;; Scheme: tube
;; Scheme author: Jan T. Sott

(define-base16-color-theme "tube"
  :base00 "#231f20"
  :base01 "#1c3f95"
  :base02 "#5a5758"
  :base03 "#737171"
  :base04 "#959ca1"
  :base05 "#d9d8d8"
  :base06 "#e7e7e8"
  :base07 "#ffffff"
  :base08 "#ee2e24"
  :base09 "#f386a1"
  :base0A "#ffd204"
  :base0B "#00853e"
  :base0C "#85cebc"
  :base0D "#009ddc"
  :base0E "#98005d"
  :base0F "#b06110")

;; Scheme: unikitty-dark
;; Scheme author: Josh W Lewis (@joshwlewis)

(define-base16-color-theme "unikitty-dark"
  :base00 "#2e2a31"
  :base01 "#4a464d"
  :base02 "#666369"
  :base03 "#838085"
  :base04 "#9f9da2"
  :base05 "#bcbabe"
  :base06 "#d8d7da"
  :base07 "#f5f4f7"
  :base08 "#d8137f"
  :base09 "#d65407"
  :base0A "#dc8a0e"
  :base0B "#17ad98"
  :base0C "#149bda"
  :base0D "#796af5"
  :base0E "#bb60ea"
  :base0F "#c720ca")

;; Scheme: unikitty-light
;; Scheme author: Josh W Lewis (@joshwlewis)

(define-base16-color-theme "unikitty-light"
  :base00 "#ffffff"
  :base01 "#e1e1e2"
  :base02 "#c4c3c5"
  :base03 "#a7a5a8"
  :base04 "#89878b"
  :base05 "#6c696e"
  :base06 "#4f4b51"
  :base07 "#322d34"
  :base08 "#d8137f"
  :base09 "#d65407"
  :base0A "#dc8a0e"
  :base0B "#17ad98"
  :base0C "#149bda"
  :base0D "#775dff"
  :base0E "#aa17e6"
  :base0F "#e013d0")

;; Scheme: vice-alt
;; Scheme author: Thomas Leon Highbaugh

(define-base16-color-theme "vice-alt"
  :base00 "#1b1d24"
  :base01 "#282b36"
  :base02 "#2f303d"
  :base03 "#323643"
  :base04 "#3f4859"
  :base05 "#555e70"
  :base06 "#b2bfd9"
  :base07 "#f4f4f7"
  :base08 "#ff3d81"
  :base09 "#F67544"
  :base0A "#ffff73"
  :base0B "#44ffdd"
  :base0C "#00caff"
  :base0D "#2fb1d4"
  :base0E "#8265ff"
  :base0F "#ff00aa")

;; Scheme: vice
;; Scheme author: Thomas Leon Highbaugh

(define-base16-color-theme "vice"
  :base00 "#17191E"
  :base01 "#22262d"
  :base02 "#3c3f4c"
  :base03 "#383a47"
  :base04 "#555e70"
  :base05 "#8b9cbe"
  :base06 "#B2BFD9"
  :base07 "#f4f4f7"
  :base08 "#ff29a8"
  :base09 "#85ffe0"
  :base0A "#f0ffaa"
  :base0B "#0badff"
  :base0C "#8265ff"
  :base0D "#00eaff"
  :base0E "#00f6d9"
  :base0F "#ff3d81")

;; Scheme: vulcan
;; Scheme author: Andrey Varfolomeev

(define-base16-color-theme "vulcan"
  :base00 "#041523"
  :base01 "#122339"
  :base02 "#003552"
  :base03 "#7a5759"
  :base04 "#6b6977"
  :base05 "#5b778c"
  :base06 "#333238"
  :base07 "#214d68"
  :base08 "#818591"
  :base09 "#9198a3"
  :base0A "#adb4b9"
  :base0B "#977d7c"
  :base0C "#977d7c"
  :base0D "#977d7c"
  :base0E "#9198a3"
  :base0F "#977d7c")

;; Scheme: windows-10-light
;; Scheme author: Fergus Collins (https://github.com/C-Fergus)

(define-base16-color-theme "windows-10-light"
  :base00 "#f2f2f2"
  :base01 "#e5e5e5"
  :base02 "#d9d9d9"
  :base03 "#cccccc"
  :base04 "#ababab"
  :base05 "#767676"
  :base06 "#414141"
  :base07 "#0c0c0c"
  :base08 "#c50f1f"
  :base09 "#f9f1a5"
  :base0A "#c19c00"
  :base0B "#13a10e"
  :base0C "#3a96dd"
  :base0D "#0037da"
  :base0E "#881798"
  :base0F "#16c60c")

;; Scheme: windows-10
;; Scheme author: Fergus Collins (https://github.com/C-Fergus)

(define-base16-color-theme "windows-10"
  :base00 "#0c0c0c"
  :base01 "#2f2f2f"
  :base02 "#535353"
  :base03 "#767676"
  :base04 "#b9b9b9"
  :base05 "#cccccc"
  :base06 "#dfdfdf"
  :base07 "#f2f2f2"
  :base08 "#e74856"
  :base09 "#c19c00"
  :base0A "#f9f1a5"
  :base0B "#16c60c"
  :base0C "#61d6d6"
  :base0D "#3b78ff"
  :base0E "#b4009e"
  :base0F "#13a10e")

;; Scheme: windows-95-light
;; Scheme author: Fergus Collins (https://github.com/C-Fergus)

(define-base16-color-theme "windows-95-light"
  :base00 "#fcfcfc"
  :base01 "#e0e0e0"
  :base02 "#c4c4c4"
  :base03 "#a8a8a8"
  :base04 "#7e7e7e"
  :base05 "#545454"
  :base06 "#2a2a2a"
  :base07 "#000000"
  :base08 "#a80000"
  :base09 "#fcfc54"
  :base0A "#a85400"
  :base0B "#00a800"
  :base0C "#00a8a8"
  :base0D "#0000a8"
  :base0E "#a800a8"
  :base0F "#54fc54")

;; Scheme: windows-95
;; Scheme author: Fergus Collins (https://github.com/C-Fergus)

(define-base16-color-theme "windows-95"
  :base00 "#000000"
  :base01 "#1C1C1C"
  :base02 "#383838"
  :base03 "#545454"
  :base04 "#7e7e7e"
  :base05 "#a8a8a8"
  :base06 "#d2d2d2"
  :base07 "#fcfcfc"
  :base08 "#fc5454"
  :base09 "#a85400"
  :base0A "#fcfc54"
  :base0B "#54fc54"
  :base0C "#54fcfc"
  :base0D "#5454fc"
  :base0E "#fc54fc"
  :base0F "#00a800")

;; Scheme: windows-highcontrast-light
;; Scheme author: Fergus Collins (https://github.com/C-Fergus)

(define-base16-color-theme "windows-highcontrast-light"
  :base00 "#fcfcfc"
  :base01 "#e8e8e8"
  :base02 "#d4d4d4"
  :base03 "#c0c0c0"
  :base04 "#7e7e7e"
  :base05 "#545454"
  :base06 "#2a2a2a"
  :base07 "#000000"
  :base08 "#800000"
  :base09 "#fcfc54"
  :base0A "#808000"
  :base0B "#008000"
  :base0C "#008080"
  :base0D "#000080"
  :base0E "#800080"
  :base0F "#54fc54")

;; Scheme: windows-highcontrast
;; Scheme author: Fergus Collins (https://github.com/C-Fergus)

(define-base16-color-theme "windows-highcontrast"
  :base00 "#000000"
  :base01 "#1C1C1C"
  :base02 "#383838"
  :base03 "#545454"
  :base04 "#a2a2a2"
  :base05 "#c0c0c0"
  :base06 "#dedede"
  :base07 "#fcfcfc"
  :base08 "#fc5454"
  :base09 "#808000"
  :base0A "#fcfc54"
  :base0B "#54fc54"
  :base0C "#54fcfc"
  :base0D "#5454fc"
  :base0E "#fc54fc"
  :base0F "#008000")

;; Scheme: windows-nt-light
;; Scheme author: Fergus Collins (https://github.com/C-Fergus)

(define-base16-color-theme "windows-nt-light"
  :base00 "#ffffff"
  :base01 "#eaeaea"
  :base02 "#d5d5d5"
  :base03 "#c0c0c0"
  :base04 "#a0a0a0"
  :base05 "#808080"
  :base06 "#404040"
  :base07 "#000000"
  :base08 "#800000"
  :base09 "#ffff00"
  :base0A "#808000"
  :base0B "#008000"
  :base0C "#008080"
  :base0D "#000080"
  :base0E "#800080"
  :base0F "#00ff00")

;; Scheme: windows-nt
;; Scheme author: Fergus Collins (https://github.com/C-Fergus)

(define-base16-color-theme "windows-nt"
  :base00 "#000000"
  :base01 "#2a2a2a"
  :base02 "#555555"
  :base03 "#808080"
  :base04 "#a1a1a1"
  :base05 "#c0c0c0"
  :base06 "#e0e0e0"
  :base07 "#ffffff"
  :base08 "#ff0000"
  :base09 "#808000"
  :base0A "#ffff00"
  :base0B "#00ff00"
  :base0C "#00ffff"
  :base0D "#0000ff"
  :base0E "#ff00ff"
  :base0F "#008000")

;; Scheme: woodland
;; Scheme author: Jay Cornwall (https://jcornwall.com)

(define-base16-color-theme "woodland"
  :base00 "#231e18"
  :base01 "#302b25"
  :base02 "#48413a"
  :base03 "#9d8b70"
  :base04 "#b4a490"
  :base05 "#cabcb1"
  :base06 "#d7c8bc"
  :base07 "#e4d4c8"
  :base08 "#d35c5c"
  :base09 "#ca7f32"
  :base0A "#e0ac16"
  :base0B "#b7ba53"
  :base0C "#6eb958"
  :base0D "#88a4d3"
  :base0E "#bb90e2"
  :base0F "#b49368")

;; Scheme: xcode-dusk
;; Scheme author: Elsa Gonsiorowski (https://github.com/gonsie)

(define-base16-color-theme "xcode-dusk"
  :base00 "#282B35"
  :base01 "#3D4048"
  :base02 "#53555D"
  :base03 "#686A71"
  :base04 "#7E8086"
  :base05 "#939599"
  :base06 "#A9AAAE"
  :base07 "#BEBFC2"
  :base08 "#B21889"
  :base09 "#786DC5"
  :base0A "#438288"
  :base0B "#DF0002"
  :base0C "#00A0BE"
  :base0D "#790EAD"
  :base0E "#B21889"
  :base0F "#C77C48")

;; Scheme: zenburn
;; Scheme author: elnawe

(define-base16-color-theme "zenburn"
  :base00 "#383838"
  :base01 "#404040"
  :base02 "#606060"
  :base03 "#6f6f6f"
  :base04 "#808080"
  :base05 "#dcdccc"
  :base06 "#c0c0c0"
  :base07 "#ffffff"
  :base08 "#dca3a3"
  :base09 "#dfaf8f"
  :base0A "#e0cf9f"
  :base0B "#5f7f5f"
  :base0C "#93e0e3"
  :base0D "#7cb8bb"
  :base0E "#dc8cc3"
  :base0F "#000000")

;; Scheme: modus-vivendi
;; Scheme author: Protesilaos Stavrou

(define-base16-color-theme "modus-vivendi"
  :base00 "#000000"
  :base01 "#535353"
  :base02 "#5a5a5a"
  :base03 "#989898"
  :base04 "#b6a0ff"
  :base05 "#ffffff"
  :base06 "#dfcf43"
  :base07 "#fefefe"
  :base08 "#fec43f"
  :base09 "#00bcff"
  :base0A "#6ae4b9"
  :base0B "#79a8ff"
  :base0C "#f78fe7"
  :base0D "#feacd0"
  :base0E "#b6a0ff"
  :base0F "#12154a")
